Repository DataBiosphere/azul, pull requests merged in 2018-10, with the labels that each got.

#270 Added happy path webservice tests (resolves #250)
  test/service/__init__.py
  test/service/test_request_builder.py
  test/service/test_request_validation.py
Labels: HCA

#377 Updated test_transformer.py for current, expected, correct behavior (fixes #376)
  indexer/test/dcc/test_transformer.py
Labels: commons

#489 Add export format description to README and update Boardwalk dev URL (resolves #373)
  webservice/README.md
Labels: commons

#485 Parallelized Elasticsearch request for serving summary response (fixes #467)
  lambdas/service/app.py
Labels: hca

#473 Fix vulnerable dependencies (closes TLP-686)
  indexer/requirements.txt
  webservice/requirements.txt
Labels: commons

#502 Add project role to project contributors (fixes #498)
  requirements.txt
  test/indexer/data/aee55415-d128-4b30-9644-e6b2742fa32b.files.results.json
  test/indexer/data/aee55415-d128-4b30-9644-e6b2742fa32b.projects.results.json
  test/indexer/data/aee55415-d128-4b30-9644-e6b2742fa32b.specimens.results.json
  test/indexer/test_hca_indexer.py
  test/service/data_generator/fake_data_utils.py
Labels: hca

#515 Implemented the flag to enable aggregation
  src/azul/service/responseobjects/elastic_request_builder.py
Labels: hca
