Repository DataBiosphere/azul, pull requests merged in 2019-09, with the labels that each got.

#1255 Change schema dos:// to drs:// (#1252)
  src/azul/drs.py
  test/service/test_manifest.py
Labels: sandbox

#1261 Fixed content-disposition header formatting for pre-signed url (#1247)
  src/azul/service/responseobjects/storage_service.py
  test/service/test_manifest.py
  test/service/test_storage_service.py
Labels: sandbox

#1280 Change headers from DOS to DRS (#1279)
  src/azul/service/responseobjects/hca_response_v5.py
  test/service/test_manifest.py
Labels: sandbox

#1293 Added assertion to validate full manifest TSV filename (#1283)
  src/azul/service/responseobjects/storage_service.py
Labels: sandbox

#1312 Remove hotfix, use prod DSS on dev & sandbox (#1311)
  deployments/dev/environment
  deployments/sandbox/environment
  test/local_integration_test.py
Labels: sandbox, urgent

#1295 Better explain conditions for deployment with apidev.py script docs (#1292)
  README.md
Labels: hold warm

#1304 Modify work-around for zarray files (#1302)
  src/azul/project/hca/transformers.py
Labels: hold warm

#1306 Rename `tsv` format to `compact` & `bdbag` to `terra.bdbag` (#1086)
  lambdas/service/app.py
  src/azul/service/responseobjects/elastic_request_builder.py
  src/azul/service/responseobjects/hca_response_v5.py
  test/local_integration_test.py
  test/service/test_manifest.py
Labels: sandbox
