Repository DataBiosphere/azul, pull requests merged in 2019-11, with the labels that each got.

#1393 Include species count in summary (#1388)
  src/azul/service/repository.py
  src/azul/service/responseobjects/elastic_request_builder.py
  src/azul/service/responseobjects/hca_response_v5.py
  test/service/test_response.py
Labels: sandbox

#1391 [R] Allow sorting on donor count (#1378)
  src/azul/project/hca/__init__.py
  src/azul/project/hca/transformers.py
  src/azul/service/responseobjects/hca_response_v5.py
  src/azul/transformer.py
  test/indexer/__init__.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/service/test_response.py
Labels: sandbox

#1369 Use DSS parameter store to determine bucket names (#1314)
  README.md
  lambdas/indexer/lambda-policy.json.template.py
  lambdas/service/lambda-policy.json.template.py
  src/azul/__init__.py
Labels: sandbox

#1392 Add check for mandatory integration parameters in validation (#1353)
  lambdas/service/app.py
  src/azul/strings.py
  test/service/test_request_validation.py
Labels: hold warm, sandbox

#1385 Clarify README section one based on build w/o credentials (#1384, #1370)
  README.md
  docs/azul-arch.png
Labels: hold warm

#1394 Handle blank entity_ids parameter differently than when parameter is missing (#1340)
  lambdas/service/app.py
  test/service/test_response.py
Labels: sandbox

#1437 Don't purge fail queues before reindex (#1422)
  scripts/reindex.py
  src/azul/__init__.py
Labels: sandbox

#1456 Add SCP495 to portals db (#1455)
  src/azul/project/hca/__init__.py
Labels: sandbox

#1431 Fix: OpenAPI UI renders incorrect server URL (#1262)
  lambdas/service/app.py
  src/azul/openapi.py
Labels: sandbox

#1466 Eliminate all imports of `lambdas.{service,indexer}.app` (#1461)
  lambdas/service/app.py
  test/service/test_cart_item_manager.py
  test/service/test_manifest.py
  test/service/test_query_shortener.py
Labels: sandbox

#1467 Limit AZUL_DEBUG=0 to `make test` on Gitlab and Travis (#1444, #1464)
  .gitlab-ci.yml
  .travis.yml
Labels: sandbox
