Repository DataBiosphere/azul, pull requests merged in 2019-05, with the labels that each got.

#935 Updated urllib3 to 1.24.2 (#927)
  requirements.txt
Labels: sandbox

#952 Refine Gitlab pipline
  .gitlab-ci.yml
Labels: sandbox

#948 Create bundles index (#903)
  lambdas/service/app.py
  src/azul/project/hca/indexer.py
  src/azul/project/hca/transformers.py
  src/azul/service/repository.py
  src/azul/service/responseobjects/elastic_request_builder.py
  src/azul/service/responseobjects/hca_response_v5.py
  src/azul/transformer.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/indexer/test_hca_indexer.py
  test/service/test_response.py
Labels: sandbox

#924 Add AnalysisProtocol.protocol_id to index (#896)
  src/azul/project/hca/transformers.py
  src/azul/service/responseobjects/hca_response_v5.py
  src/azul/service/service_config/request_config.json
  test/indexer/test_hca_indexer.py
  test/service/test_response.py
Labels: orange, sandbox

#959 Fix projectSummary.donorCount (#953)
  src/azul/service/responseobjects/hca_response_v5.py
  test/service/test_request_builder.py
  test/service/test_response.py
Labels: orange, sandbox

#962 Absorb addtion of paging to `GET /bundles/{uuid}` in DSS
  requirements.txt
Labels: sandbox

#973 Updated urllib3 to 1.24.3 (#970)
  requirements.txt
Labels: orange

#963 Ignore Retry-After from DSS for small file downloads (#686)
  lambdas/service/app.py
  test/service/test_dss_proxy.py
Labels: orange

#946 Add deletion to integration test (#838)
  src/azul/azulclient.py
  src/azul/indexer.py
  test/local_integration_test.py
Labels: orange, sandbox

#964 Replace bdbag config with manifest (#892)
  src/azul/service/responseobjects/elastic_request_builder.py
  src/azul/service/responseobjects/hca_response_v5.py
  src/azul/service/service_config/request_config.json
  test/local_integration_test.py
  test/service/test_request_validation.py
Labels: orange, sandbox

#992 Backport prod fix to develop
  requirements.txt
Labels: orange

#998 Back-merge exclusion from prod into develop
  src/azul/project/hca/__init__.py
Labels: orange

#987 Make indexing of organs more consistent (#977)
  src/azul/project/hca/transformers.py
  src/azul/service/responseobjects/elastic_request_builder.py
  src/azul/service/responseobjects/hca_response_v5.py
  src/azul/transformer.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/indexer/data/b7fc737e-9b7b-4800-8977-fe7c94e131df.metadata.json
  test/indexer/data/e0ae8cfa-2b51-4419-9cde-34df44c6458a.metadata.json
  test/indexer/test_hca_indexer.py
  test/service/test_request_builder.py
  test/service/test_response.py
Labels: orange, sandbox

#1003 Combine workflow and workflowVersion facets (#985)
  src/azul/project/hca/transformers.py
  src/azul/service/responseobjects/hca_response_v5.py
  src/azul/service/service_config/request_config.json
  test/indexer/test_hca_indexer.py
  test/service/test_response.py
Labels: orange, sandbox

#1007 organSummaries organ of None error (#1006)
  src/azul/service/responseobjects/hca_response_v5.py
Labels: orange, sandbox

#1004 Renamed temporary subfolder in BDbag to `manifest` (#991)
  src/azul/service/responseobjects/hca_response_v5.py
  test/service/test_request_validation.py
Labels: orange, sandbox

#1028 Return gs url with DRS endpoint (#920)
  lambdas/service/app.py
  test/service/test_drs.py
Labels: orange

#1041 Speed up indexing tests with `refresh=True`
  test/indexer/__init__.py
Labels: orange, sandbox

#1043 Ensure integration tests always cleanup bundles (#994)
  src/azul/azulclient.py
  test/local_integration_test.py
Labels: orange, sandbox

#1033 Add imaging-specific facets (#885)
  requirements.txt
  src/azul/project/hca/transformers.py
  src/azul/service/repository.py
  src/azul/service/responseobjects/elastic_request_builder.py
  src/azul/service/responseobjects/hca_response_v5.py
  src/azul/service/service_config/request_config.json
  src/azul/transformer.py
  test/indexer/test_hca_indexer.py
  test/service/test_request_builder.py
  test/service/test_response.py
Labels: orange, sandbox

#1042 Return gs url with DRS endpoint (#920)
  lambdas/service/app.py
  test/service/test_drs.py
Labels: hold warm, orange

#1048 Increase terms aggregation size limit (#1047)
  src/azul/__init__.py
  src/azul/service/responseobjects/elastic_request_builder.py
Labels: orange
