Repository DataBiosphere/azul, pull requests merged in 2019-06, with the labels that each got.

#1008 Add `metadata` field to documents in bundles index (#965, #965)
  src/azul/project/hca/metadata_generator.py
  src/azul/project/hca/transformers.py
  src/azul/transformer.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/indexer/test_hca_indexer.py
Labels: orange, sandbox

#1037 Added `/progress` endpoint in Indexer and `api_endpoints` to `/health` endpoint (#971)
  lambdas/indexer/app.py
  lambdas/service/app.py
  src/azul/health.py
  test/health_check_test_case.py
  test/local_integration_test.py
Labels: orange, sandbox

#1045 Excluding `metadata` field index mapping (#1020)
  src/azul/project/hca/indexer.py
  test/indexer/test_hca_indexer.py
Labels: orange, sandbox

#1056 Replaced `*` with `sample` from manifests (#1055)
  src/azul/service/service_config/request_config.json
  test/service/test_request_validation.py
Labels: orange, sandbox

#1058 Fix: `git secrets` check fails in sub directories (#1057)
  common.mk
Labels: orange, sandbox

#1059 Refactor HCA transformer
  src/azul/project/hca/transformers.py
Labels: orange, sandbox

#1062 Added check_branch dependencies in Makefile (#1061)
  Makefile
Labels: sandbox

#936 Add CONTRIBUTING document (#750)
  CONTRIBUTING.rst
Labels: orange

#1081 Use DistinctAccumulator in CellSuspensionAggregator (#1039)
  src/azul/project/hca/transformers.py
Labels: orange, sandbox

#1087 Fix: /health/progress is not lazy and therefore slow (#1084)
  lambdas/indexer/app.py
  lambdas/service/app.py
  src/azul/health.py
  test/health_check_test_case.py
Labels: orange

#1088 Parallelize API endpoint health checks (#1085)
  src/azul/health.py
Labels: orange, sandbox

#1092 Avoid dash and brackets in BDBag column names (#1091)
  src/azul/service/responseobjects/hca_response_v5.py
  test/service/test_request_validation.py
Labels: orange, sandbox
