Repository DataBiosphere/azul, pull requests merged in 2019-10, with the labels that each got.

#1322 Enable action OK when alarms transition from alarm states (#1233)
  terraform/cloudwatch.tf.json.template.py
Labels: sandbox

#1297 Cache health check response to reduce service load (#1224)
  lambdas/indexer/.chalice/config.json.template.py
  lambdas/indexer/app.py
  lambdas/indexer/lambda-policy.json.template.py
  lambdas/service/.chalice/config.json.template.py
  lambdas/service/app.py
  src/azul/__init__.py
  terraform/route53_health_check.tf.json.template.py
  test/health_check_test_case.py
Labels: sandbox

#1321 Measure Azul health checks latency (#1151)
  terraform/route53_health_check.tf.json.template.py
Labels: sandbox

#1323 Limit 'size' parameter to 1000 or less (#1257)
  lambdas/service/app.py
Labels: sandbox

#1339 Update SCEA portal details (#1337)
  src/azul/project/hca/__init__.py
Labels: hold warm

#1341 Format dumped json for apidev.py
  scripts/apidev.py
Labels: hold warm

#1343 [r] Include fields that allow CLI downloads for full manifest (#1273)
  src/azul/project/hca/metadata_generator.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/indexer/test_hca_indexer.py
  test/service/test_manifest.py
Labels: sandbox

#1349 Add script to generate release notes
  scripts/release.sh
Labels: hold warm

#1346 Add Xena portal integrations (#1345)
  src/azul/project/hca/__init__.py
  test/service/test_response.py
Labels: sandbox

#1331 Hotfix for staging, DSS bucket swap
  src/azul/__init__.py
Labels: hold warm, urgent

#1329 Add entity_ids param to integrations endpoint (#1318)
  lambdas/service/app.py
  test/service/test_response.py
Labels: sandbox

#1307 Improve deployment cleanup process (#1303)
  README.md
  lambdas/indexer/Makefile
  lambdas/service/Makefile
  scripts/manage_lambda_iam_role.py
Labels: sandbox

#1362 Remove SCP495 study entry from portals database (#1360)
  src/azul/project/hca/__init__.py
Labels: sandbox

#1381 Fully qualify dynamodb-local image reference (#1380)
  test/dynamo_test_case.py
Labels: sandbox

#1354 Remove health endpoint duplication in indexer & service lambdas (#1290)
  lambdas/indexer/app.py
  lambdas/indexer/lambda-policy.json.template.py
  lambdas/service/app.py
  src/azul/health.py
  test/health_check_test_case.py
Labels: sandbox
