Repository DataBiosphere/azul, pull requests merged in 2020-08, with the labels that each got.

#2042 Handle obsolete bundle versions in IntegrationTest (#2003)
  src/azul/azulclient.py
  test/integration_test.py
Labels: 4+ reviews, orange, sandbox

#2038 Contribution guide updates (#2028)
  CONTRIBUTING.rst
Labels: hold warm, orange

#2128 Add note on pseudo constants to contribution guide
  CONTRIBUTING.rst
Labels: 0 reviews, hold warm, orange

#2111 Fix: DSS adapter fails on prefixes starting with 0s (#2108)
  scripts/dss_v2_apdapter.py
Labels: 0 reviews, hold warm, orange

#2135 Document TDR and SAM service url env vars (#2134)
  UPGRADING.rst
  environment.py
Labels: 1 review, orange, urgent

#2106 Add biomaterial_id to full manifest (#2090)
  src/azul/plugins/metadata/hca/full_metadata.py
  src/azul/queues.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/service/test_manifest.py
Labels: 1 review, orange, reindex, sandbox

#2080 Split polymorphic 'protocols' inner entity (#2043)
  src/azul/project/hca/__init__.py
  src/azul/project/hca/transformers.py
  src/azul/queues.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/hca_response_v5.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/indexer/test_hca_indexer.py
  test/service/test_request_builder.py
  test/service/test_response.py
Labels: 3 reviews, HCA, reindex, sandbox

#2140 Use dev SAM instance (#2120)
  deployments/.example.local/environment.py
  deployments/dev/environment.py
  deployments/sandbox/environment.py
Labels: 1 review, orange, sandbox, urgent

#2124 Eliminate redundant `__` in field names for filter queries
  src/azul/service/elasticsearch_service.py
Labels: orange, sandbox

#2127 Generalize index field translation (#1747)
  src/azul/indexer/document.py
  src/azul/plugins/metadata/hca/transform.py
  src/azul/service/elasticsearch_service.py
  test/indexer/test_hca_indexer.py
  test/service/test_response.py
Labels: orange, sandbox

#2102 Cache indexer service account credentials (#2056)
  src/azul/dss.py
Labels: 3 reviews, orange, sandbox

#2145 Remove front matter from PR template (#2129)
  .github/pull_request_template.md
Labels: orange

#2098 Switch to snapshot `dcp1_metadata_no_files` (#2097, #2023)
  deployments/.example.local/environment.py
  deployments/dev/environment.py
  deployments/sandbox/environment.py
  src/azul/tdr.py
  test/integration_test.py
Labels: orange, sandbox

#2118 Add 'sequencing_input' in 'terra.bdbag' manifests (#2113)
  src/azul/project/hca/__init__.py
  src/azul/project/hca/transformers.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/service/test_manifest.py
Labels: 1 review, HCA, reindex, sandbox

#2160 Fix: Retries of `contribute` lambda invocations may drop tallies (#2159)
  src/azul/indexer/index_service.py
  test/indexer/test_hca_indexer.py
Labels: orange, reindex, sandbox

#2015 Change DRS URLs to Broad resolver (#1850)
  UPGRADING.rst
  deployments/dev/environment.py
  deployments/sandbox/environment.py
  environment.py
  requirements.dev.trans.txt
  requirements.trans.txt
  requirements.txt
  src/azul/__init__.py
  src/azul/azulclient.py
  src/azul/bigquery.py
  src/azul/indexer/__init__.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/hca/transform.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/service/manifest_service.py
  src/azul/tdr.py
  test/azul_test_case.py
  test/indexer/__init__.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/indexer/test_hca_indexer.py
  test/service/test_tdr.py
Labels: 1 review, orange, reindex, sandbox

#2067 Remove `:` from versions in BDBag manifest (#2064)
  src/azul/service/manifest_service.py
  test/integration_test.py
Labels: 1 review, orange, sandbox

#2173 Separate ES domain for sandbox and personal deployments (#2171)
  UPGRADING.rst
  deployments/.example.local/environment.py
  deployments/sandbox/environment.py
Labels: orange

#2177 Use latest TDR snapshot; force version uniqueness again (#2149, #2146)
  UPGRADING.rst
  deployments/.example.local/environment.py
  deployments/dev/environment.py
  deployments/sandbox/environment.py
  src/azul/plugins/repository/tdr/__init__.py
Labels: orange, reindex, sandbox

#2212 [r] Add 'sequencing_input' to terra and compact manifests (#2211)
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/transform.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/service/test_manifest.py
Labels: orange, reindex, sandbox
