Repository DataBiosphere/azul, pull requests merged in 2020-04, with the labels that each got.

#1538 Document /health endpoints (#1400)
  lambdas/indexer/app.py
  lambdas/service/app.py
  src/azul/health.py
  test/health_check_test_case.py
Labels: 3 reviews, orange, sandbox

#1658 Log token queue length in queue waiter (#1617)
  scripts/reindex.py
  src/azul/queues.py
  test/integration_test.py
Labels: 2 reviews, orange, sandbox

#1639 Refactor handling of environment for easier reuse (#1637)
  .gitignore
  README.md
  UPGRADING.rst
  attic/deployments/.example.local/environment
  attic/deployments/dev.gitlab/environment
  attic/deployments/dev/environment
  attic/deployments/sandbox/environment
  attic/environment
  deployments/.example.local/environment.local.py
  deployments/.example.local/environment.py
  deployments/dev.gitlab/environment.py
  deployments/dev/environment.py
  deployments/sandbox/environment.py
  environment
  environment.py
  scripts/convert_environment.py
  scripts/envhook.py
  scripts/export_environment.py
  src/azul/__init__.py
Labels: orange, sandbox

#1648 Cache `terra.bdbag` and `compact` manifest formats
  lambdas/service/app.py
  src/azul/__init__.py
  src/azul/service/manifest_service.py
  test/service/test_manifest.py
Labels: 4+ reviews, chain, orange, sandbox

#1635 Use Terraform for deploying lambdas (#556)
  .gitlab-ci.yml
  Dockerfile
  README.md
  UPGRADING.rst
  lambdas/Makefile
  lambdas/indexer/.chalice/config.json.template.py
  lambdas/indexer/.gitignore
  lambdas/indexer/Makefile
  lambdas/service/.gitignore
  lambdas/service/Makefile
  scripts/manage_chalice_deployed.py
  scripts/manage_lambda_iam_role.py
  scripts/prepare_lambda_deployment.py
  src/azul/deployment.py
  src/azul/indexer/__init__.py
  src/azul/indexer/policy.py
  src/azul/service/policy.py
  terraform/.gitignore
  terraform/api_gateway.tf.json.template.py
  terraform/common.tf.json.template.py
  terraform/gitlab/gitlab.tf.json.template.py
  terraform/modules.tf.json.template.py
Labels: 4+ reviews, chain, orange, sandbox, urgent

#1681 Fix typo in UPGRADING.rst
  UPGRADING.rst
Labels: orange

#1683 Fix typo in heading
  UPGRADING.rst
Labels: orange

#1660 Validate filters for manifest requests (#1582)
  lambdas/service/app.py
  test/service/test_manifest.py
Labels: 3 reviews, orange, sandbox

#1676 Fix typo in CI/CD section of README
  README.md
Labels: orange

#1669 Remove redundant bundles from Terra export (#916)
  src/azul/service/manifest_service.py
  test/indexer/data/cfab8304-dc9f-439e-af29-f8eb75b0729d.manifest.json
  test/indexer/data/cfab8304-dc9f-439e-af29-f8eb75b0729d.metadata.json
  test/indexer/data/f0731ab4-6b80-4eed-97c9-4984de81a47c.manifest.json
  test/indexer/data/f0731ab4-6b80-4eed-97c9-4984de81a47c.metadata.json
  test/service/test_manifest.py
Labels: 0 reviews, orange, sandbox

#1689 Fix TypeError sorting None on reindex (#1678)
  src/azul/project/hca/transformers.py
  test/indexer/data/1b6d8348-d6e9-406a-aa6a-7ee886e52bf9.manifest.json
  test/indexer/data/1b6d8348-d6e9-406a-aa6a-7ee886e52bf9.metadata.json
  test/indexer/test_hca_indexer.py
Labels: orange, sandbox

#1682 Reduce noisy indexer aggregation logs (#1670)
  src/azul/indexer/__init__.py
Labels: 1 review, orange, sandbox

#1684 Generalize permissions boundary account id (#1561)
  environment.py
  src/azul/__init__.py
  src/azul/indexer/policy.py
  src/azul/service/policy.py
  terraform/api_gateway.tf.json.template.py
  terraform/gitlab/gitlab.tf.json.template.py
Labels: 1 review, orange, sandbox

#1691 Fix: Manifest content hash is computed even when 'token' is provided
  lambdas/service/app.py
Labels: 1 review, orange, sandbox

#1707 Change ElasticSearch snapshot time (#1703)
  terraform/elasticsearch.tf.json.template.py
Labels: orange

#1692 Stop omitting project response fields (#1666)
  src/azul/service/repository_service.py
  test/service/test_repository_projects.py
Labels: 0 reviews, orange, sandbox

#1714 Segregate Cloudwatch resources by deployment (#1713)
  scripts/prepare_lambda_deployment.py
Labels: sandbox, urgent

#1668 Store openapi spec in chalice object (#1485)
  lambdas/service/app.py
  scripts/apidev.py
  src/azul/chalice.py
  src/azul/openapi/__init__.py
  test/test_openapi.py
Labels: 4+ reviews, chain, orange, sandbox

#1650 Avoid generating manifest content hash more than once
  lambdas/service/app.py
  src/azul/service/async_manifest_service.py
  src/azul/service/manifest_service.py
  test/service/test_async_manifest_service.py
  test/service/test_manifest.py
Labels: 3 reviews, orange, sandbox

#1709 Allow detached head for personal deployments in make check_branch
  scripts/check_branch.py
Labels: 1 review, orange, sandbox

#1721 Remove role assumptors for dev.sc & sandbox deployments (#1712)
  deployments/dev/environment.py
  deployments/sandbox/environment.py
Labels: orange, sandbox

#1729 Switch all deployments to DSS prod (#1577)
  UPGRADING.rst
  deployments/.example.local/environment.py
  deployments/dev/environment.py
  deployments/sandbox/environment.py
  src/azul/__init__.py
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, sandbox

#1655 Use Lambda layers to speed up `make deploy` (#1272)
  UPGRADING.rst
  lambdas/Makefile
  lambdas/layer/.chalice/config.json.template.py
  lambdas/layer/.gitignore
  lambdas/layer/Makefile
  lambdas/layer/app.py
  lambdas/layer/requirements.txt
  lambdas/service/requirements.txt
  scripts/prepare_lambda_deployment.py
  scripts/stage_layer.py
  src/azul/__init__.py
  src/azul/files.py
  src/azul/lambda_layer.py
  terraform/Makefile
  terraform/lambda_layer.tf.json.template.py
  terraform/modules.tf.json.template.py
  test/test_doctests.py
Labels: 4+ reviews, orange, sandbox

#1667 Remove SQS Token Queue (#1653)
  lambdas/indexer/app.py
  src/azul/__init__.py
  src/azul/indexer/policy.py
  src/azul/queues.py
  terraform/sqs.tf.json.template.py
Labels: 2 reviews, orange, sandbox

#1699 Fix: `make deploy` requires ES resources to be provisioned (#1688)
  README.md
  src/azul/__init__.py
  src/azul/deployment.py
Labels: 2 reviews, chain, orange, sandbox

#1705 Redesign template config variable mechanism (#1645)
  UPGRADING.rst
  deployments/.example.local/environment.py
  deployments/dev/environment.py
  deployments/sandbox/environment.py
  environment.py
  scripts/export_environment.py
  src/azul/__init__.py
Labels: 3 reviews, orange, sandbox

#1708 Add general API documentation (#1409)
  lambdas/service/app.py
Labels: 2 reviews, orange, sandbox
