Repository DataBiosphere/azul, pull requests merged in 2020-09, with the labels that each got.

#2218 Update TDR source in DCP2 EBI catalog (#2213)
  deployments/dev/environment.py
  deployments/sandbox/environment.py
Labels: 1 review, orange, reindex, sandbox

#2144 Split polymorphic 'protocols' inner entity (#2082)
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/transform.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/hca_response_v5.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/indexer/test_hca_indexer.py
  test/service/test_request_builder.py
  test/service/test_response.py
Labels: 0 reviews, orange, reindex, sandbox

#2027 Add script for calculating velocity (#1807)
  .github/workflows/velocity.yml
  environment.py
  scripts/velocity.py
  test/test_doctests.py
Labels: 1 review, orange

#2165 Add DSS Adapter argument to copy only analysis bundles (#2162)
  scripts/dss_v2_apdapter.py
Labels: 0 reviews, orange

#2193 Add tests against dropped tallies when contribute lambda is retried (#2163)
  test/indexer/test_hca_indexer.py
Labels: 0 reviews, HCA, sandbox

#2216 Fix misnamed `make requirements_update` in contribution guide
  .github/pull_request_template.md
Labels: orange

#2094 Clean up Terraform resource names (#2033)
  .gitlab-ci.yml
  scripts/reindex.py
  scripts/rename_resources.py
  src/azul/queues.py
  terraform/Makefile
  terraform/authentication.tf.json.template.py
  terraform/dynamo.tf.json.template.py
  terraform/elasticsearch.tf.json.template.py
  terraform/modules.tf.json.template.py
  terraform/s3.tf.json.template.py
  terraform/step_function.tf.json.template.py
  test/integration_test.py
Labels: 4+ reviews, chain, orange, sandbox

#2141 Document workaround for `make deploy` failure due to manually deleted ES instance (#1998)
  README.md
Labels: 2 reviews, orange

#2205 Raise exception class where appropriate for brevity (#2040)
  CONTRIBUTING.rst
  scripts/envhook.py
  src/azul/azulclient.py
  src/azul/indexer/__init__.py
  src/azul/indexer/document.py
  src/azul/indexer/transform.py
  src/azul/json_freeze.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/hca/full_metadata.py
  src/azul/plugins/metadata/hca/transform.py
  src/azul/service/cart_export_service.py
  src/azul/service/hca_response_v5.py
  src/azul/service/manifest_service.py
  src/azul/threads.py
  src/azul/time.py
  test/app_test_case.py
  test/azul_test_case.py
  test/health_check_test_case.py
Labels: 0 reviews, orange, sandbox

#2220 Add cached_property to _es_domain_status (#2194)
  src/azul/deployment.py
Labels: 0 reviews, orange, sandbox

#2206 Add sort mode property to 'FieldType' class (#2176)
  src/azul/indexer/document.py
  src/azul/plugins/metadata/hca/transform.py
  src/azul/service/elasticsearch_service.py
  test/indexer/data/8c90d4fe-9a5d-4e3d-ada2-0414b666b880.manifest.json
  test/indexer/data/8c90d4fe-9a5d-4e3d-ada2-0414b666b880.metadata.json
  test/indexer/data/97f0cc83-f0ac-417a-8a29-221c77debde8.manifest.json
  test/indexer/data/97f0cc83-f0ac-417a-8a29-221c77debde8.metadata.json
  test/service/test_response.py
Labels: 2 reviews, orange, sandbox

#2215 Use Docker API bindings in kibana_proxy.py (#1891)
  README.md
  attic/scripts/count-bundles.py
  attic/scripts/upload-tsv-files.py
  scripts/can_bundle.py
  scripts/kibana-proxy.py
  scripts/kibana_proxy.py
Labels: 0 reviews, orange, sandbox

#2238 Fix metadata errors in DCP2EBI catalog (#2237)
  deployments/dev/environment.py
  deployments/sandbox/environment.py
Labels: orange, reindex, sandbox

#2119 Return empty 200 service response for unpopulated ES indices (#1995)
  src/azul/es.py
  src/azul/service/elasticsearch_service.py
  test/service/test_response.py
Labels: 4+ reviews, orange, sandbox

#2208 Fix invalid punctuation in BDBag column names (#2182)
  src/azul/service/manifest_service.py
Labels: 0 reviews, orange, sandbox

#2121 Add testing for index_controller (#1589)
  src/azul/queues.py
  test/indexer/test_indexer_controller.py
Labels: 4+ reviews, orange, sandbox

#2224 Order missing fields first in a desc sort (#2174)
  src/azul/service/elasticsearch_service.py
  test/service/test_response.py
Labels: 1 review, orange, sandbox

#2235 Upload velocity report to Gitlab wiki (#2229)
  .github/workflows/velocity.yml
Labels: 1 review, orange

#2236 Fix BigQuery verification during deployment (#2025)
  README.md
  UPGRADING.rst
  deployments/.example.local/environment.py
  scripts/register_sam.py
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/tdr.py
Labels: 4+ reviews, orange, sandbox

#2217 Upgrade PyJWT to v1.7.1 (#2069)
  UPGRADING.rst
  requirements.dev.trans.txt
  requirements.trans.txt
  requirements.txt
  test/azul_test_case.py
Labels: 2 reviews, orange, sandbox

#2196 Handle DRS URIs when indexing TDR datasets (#2114)
  src/azul/indexer/__init__.py
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/service/manifest_service.py
  test/service/test_tdr.py
Labels: 1 review, orange, sandbox

#2187 Locust script is stale (#2154)
  README.md
  requirements.dev.txt
  scripts/locust/service.py
Labels: 4+ reviews, HCA, sandbox

#2234 Manifest endpoint spec lists filterable facets in description (#2044)
  lambdas/service/app.py
Labels: 1 review, orange, sandbox

#2253 Update DCP2 catalog to `hca_ucsc_files___20200909` snapshot (#2247)
  UPGRADING.rst
  deployments/.example.local/environment.py
  deployments/dev/environment.py
  deployments/sandbox/environment.py
Labels: chain, orange, reindex, sandbox

#2157 Generalize DRS client (#2150)
  src/azul/drs.py
  test/integration_test.py
Labels: 3 reviews, chain, orange, sandbox

#2219 Add DRS URLs to compact manifest (#2180)
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/service/manifest_service.py
  test/service/test_manifest.py
Labels: 3 reviews, orange, sandbox

#2168 Add constraints to catalog query parameter (#2158)
  lambdas/service/app.py
  test/service/test_request_validation.py
Labels: 4+ reviews, chain, orange, sandbox

#2263 `make requirements_update` removes transient pins injectively (#2261)
  Makefile
  UPGRADING.rst
  requirements.dev.trans.txt
  requirements.trans.txt
Labels: orange, sandbox

#2227 Add runbook for remotely debugging lambdas (#2207)
  README.md
  src/azul/remote_debug.py
Labels: 1 review, orange

#2256 Update DCP2EBI catalogs (#2252, #2255)
  deployments/dev/environment.py
  deployments/sandbox/environment.py
Labels: orange, reindex, sandbox

#2276 Fix: `make requirements_update` fails in `sed` on macOS (#2269)
  Makefile
  UPGRADING.rst
  requirements.dev.trans.txt
Labels: orange, sandbox

#2245 Filter by cellCount to consider summed value (#1862)
  src/azul/indexer/aggregate.py
  src/azul/indexer/index_service.py
  src/azul/indexer/transform.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/transform.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/service/test_response.py
Labels: 2 reviews, orange, reindex, sandbox

#2272 Log entity ids before querying in TDR plugin (#2265)
  src/azul/plugins/repository/tdr/__init__.py
Labels: 1 review, orange, sandbox

#2260 Fix: README uses old name for renamed TF resource (#2239)
  README.md
Labels: 0 reviews, no demo, orange

#2264 Document velocity report script configuration (#2249)
  scripts/velocity.py
Labels: 2 reviews, orange

#2297 Fix: Incorrect fileTypeSummary with `null` file size (#2285)
  src/azul/service/elasticsearch_service.py
Labels: orange, sandbox

#2299 Upload `coverage` output in a separate job stage on Travis (#2283)
  .travis.yml
Labels: orange

#2304 Introduce DRS controller (#2305)
  lambdas/service/app.py
  src/azul/drs.py
  src/azul/service/drs_controller.py
  src/azul/service/repository_service.py
  test/azul_test_case.py
  test/integration_test.py
  test/service/test_drs.py
  test/test_doctests.py
Labels: chain, orange, sandbox

#2312 Fix: codecov picks up coverage data from `develop` builds (#2283)
  .travis.yml
Labels: orange

#2314 Fix `make requirements_update` assertion failure (#2313)
  .travis.yml
  UPGRADING.rst
  requirements.dev.trans.txt
  requirements.dev.txt
  requirements.trans.txt
  requirements.txt
  scripts/manage_requirements.py
Labels: orange, sandbox
