Repository DataBiosphere/azul, pull requests merged in 2020-12, with the labels that each got.

#2556 Index hca_dev_20201023_ebiv4___20201121 into dcp2ebi on dev (#2541)
  deployments/dev/environment.py
  deployments/sandbox/environment.py
Labels: orange, reindex, sandbox

#2572 [r] Index hca_prod_20201118_dcp1___20201202 into dcp1 on prod (#2569)
  deployments/prod/environment.py
Labels: orange, reindex

#2573 Index hca_dev_20200819___20201202 into dcp2 on dev (#2570)
  deployments/.example.local/environment.py
  deployments/dev/environment.py
  deployments/sandbox/environment.py
Labels: orange, reindex

#2543 Correctly identify dangling supplementary files (#2540)
  src/azul/plugins/repository/tdr/__init__.py
Labels: 2 reviews, orange, reindex, sandbox

#2577 Fix: Occasional KeyError on `/index/summary` endpoint (#2461)
  lambdas/service/app.py
  scripts/cgm_adapter.py
  scripts/dss_v2_apdapter.py
  scripts/kibana_proxy.py
  scripts/log_api_gateway.py
  scripts/manage_health_checks.py
  scripts/provision_credentials.py
  scripts/scrape_aws_service_model.py
  scripts/velocity.py
  src/azul/__init__.py
  src/azul/azulclient.py
  src/azul/deployment.py
  src/azul/es.py
  src/azul/health.py
  src/azul/indexer/document_service.py
  src/azul/indexer/index_controller.py
  src/azul/lambda_layer.py
  src/azul/lambdas.py
  src/azul/objects.py
  src/azul/portal_service.py
  src/azul/queues.py
  src/azul/service/repository_controller.py
  src/azul/service/storage_service.py
  src/azul/terra.py
  src/azul/version_service.py
  terraform/gitlab/gitlab.tf.json.template.py
  test/azul_test_case.py
  test/health_check_test_case.py
  test/indexer/test_hca_indexer.py
  test/indexer/test_indexer_controller.py
  test/integration_test.py
  test/retorts.py
  test/service/test_dss_proxy.py
  test/service/test_portal_service.py
  test/service/test_query_shortener.py
  test/service/test_tdr.py
  test/version_table_test_case.py
Labels: orange, sandbox

#2601 Index hca_dev_20201203___20201207 into dcp2 on dev (#2596)
  deployments/.example.local/environment.py
  deployments/dev/environment.py
  deployments/sandbox/environment.py
Labels: reindex, sandbox

#2377 Fix and simplify manual SAM registration command in README
  README.md
Labels: no demo, no sandbox, orange

#2608 Fix full manifests for contributor generated matrices (#2440)
  README.md
  scripts/can_dss_bundle.py
  scripts/can_tdr_bundle.py
  src/azul/indexer/document.py
  src/azul/service/manifest_service.py
  test/indexer/data/4f2fc365-9f97-51ca-bbfe-fe30cefc333d.manifest.json
  test/indexer/data/4f2fc365-9f97-51ca-bbfe-fe30cefc333d.metadata.json
  test/indexer/test_hca_indexer.py
  test/service/test_manifest.py
Labels: 0 reviews, orange, reindex, sandbox

#2448 Use stratification terminology in CGM Adapter (#2417)
  scripts/cgm_adapter.py
Labels: chain, no sandbox, orange

#2485 Replace CGM stratification names with HCA terms (#2466)
  scripts/cgm_adapter.py
Labels: 0 reviews, chain, no sandbox, orange

#2550 Check for duplicate file names in CGM Adapter (#2421)
  scripts/cgm_adapter.py
Labels: 0 reviews, orange

#2493 Add script to test manifest 404 (#2456)
  scripts/manifest_404.py
Labels: no sandbox, orange

#2589 Reject null file_id in snapshots (#2579)
  src/azul/plugins/repository/tdr/__init__.py
Labels: 0 reviews, orange, sandbox

#2590 Allow Gitlab to deploy DataBrowser/DataPortal to `prod` (HumanCellAtlas/data-browser#1393)
  terraform/gitlab/gitlab.tf.json.template.py
Labels: no demo, no sandbox, orange

#2619 Index hca_dev_20201203___20201210 into dcp2 on dev (#2618)
  deployments/.example.local/environment.py
  deployments/dev/environment.py
  deployments/sandbox/environment.py
Labels: orange, reindex, sandbox

#2554 Perform secondary sort of stratification tree dimensions (#2546)
  src/azul/plugins/metadata/hca/contributor_matrices.py
  test/indexer/data/1ec111a0-7481-571f-b35a-5a0e8fca890a.metadata.json
  test/indexer/data/4f2fc365-9f97-51ca-bbfe-fe30cefc333d.metadata.json
  test/indexer/test_hca_indexer.py
  test/service/test_response.py
Labels: 1 review, orange, sandbox

#2473 Fix: Full manifest fails to generate for large data requests (#2452)
  src/azul/service/manifest_service.py
  src/azul/strings.py
  test/service/test_manifest.py
Labels: 1 review, orange, sandbox

#2474 Improve subgraph stitching (#2413)
  src/azul/plugins/repository/tdr/__init__.py
  test/service/test_tdr.py
Labels: 0 reviews, orange, sandbox

#2492 Fix: Queue waiter does not honor eventual consistency wait time (#2178)
  src/azul/queues.py
Labels: 1 review, orange, sandbox

#2645 Index hca_dev_20201217_test4___20201218 into dcp2 on dev (#2644)
  deployments/.example.local/environment.py
  deployments/dev/environment.py
  deployments/sandbox/environment.py
  scripts/reindex.py
  src/azul/azulclient.py
  src/azul/indexer/index_controller.py
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/queues.py
  test/indexer/test_indexer_controller.py
  test/integration_test.py
Labels: orange, reindex, sandbox

#2566 Upload velocity reports to GitHub repository instead of GitLab wiki (#2458)
  .github/workflows/velocity.yml
  README.md
  scripts/velocity.py
Labels: no sandbox, orange

#2636 Make indexer tests insensitive to AZUL_INDEXER_CONCURRENCY (#2107)
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/indexer/test_hca_indexer.py
Labels: 0 reviews, orange, sandbox

#2648 Disable DRS endpoints unless DSS plugin is active (#2588)
  lambdas/service/app.py
Labels: orange

#2612 Retire `/dss/files` and `/fetch/dss/files` (#2311)
  lambdas/service/app.py
  test/service/test_drs.py
  test/service/test_repository_proxy.py
  test/service/test_response.py
Labels: 0 reviews, orange, sandbox

#2599 Skipping tests if AZUL_DSS_ENDPOINT is not defined (#2496)
  src/azul/__init__.py
  src/azul/indexer/lambda_iam_policy.py
  src/azul/service/lambda_iam_policy.py
  test/integration_test.py
  test/service/__init__.py
  test/service/test_cart_export_service.py
  test/service/test_collection_data_access.py
  test/service/test_drs.py
  test/service/test_manifest.py
  test/service/test_portal_service.py
  test/service/test_repository_proxy.py
Labels: 2 reviews, orange, sandbox

#2656 Hotfix: Compact manifest fails for PDF files (#2649)
  src/azul/service/manifest_service.py
Labels: no sandbox, orange

#2564 Add fileSource facet (#2491)
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/aggregate.py
  src/azul/plugins/metadata/hca/transform.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/service/test_response.py
Labels: 1 review, chain, orange, reindex, sandbox

#2659 Disable DSS plugin in all deployments (#2658)
  UPGRADING.rst
  deployments/.example.local/environment.py
  deployments/dev/environment.py
  deployments/prod/environment.py
  deployments/sandbox/environment.py
  environment.py
  test/service/__init__.py
Labels: orange, reindex, sandbox

#2662 Move lower deployments to `platform-hca-dev` (#2494)
  Makefile
  README.md
  UPGRADING.rst
  deployments/.example.local/environment.py
  deployments/dev/environment.py
  deployments/sandbox/environment.py
  requirements.dev.trans.txt
  requirements.trans.txt
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, reqs, upgrade

#2663 Fix: Example deployment is stale (#2445)
  .gitignore
  README.md
  UPGRADING.rst
  deployments/.example.local/environment.local
  deployments/.example.local/environment.local.py
  deployments/.example.local/environment.py
  deployments/dev.gitlab/environment.py
  deployments/dev/.example.environment.local.py
  deployments/dev/environment.py
  deployments/prod/.example.environment.local.py
  deployments/prod/environment.py
  deployments/sandbox/.example.environment.local.py
  deployments/sandbox/environment.py
  environment
  environment.py
  scripts/convert_environment.py
Labels: orange, sandbox, upgrade

#2657 Backport: Hotfix: Compact manifest fails for PDF files (#2649)
  src/azul/service/manifest_service.py
Labels: orange, partial, port, sandbox
