Repository DataBiosphere/azul, pull requests merged in 2020-07, with the labels that each got.

#1889 Include ability to return a gs:// URL from DRS endpoint (#1772)
  README.md
  lambdas/service/app.py
  requirements.dev.trans.txt
  requirements.dev.txt
  src/azul/drs.py
  src/azul/openapi/__init__.py
  test/azul_test_case.py
  test/integration_test.py
  test/service/test_drs.py
Labels: 4+ reviews, orange, sandbox, urgent

#1983 Backport: TypeError sorting None on reindex (#1678, #1982)
  src/azul/project/hca/transformers.py
  test/indexer/data/1b6d8348-d6e9-406a-aa6a-7ee886e52bf9.manifest.json
  test/indexer/data/1b6d8348-d6e9-406a-aa6a-7ee886e52bf9.metadata.json
  test/indexer/test_hca_indexer.py
Labels: 1 review, HCA, sandbox

#1976 Implement catalogs, groups of indexes (#1929)
  README.md
  environment.py
  lambdas/indexer/app.py
  lambdas/service/app.py
  requirements.dev.trans.txt
  requirements.txt
  scripts/delete_bundle.py
  scripts/export_environment.py
  scripts/reindex.py
  src/azul/__init__.py
  src/azul/azulclient.py
  src/azul/drs.py
  src/azul/indexer/document.py
  src/azul/indexer/document_service.py
  src/azul/indexer/index_controller.py
  src/azul/indexer/index_service.py
  src/azul/openapi/schema.py
  src/azul/plugins/metadata/hca/transform.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/queues.py
  src/azul/service/async_manifest_service.py
  src/azul/service/cart_item_manager.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/manifest_service.py
  src/azul/service/repository_service.py
  src/azul/subscription.py
  test/azul_test_case.py
  test/indexer/__init__.py
  test/indexer/test_hca_indexer.py
  test/indexer/test_projects.py
  test/integration_test.py
  test/service/__init__.py
  test/service/test_async_manifest_service.py
  test/service/test_cart_item_manager.py
  test/service/test_drs.py
  test/service/test_manifest.py
  test/service/test_pagination.py
  test/service/test_repository_projects.py
  test/service/test_repository_specimen.py
  test/service/test_request_builder.py
  test/service/test_request_validation.py
  test/service/test_response.py
Labels: orange, sandbox

#1969 Incorrect crc32c for zarr files in manifests (#1948)
  src/azul/plugins/metadata/hca/transform.py
  test/service/test_manifest.py
Labels: orange, sandbox

#1857 Implement list_bundles for TDR plugin (#1762)
  deployments/dev/environment.py
  deployments/sandbox/environment.py
  environment.py
  lambdas/service/app.py
  requirements.dev.trans.txt
  requirements.dev.txt
  requirements.trans.txt
  requirements.txt
  src/azul/__init__.py
  src/azul/azulclient.py
  src/azul/bigquery.py
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/service/repository_service.py
  src/azul/tdr.py
  src/azul/uuids.py
  test/service/test_tdr.py
  test/test_doctests.py
Labels: 4+ reviews, chain, orange, sandbox

#1883 Implement fetch_bundle for TDR plugin (#1844)
  src/azul/bigquery.py
  src/azul/indexer/__init__.py
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/tdr.py
  test/service/test_tdr.py
Labels: 1 review, chain, orange, sandbox

#1924 Fix: Inconsistencies among config.json.template.py (#1911, #1775)
  lambdas/indexer/.chalice/config.json.template.py
  lambdas/service/.chalice/config.json.template.py
Labels: 2 reviews, orange, sandbox

#1928 Add minimum / maximum to openapi size spec (#1927)
  lambdas/service/app.py
  src/azul/openapi/schema.py
Labels: 1 review, orange, sandbox

#1947 Fix typo in service.app.py (#1946)
  lambdas/service/app.py
Labels: 0 reviews, orange, sandbox

#1973 Test unexpected warnings with AlwaysTearDownTestCase (#1981)
  test/test_app_logging.py
Labels: 1 review, hold warm, orange

#1974 Use qualified_resource_name for object version table name (#1944)
  src/azul/__init__.py
Labels: 1 review, orange, sandbox

#1999 Compare with _resource_prefix in unqualified_resource_name (#1936)
  src/azul/__init__.py
Labels: 0 reviews, orange, sandbox

#1996 Move `scripts/count-bundles.py` to `attic` (#1912)
  attic/count-bundles.py
Labels: 0 reviews, orange

#1837 Create DSS adapter script (#1753)
  requirements.dev.txt
  requirements.trans.txt
  scripts/dss_v2_apdapter.py
Labels: 3 reviews, chain, orange, sandbox

#2006 DSS adapter get schema type from describedBy (#1831)
  scripts/dss_v2_apdapter.py
Labels: chain, orange, sandbox

#1945 Reuse `filters` parameter spec for manifest endpoints (#1940)
  lambdas/service/app.py
Labels: 0 reviews, orange, sandbox

#1978 Add `version` parameter to spec of /dss endpoints (#1977)
  lambdas/service/app.py
  src/azul/service/repository_service.py
Labels: 3 reviews, orange, sandbox

#2012 Always provision indexer service account (#2011)
  README.md
  UPGRADING.rst
  deployments/.example.local/environment.local.py
  environment.py
  terraform/authentication.tf.json.template.py
Labels: sandbox

#1896 Handle supplementary file links in TDR plugin bundle emulation
  requirements.txt
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/tdr.py
  test/service/test_tdr.py
Labels: 0 reviews, orange

#2024 Make integration_test work with TDR plugin (#1972)
  deployments/dev/environment.py
  deployments/sandbox/environment.py
  src/azul/azulclient.py
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/tdr.py
  test/integration_test.py
Labels: orange, sandbox

#1950 Optionally skip secondary bundles in DSS adapter for v2 (#1932)
  scripts/dss_v2_apdapter.py
Labels: 2 reviews, orange, sandbox

#1988 Add `token` spec to `/dss` endpoints (#1985)
  lambdas/service/app.py
Labels: 1 review, orange, sandbox

#2020 Print missing bundles in `IndexingIntegrationTest` (#2002)
  test/integration_test.py
Labels: 0 reviews, orange, sandbox

#2001 Add `catalog` parameter to spec to `/index/summary` endpoints (#2000)
  lambdas/service/app.py
Labels: 1 review, orange, sandbox

#2019 Match schema_version to describedBy version in links.json (#2017)
  scripts/dss_v2_apdapter.py
Labels: 1 review, orange, sandbox

#2037 Clean up uuids.py (#2036)
  src/azul/azulclient.py
  src/azul/exceptions.py
  src/azul/uuids.py
  test/test_doctests.py
Labels: orange, sandbox

#2026 Many DSS adapter exceptions should be RequirementError (#2007)
  scripts/dss_v2_apdapter.py
Labels: 1 review, orange, sandbox

#2057 Maintain catalogs for DCP/1 and DCP/2 simultaneously (#2022)
  deployments/dev/environment.py
  deployments/sandbox/environment.py
  environment
  environment.py
  lambdas/indexer/app.py
  lambdas/service/app.py
  requirements.dev.trans.txt
  requirements.trans.txt
  requirements.txt
  scripts/delete_bundle.py
  scripts/dss_v2_apdapter.py
  scripts/manage_requirements.py
  scripts/reindex.py
  scripts/subscribe.py
  src/azul/__init__.py
  src/azul/azulclient.py
  src/azul/bigquery.py
  src/azul/deployment.py
  src/azul/exceptions.py
  src/azul/health.py
  src/azul/indexer/document.py
  src/azul/indexer/document_service.py
  src/azul/indexer/index_controller.py
  src/azul/indexer/index_service.py
  src/azul/lambda_layer.py
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/portal_service.py
  src/azul/queues.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/manifest_service.py
  src/azul/service/storage_service.py
  src/azul/subscription.py
  src/azul/tdr.py
  test/azul_test_case.py
  test/indexer/__init__.py
  test/indexer/test_hca_indexer.py
  test/indexer/test_projects.py
  test/integration_test.py
  test/service/test_portal_service.py
  test/service/test_request_validation.py
  test/service/test_response.py
  test/service/test_tdr.py
Labels: orange

#2046 Fix test indexing bundles using same FQID (#1802)
  test/indexer/test_hca_indexer.py
Labels: orange, sandbox

#2039 Prevent failure due to `write` AWS lambda memory exhaustion (#2013)
  lambdas/indexer/.chalice/config.json.template.py
Labels: 1 review, HCA, sandbox

#2079 Add cell_suspension.biomaterial_id to terra.bdbag (#2051)
  src/azul/project/hca/__init__.py
  src/azul/project/hca/transformers.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/service/test_manifest.py
Labels: 0 reviews, HCA, sandbox

#2084 Fix: frequent unassigned shards in `dev` ES domain (#2083)
  src/azul/azulclient.py
  src/azul/indexer/index_service.py
  test/integration_test.py
Labels: orange, sandbox

#2055 Add 'cell_suspension.biomaterial_id' to terra.bdbag (#2081)
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/transform.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/service/test_manifest.py
Labels: orange, sandbox

#2065 Define BigQuery types (#2060)
  src/azul/bigquery.py
  src/azul/tdr.py
  test/service/test_tdr.py
Labels: 1 review, orange, sandbox

#2096 Programatically register service accounts with SAM (#2025)
  README.md
  deployments/dev/environment.py
  deployments/sandbox/environment.py
  scripts/register_sam.py
  src/azul/__init__.py
  src/azul/bigquery.py
  src/azul/dss.py
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/tdr.py
  terraform/Makefile
  test/service/test_tdr.py
Labels: orange

#2030 Use multithreading when reading TDR bigquery tables (#2021)
  environment.py
  scripts/can-bundle.py
  src/azul/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/tdr.py
  test/integration_test.py
  test/service/test_tdr.py
Labels: 3 reviews, orange, sandbox

#2075 Include `make package` in destroy instructions
  README.md
Labels: 1 review, orange

#2092 Add blank issue template (#2053)
  .github/ISSUE_TEMPLATE/blank.md
Labels: orange

#2088 Add doctest to BigQueryDataset.parse (#2034)
  src/azul/tdr.py
  test/service/test_tdr.py
  test/test_doctests.py
Labels: orange

#2091 Fix typo in azul_flake8.py (#2086)
  .flake8/azul_flake8.py
Labels: orange
