Repository DataBiosphere/azul, pull requests merged in 2020-02, with the labels that each got.

#1539 Enable direct DSS access via configuration (#1533)
  deployments/.example.local/environment
  deployments/dev/environment
  deployments/sandbox/environment
  environment
  src/azul/__init__.py
  src/azul/dss.py
  test/integration_test.py
Labels: sandbox

#1512 Block indexing by file type instead of by file extension (#1459)
  src/azul/project/hca/metadata_generator.py
  test/indexer/test_hca_indexer.py
Labels: hold warm, orange, sandbox

#1494 Add next and previous link in pagination for service response (#1256)
  lambdas/service/app.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/hca_response_v5.py
  test/service/test_pagination.py
  test/service/test_response.py
Labels: orange, sandbox

#1543 Verify labCount in summary aggregation (#1188)
  src/azul/service/elasticsearch_service.py
  test/service/test_response.py
Labels: sandbox

#1541 Expose specimen organ and part as a facet (#1497)
  src/azul/project/hca/__init__.py
Labels: HCA, orange, port, sandbox, urgent

#1545 Initialize boto session to use credential cache (#1534)
  environment
  scripts/envhook.py
Labels: orange

#1544 Update metadata-api dependency to point to DataBiosphere fork (#1518)
  requirements.txt
Labels: orange, sandbox

#1549 Stop replacing . with _ in participant_id
  src/azul/service/manifest_service.py
  test/service/test_manifest.py
Labels: orange, sandbox

#1524 Always sort multi-valued fields (#1446)
  src/azul/project/hca/transformers.py
  src/azul/service/hca_response_v5.py
  src/azul/transformer.py
  test/indexer/__init__.py
  test/indexer/test_hca_indexer.py
  test/service/test_response.py
Labels: orange, sandbox

#1550 Remove tsv and bdbag manifest format names (#1342)
  lambdas/service/app.py
  src/azul/service/manifest_service.py
  test/integration_test.py
  test/service/test_manifest.py
Labels: orange, sandbox

#1555 Apply orange label to pull requests using new DataBiosphere repo (#1540)
  .github/workflows/label.yml
Labels: orange

#1573 Fix: TypeError aggregating multi-valued fields with None (#1571)
  src/azul/collections.py
  src/azul/project/hca/transformers.py
  src/azul/transformer.py
Labels: orange, sandbox

#1572 Fix: InvalidClientTokenId raised when running unit tests locally (#1567)
  test/azul_test_case.py
Labels: orange

#1554 Sorting by multi-valued fields (#1445)
  src/azul/service/elasticsearch_service.py
  test/service/test_response.py
Labels: orange, sandbox

#1574 ES response for summary request with 'size' set to 0 (#1192)
  src/azul/service/elasticsearch_service.py
Labels: orange, sandbox

#1576 Add specimen organ and organ part facets (#1497, #1564)
  src/azul/project/hca/__init__.py
Labels: orange, sandbox

#1584 Specify 'gitdb2' dependency version (#1583)
  requirements.dev.txt
Labels: orange, sandbox, urgent

#1503 Add DRS 1.0 Support (#1115)
  lambdas/service/app.py
  requirements.dev.txt
  requirements.txt
  src/azul/drs.py
  test/integration_test.py
  test/service/test_drs.py
Labels: orange, sandbox

#1578 Add GET/PUT script for portal database access
  scripts/manage_portals.py
Labels: orange

#1580 Document /version endpoint (#1401)
  lambdas/service/app.py
  src/azul/doctests.py
  src/azul/openapi/__init__.py
  src/azul/openapi/schema.py
  test/test_doctests.py
  test/test_openapi.py
Labels: orange, sandbox

#1579 Log contributions per entity during aggregation
  src/azul/indexer.py
Labels: orange, sandbox

#1581 Remove 'dryrun' capabilities from reindex (#1447)
  scripts/reindex.py
  src/azul/azulclient.py
Labels: hold warm, orange

#1585 Deprecate keywords endpoint (#1408)
  lambdas/service/app.py
Labels: hold warm, orange

#1588 Fix: Terraform warns about destroy provisioners (#1553)
  terraform/authentication.tf.json.template.py
Labels: hold warm, orange

#1598 Change storage backend bucket environment variable name (#1527)
  README.md
  environment
  src/azul/__init__.py
  src/azul/portal_service.py
  test/service/test_portal_service.py
Labels: orange, sandbox

#1603 Use AWS CLI cache for ESClientFactory.get() (#1602)
  src/azul/es.py
Labels: orange, sandbox

#1529 Gitlab reindex timeout (#1481)
  .gitlab-ci.yml
  deployments/sandbox/environment
  scripts/reindex.py
Labels: orange, sandbox
