Repository DataBiosphere/azul, pull requests merged in 2020-05, with the labels that each got.

#1746 Disable DSS subscription in `dev` and `sandbox` (#1745)
  deployments/dev/environment.py
  deployments/sandbox/environment.py
Labels: orange

#1733 Refactor queues.py (type hints, method lifecycle & formatting)
  scripts/reindex.py
  src/azul/queues.py
  test/integration_test.py
Labels: orange, sandbox

#1710 Mock AWS_DEFAULT_REGION for all unit tests
  test/azul_test_case.py
  test/dynamo_test_case.py
  test/health_check_test_case.py
  test/indexer/test_hca_indexer.py
  test/version_table_test_case.py
Labels: 2 reviews, orange, sandbox

#1716 Debug indexing assertion errors (#1693)
  lambdas/indexer/.chalice/config.json.template.py
  src/azul/indexer/__init__.py
Labels: 0 reviews, orange, sandbox

#1736 Fix: `_describe_es_domain_status` is subscribed when None is returned
  src/azul/deployment.py
Labels: 3 reviews, orange, sandbox

#1750 Reword IndexNotFoundError message (#1741)
  src/azul/service/elasticsearch_service.py
Labels: 0 reviews, orange

#1767 Update swagger UI and editor (#1730)
  lambdas/service/vendor/static/swagger-ui.html
  scripts/apidev_static/swagger-editor.html
Labels: 0 reviews, orange, sandbox

#1769 Make make faster
  .dockerignore
  .gitallowed
  .travis.yml
  .trufflehog.json
  Dockerfile
  Makefile
  README.md
  common.mk
  lambdas/Makefile
  lambdas/indexer/Makefile
  lambdas/layer/Makefile
  lambdas/service/Makefile
  terraform/Makefile
  terraform/gitlab/Makefile
Labels: orange

#1728 Validate mandatory param for DSS (#1609)
  lambdas/service/app.py
Labels: 3 reviews, orange, sandbox

#1687 Build OpenAPI spec statically (#1450)
  README.md
  lambdas/service/app.py
  scripts/apidev.py
  src/azul/chalice.py
  src/azul/json.py
  src/azul/openapi/__init__.py
  src/azul/service/policy.py
  test/test_openapi.py
Labels: 2 reviews, chain, orange, sandbox

#1774 Enable app module doctest discovery (#1761)
  src/azul/modules.py
  test/test_doctests.py
Labels: 1 review, orange, sandbox

#1744 Replace ! with / in file names (#1593)
  src/azul/project/hca/metadata_generator.py
  src/azul/project/hca/transformers.py
  test/indexer/test_hca_indexer.py
Labels: 2 reviews, orange, sandbox

#1781 [1/2] Refactor DSS specifics into plugin (#1763)
  attic/rfc/cart-api-endpoints.md
  attic/rfc/cart-api-models.md
  attic/rfc/cart-api-v1.md
  attic/rfc/state_machine.png
  deployments/.example.local/environment.py
  deployments/dev/environment.py
  deployments/sandbox/environment.py
  environment.py
  lambdas/indexer/app.py
  lambdas/service/app.py
  src/azul/__init__.py
  src/azul/azulclient.py
  src/azul/indexer/__init__.py
  src/azul/indexer/index_controller.py
  src/azul/indexer/transformer.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/__init__.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/indexer.py
  src/azul/plugins/metadata/hca/metadata_generator.py
  src/azul/plugins/metadata/hca/transformers.py
  src/azul/plugins/repository/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/portal_service.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/manifest_service.py
  src/azul/subscription.py
  test/azul_test_case.py
  test/indexer/__init__.py
  test/indexer/test_hca_indexer.py
  test/indexer/test_projects.py
  test/service/test_portal_service.py
  test/service/test_request_builder.py
  test/service/test_request_validation.py
  test/service/test_response.py
  test/test_doctests.py
Labels: orange

#1787 Fix broken `check_env` make target
  common.mk
Labels: orange, sandbox

#1743 Rename `deploy` target to `package` & `terraform` to `deploy` (#1654)
  .gitlab-ci.yml
  Makefile
  README.md
  environment.py
  lambdas/Makefile
  lambdas/indexer/Makefile
  lambdas/layer/Makefile
  lambdas/service/Makefile
  src/azul/deployment.py
  test/es_test_case.py
Labels: 3 reviews, orange, sandbox

#1795 Update Google credentials section in README
  README.md
Labels: 1 review, orange

#1725 Ensure Lambda package hash is deterministic (#1673)
  .travis.yml
  Dockerfile
  Makefile
  README.md
  UPGRADING.rst
  common.mk
  deployments/.example.local/environment.local.py
  deployments/.example.local/environment.py
  deployments/dev.gitlab/environment.py
  deployments/dev/environment.py
  deployments/sandbox/environment.py
  environment.py
  lambdas/.wheels/jsonobject-0.9.9-cp36-cp36m-linux_x86_64.whl
  lambdas/.wheels/jsonobject-0.9.9-cp38-cp38-linux_x86_64.whl
  lambdas/indexer/Makefile
  lambdas/service/Makefile
  requirements.dev.txt
  requirements.txt
  scripts/convert_environment.py
  scripts/envhook.py
  scripts/export_environment.py
  scripts/prepare_lambda_deployment.py
  src/azul/__init__.py
  src/azul/json_freeze.py
  src/azul/queues.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/repository_service.py
  src/azul/threads.py
  test/health_check_test_case.py
  test/indexer/test_hca_indexer.py
  test/retorts.py
Labels: 4+ reviews, chain, orange, sandbox

#1819 Add instructions for updating Python interpreter
  UPGRADING.rst
Labels: orange

#1789 [2/2] Refactor DSS specifics into plugin (#1763)
  README.md
  common.mk
  lambdas/service/app.py
  requirements.dev.txt
  requirements.txt
  scripts/envhook.py
  scripts/kibana-proxy.py
  scripts/locust/service.py
  scripts/reindex.py
  scripts/scrape_aws_service_model.py
  src/azul/__init__.py
  src/azul/aws_service_model.py
  src/azul/azulclient.py
  src/azul/deployment.py
  src/azul/health.py
  src/azul/hmac.py
  src/azul/indexer/__init__.py
  src/azul/indexer/aggregate.py
  src/azul/indexer/document.py
  src/azul/indexer/document_service.py
  src/azul/indexer/index_controller.py
  src/azul/indexer/index_service.py
  src/azul/indexer/lambda_iam_policy.py
  src/azul/indexer/transform.py
  src/azul/indexer/transformer.py
  src/azul/json_freeze.py
  src/azul/lambdas.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/aggregate.py
  src/azul/plugins/metadata/hca/full_metadata.py
  src/azul/plugins/metadata/hca/indexer.py
  src/azul/plugins/metadata/hca/transform.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/portal_service.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/lambda_iam_policy.py
  src/azul/service/manifest_service.py
  src/azul/subscription.py
  src/azul/threads.py
  src/azul/types.py
  src/azul/vendored/frozendict/__init__.py
  terraform/api_gateway.tf.json.template.py
  test/azul_test_case.py
  test/indexer/__init__.py
  test/indexer/test_hca_indexer.py
  test/indexer/test_projects.py
  test/integration_test.py
  test/retorts.py
  test/service/__init__.py
  test/service/test_cart_export_job_manager.py
  test/service/test_cart_export_service.py
  test/service/test_collection_data_access.py
  test/service/test_manifest.py
  test/service/test_portal_service.py
  test/service/test_request_validation.py
  test/service/test_response.py
  test/service/test_storage_service.py
  test/test_doctests.py
Labels: chain, orange

#1813 Fix links in OpenAPI description (#1777)
  lambdas/service/app.py
Labels: orange

#1790 Rename `repository` in service routes (#1724)
  lambdas/service/app.py
  scripts/count-bundles.py
  scripts/locust/service.py
  scripts/upload-tsv-files.py
  src/azul/health.py
  test/health_check_test_case.py
  test/integration_test.py
  test/service/test_manifest.py
  test/service/test_pagination.py
  test/service/test_repository_projects.py
  test/service/test_repository_specimen.py
  test/service/test_request_validation.py
  test/service/test_response.py
Labels: 0 reviews, orange, sandbox

#1731 Add test proving path_spec can be shared (#1646)
  test/test_openapi.py
Labels: 3 reviews, orange

#1811 Move `json-object` wheel from lambda packages to layer package (#1770)
  UPGRADING.rst
  lambdas/indexer/Makefile
  lambdas/layer/.gitignore
  lambdas/layer/Makefile
  lambdas/service/Makefile
Labels: 0 reviews, orange, sandbox

#1832 Fix pyenv instructions in README
  README.md
Labels: orange

#1734 Fix ResourceNotFoundException during deploy (#1672)
  UPGRADING.rst
  requirements.dev.txt
Labels: 0 reviews, orange, sandbox

#1647 Document /index endpoints (#1405)
  lambdas/service/app.py
  src/azul/openapi/__init__.py
  src/azul/openapi/params.py
  src/azul/openapi/responses.py
  src/azul/openapi/schema.py
Labels: 4+ reviews, chain, orange, sandbox

#1719 Upgrade Elasticsearch version to 6.8 (#1522)
  requirements.txt
  terraform/elasticsearch.tf.json.template.py
  test/es_test_case.py
  test/indexer/test_hca_indexer.py
  test/indexer/test_projects.py
  test/service/test_request_builder.py
Labels: 1 review, orange, sandbox

#1842 Upgrade instructions for ES 6.8 (#1522)
  UPGRADING.rst
Labels: hold warm, orange, urgent

#1773 Optimize lambda memory usage (#1732)
  lambdas/indexer/.chalice/config.json.template.py
  lambdas/indexer/app.py
  src/azul/__init__.py
  src/azul/azulclient.py
  src/azul/health.py
  src/azul/indexer/index_controller.py
  src/azul/indexer/lambda_iam_policy.py
  src/azul/queues.py
  terraform/cloudwatch.tf.json.template.py
  terraform/sqs.tf.json.template.py
  test/indexer/test_hca_indexer.py
Labels: orange, sandbox

#1799 Rearrange tags in Swagger UI (#1793)
  lambdas/service/app.py
Labels: 0 reviews, orange

#1852 Multiple Gitlab workers (#1851)
  .gitlab-ci.yml
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, sandbox

#1798 Document default sorting behavior (#1782)
  lambdas/service/app.py
  requirements.dev.txt
  scripts/envhook.py
  src/azul/__init__.py
  src/azul/drs.py
  src/azul/openapi/schema.py
  src/azul/security/authenticator.py
  src/azul/service/elasticsearch_service.py
  terraform/gitlab/gitlab.tf.json.template.py
  test/security/test_authenticator.py
Labels: 1 review, orange, sandbox

#1817 Add filters to prev/next links (#1812)
  src/azul/service/elasticsearch_service.py
  test/service/test_pagination.py
Labels: 1 review, orange, sandbox

#1827 Add auto_paging to fetch_bundle_manifest (#1810)
  src/azul/plugins/repository/dss/__init__.py
Labels: 0 reviews, orange, sandbox
