Repository DataBiosphere/azul, pull requests merged in 2020-06, with the labels that each got.

#1847 Format timestamps in queue dumps (#1846)
  src/azul/queues.py
Labels: orange

#1841 Document that freebie tickets should be blocked by PR (#1821)
  CONTRIBUTING.rst
Labels: hold warm, orange

#1859 Fix: Bad link on Service Swagger UI page (#1818)
  lambdas/service/.gitignore
  lambdas/service/vendor/static/swagger-ui.html
Labels: orange, sandbox

#1874 Fix DSS plugin's fetch_bundle_manifest return value (#1873)
  src/azul/azulclient.py
  src/azul/indexer/__init__.py
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/dss/__init__.py
Labels: orange, sandbox

#1876 Log manifest content hash (#1739)
  src/azul/service/manifest_service.py
Labels: orange, sandbox

#1886 Update kibana-proxy.py to work with ES 6.8 (#1885)
  README.md
  scripts/kibana-proxy.py
Labels: orange

#1882 Pin transitive dependencies (#1738)
  .gitattributes
  .gitlab-ci.yml
  Dockerfile
  Makefile
  README.md
  common.mk
  docs/dependencies.svg
  lambdas/layer/requirements.trans.txt
  requirements.dev.trans.txt
  requirements.dev.txt
  requirements.pip.txt
  requirements.trans.txt
  requirements.txt
  scripts/manage_requirements.py
Labels: chain, orange, sandbox

#1742 Dynamically determine timeout for given num of bundles (#1696)
  .gitlab-ci.yml
  scripts/reindex.py
  src/azul/queues.py
  test/integration_test.py
Labels: 4+ reviews, hold warm, orange

#1839 Force compiling of source files during deployment (#1673)
  environment.py
  lambdas/indexer/Makefile
  lambdas/lambdas.mk
  lambdas/layer/Makefile
  lambdas/service/Makefile
Labels: 4+ reviews, orange, sandbox

#1843 Switch to functools.cached_properties (#1796)
  lambdas/indexer/app.py
  lambdas/service/app.py
  requirements.txt
  src/azul/azulclient.py
  src/azul/deployment.py
  src/azul/health.py
  src/azul/indexer/document_service.py
  src/azul/indexer/index_controller.py
  src/azul/lambda_layer.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/queues.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/manifest_service.py
  src/azul/service/storage_service.py
  test/integration_test.py
  test/service/test_response.py
Labels: 2 reviews, orange, sandbox

#1867 Fix another link in OpenAPI docs (#1777)
  lambdas/service/app.py
Labels: orange

#1881 Rename `disease` facet to `sampleDisease` (#1592)
  lambdas/service/app.py
  src/azul/plugins/metadata/hca/__init__.py
  test/service/test_request_builder.py
  test/service/test_response.py
Labels: 1 review, orange, sandbox

#1872 Add sequencing process ID to terra.bdbag manifests (#1853)
  src/azul/project/hca/__init__.py
  src/azul/project/hca/transformers.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/service/test_manifest.py
Labels: 0 reviews, HCA, sandbox

#1875 Prevent `future` related warnings (#1783)
  src/azul/plugins/metadata/hca/full_metadata.py
Labels: orange, sandbox

#1884 Add exception handling to tally aggregation (#1890, #1845)
  src/azul/indexer/index_controller.py
Labels: 0 reviews, orange, sandbox

#1877 Improve HEAD method spec for index endpoints
  lambdas/service/app.py
Labels: 0 reviews, orange, sandbox

#1894 Add crc32c to manifests and make sha256 optional (#1866)
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/full_metadata.py
  src/azul/plugins/metadata/hca/transform.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/service/test_manifest.py
Labels: 1 review, orange, sandbox

#1908 Remove redundant bundles from Terra export (#1904)
  src/azul/service/manifest_service.py
  test/indexer/data/cfab8304-dc9f-439e-af29-f8eb75b0729d.manifest.json
  test/indexer/data/cfab8304-dc9f-439e-af29-f8eb75b0729d.metadata.json
  test/indexer/data/f0731ab4-6b80-4eed-97c9-4984de81a47c.manifest.json
  test/indexer/data/f0731ab4-6b80-4eed-97c9-4984de81a47c.metadata.json
  test/service/test_manifest.py
Labels: HCA, sandbox

#1906 Add sequencing process ID to terra.bdbag manifests (#1899)
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/aggregate.py
  src/azul/plugins/metadata/hca/transform.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/service/test_manifest.py
Labels: orange, sandbox

#1900 Add retry to integration test notifications
  src/azul/azulclient.py
Labels: orange, sandbox

#1915 Gitlab IAM policy for Data Portal & Browser deployment (#1893)
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange

#1913 Refactor manifest tests (#1430)
  src/azul/service/elasticsearch_service.py
  src/azul/service/manifest_service.py
  test/service/test_manifest.py
Labels: no demo, orange, sandbox

#1920 Fix: `make requirements_update` is not stable (#1919)
  Makefile
Labels: orange, sandbox

#1925 Gitlab IAM policy for Data Portal & Browser deployment (#1893)
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange

#1856 Use Terraform to determine ES env variables (#1704)
  README.md
  lambdas/indexer/.chalice/config.json.template.py
  lambdas/service/.chalice/config.json.template.py
  scripts/prepare_lambda_deployment.py
  src/azul/__init__.py
  src/azul/deployment.py
  terraform/modules.tf.json.template.py
  test/integration_test.py
Labels: 4+ reviews, orange, sandbox

#1878 Remove pagination elements made obsolete by next/previous links (#1499)
  scripts/count-bundles.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/hca_response_v5.py
  test/integration_test.py
  test/service/test_pagination.py
  test/service/test_response.py
Labels: 3 reviews, orange, sandbox

#1933 Enable error logs on Elasticsearch domain (#1888)
  terraform/elasticsearch.tf.json.template.py
Labels: 0 reviews, orange, sandbox

#1865 Filter resource warnings in integration tests (#1825)
  Makefile
  requirements.dev.trans.txt
  requirements.trans.txt
  test/app_test_case.py
  test/azul_test_case.py
  test/docker_container_test_case.py
  test/integration_test.py
  test/service/test_async_manifest_service.py
  test/service/test_buffer.py
  test/service/test_cart_export_endpoints.py
  test/service/test_cart_export_job_manager.py
  test/service/test_cart_export_service.py
  test/service/test_manifest.py
  test/service/test_storage_service.py
  test/test_app_logging.py
  test/test_changelog.py
  test/test_openapi.py
  test/version_table_test_case.py
Labels: 4+ reviews, orange, sandbox

#1918 Allow personal deployment from any branch (#1715)
  scripts/check_branch.py
  src/azul/__init__.py
  terraform/s3.tf.json.template.py
  test/integration_test.py
Labels: 1 review, orange, sandbox

#1926 Fix: HEAD /index/summary spec declares a body (#1916)
  lambdas/service/app.py
Labels: 0 reviews, orange, sandbox
