Repository DataBiosphere/azul, pull requests merged in 2020-03, with the labels that each got.

#1600 Document /openapi endpoint (#1407)
  lambdas/service/app.py
  src/azul/openapi/schema.py
Labels: orange, sandbox

#1606 Document AWS CodeCommit for Gitlab configurations (#1523)
  README.md
Labels: orange

#1610 Strip trailing = from DRS access key (#1604)
  src/azul/drs.py
Labels: orange, sandbox

#1614 Disable cart endpoints (#1513)
  environment
  lambdas/indexer/app.py
  lambdas/service/app.py
  src/azul/chalice.py
  src/azul/modules.py
  test/app_test_case.py
  test/test_app_logging.py
Labels: orange, sandbox

#1611 Catch correct HTTPError in order to retry notifications (#1551)
  src/azul/azulclient.py
Labels: orange, sandbox

#1597 Simplify indexing retry that allows tallies of 0 (#1570)
  src/azul/indexer.py
  src/azul/transformer.py
  test/indexer/test_hca_indexer.py
Labels: orange, sandbox

#1586 Document /dss/files and /fetch/dss/files endpoints (#1402)
  lambdas/service/app.py
  src/azul/openapi/__init__.py
  src/azul/openapi/params.py
  src/azul/openapi/responses.py
  src/azul/openapi/schema.py
  src/azul/strings.py
  test/test_doctests.py
Labels: orange, sandbox

#1619 Add specimenDisease facet (#1591)
  src/azul/project/hca/__init__.py
  test/service/test_response.py
Labels: orange, sandbox

#1616 Make queue waiting less demanding (#1557)
  scripts/reindex.py
  src/azul/queues.py
  test/integration_test.py
Labels: orange, sandbox

#1625 Backport: Add specimenDisease facet (#1624)
  src/azul/project/hca/__init__.py
  test/service/test_response.py
Labels: sandbox

#1627 Get Gateway ID from app.current_request, not environment (#1626)
  lambdas/indexer/.chalice/config.json.template.py
  lambdas/service/.chalice/config.json.template.py
  lambdas/service/app.py
  scripts/apidev.py
  src/azul/deployment.py
  src/azul/openapi/__init__.py
Labels: orange, sandbox

#1628 Upgrade to hca 7.0.1 (#1487)
  requirements.txt
Labels: orange, sandbox

#1632 Replace @azul.decorators.memoized_property with boltons.cacheutils.cachedproperty
  src/azul/decorators.py
  src/azul/deployment.py
  src/azul/health.py
  src/azul/queues.py
  src/azul/service/storage_service.py
  test/integration_test.py
Labels: orange, sandbox

#1636 Convert drs.py from `urllib.parse` to `furl` (#1612)
  src/azul/drs.py
  test/service/test_drs.py
Labels: orange, sandbox

#1622 Fix: Manifest generation exhausts memory on Lambda (#1596)
  src/azul/service/manifest_service.py
  src/azul/service/storage_service.py
Labels: orange, sandbox

#1587 Fix: Paging broken when sorting fields with Null values (#1575)
  lambdas/service/app.py
  src/azul/__init__.py
  src/azul/collections.py
  src/azul/project/hca/transformers.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/hca_response_v5.py
  src/azul/transformer.py
  test/indexer/__init__.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/indexer/test_hca_indexer.py
  test/service/test_pagination.py
  test/service/test_request_builder.py
  test/service/test_response.py
Labels: orange, sandbox

#1649 Eliminate /health test code duplication (#1443)
  test/health_check_test_case.py
  test/indexer/test_health_check.py
  test/service/test_health_check.py
Labels: orange, sandbox

#1435 Document manifest endpoints (#1404)
  lambdas/service/app.py
  src/azul/openapi/__init__.py
  src/azul/openapi/params.py
  src/azul/openapi/responses.py
  src/azul/strings.py
  test/service/test_async_manifest_service.py
Labels: orange, sandbox

#1651 Switch to get_bundles_all.iterate() (#1486)
  src/azul/azulclient.py
Labels: orange, sandbox

#1634 Print TF version during gitlab deploy (#1200)
  .gitlab-ci.yml
Labels: orange, sandbox

#1608 Backport: Paging broken when sorting fields with Null values (#1607)
  lambdas/service/app.py
  src/azul/__init__.py
  src/azul/collections.py
  src/azul/project/hca/transformers.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/hca_response_v5.py
  src/azul/transformer.py
  test/indexer/__init__.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/indexer/test_hca_indexer.py
  test/service/test_pagination.py
  test/service/test_request_builder.py
  test/service/test_response.py
Labels: HCA, orange

#1652 Link to /dss/files for response description (#1642)
  lambdas/service/app.py
Labels: orange, sandbox

#1657 Azul Readme: notes about branch merging
  README.md
Labels: doc, orange

#1631 Replace str.format with f-strings (#1193)
  src/azul/queues.py
  src/azul/service/elasticsearch_service.py
  test/integration_test.py
  test/service/test_pagination.py
  test/service/test_request_builder.py
Labels: 4+ reviews, hold warm, orange, sandbox
