Repository DataBiosphere/azul, pull requests merged in 2021-04, with the labels that each got.

#2921 Update GitLab to 13.10.0 (#2889)
  terraform/gitlab/gitlab.tf.json.template.py
Labels: no sandbox, orange

#2777 Add ability to index a single source (#2766)
  CONTRIBUTING.rst
  scripts/reindex.py
  src/azul/__init__.py
  src/azul/azulclient.py
Labels: 4+ reviews, orange, urgent

#2911 Add /repository/files URL to compact manifest (#2863)
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/service/manifest_service.py
  test/service/test_manifest.py
Labels: 3 reviews, orange

#2892 Create a Jupyter notebook to download project matrices (#2864)
  docs/download-project-matrices.ipynb
  docs/hca_file_downloader.py
Labels: no demo, no sandbox, orange

#2855 Change queue waiter heuristic to measure progress (#2617)
  .gitlab-ci.yml
  scripts/reindex.py
  src/azul/azulclient.py
  src/azul/queues.py
  test/integration_test.py
Labels: 3 reviews, orange

#2936 Do not instruct operator to manage BQ slots (#2924)
  .github/pull_request_template.md
  .gitlab-ci.yml
Labels: 0 reviews, no demo, orange

#2938 Fix: Orange labeler doesn't work on PRs from forks (#2895)
  .github/workflows/label.yml
Labels: 0 reviews, orange

#2942 Extend expiration of signed URLs for TDR files (#2876)
  src/azul/plugins/repository/tdr/__init__.py
Labels: 0 reviews, no demo, orange

#2961 Increase queue stabilization window to 10 minutes (#2959)
  src/azul/queues.py
Labels: 1 review, orange, urgent

#2963 Disable globbing in curl manifest (#2943)
  src/azul/service/manifest_service.py
  test/service/test_manifest.py
Labels: 0 reviews, orange, urgent

#2967 Remove `/fetch` from file URLs in projects & files endpoint (#2908)
  src/azul/service/index_query_service.py
  test/service/test_response.py
Labels: 0 reviews, orange, urgent

#2962 Refactor async manifest code (#2949)
  lambdas/service/app.py
  src/azul/service/async_manifest_service.py
  src/azul/service/manifest_controller.py
  test/service/test_async_manifest_service.py
  test/service/test_manifest_async.py
Labels: no demo, orange

#2934 Rephrase PR checklists for reindexing prod (#2836)
  .github/pull_request_template.md
Labels: 0 reviews, no demo, no sandbox, orange

#2968 Add instruction for `sandbox` label in PR template (#2918)
  .github/pull_request_template.md
Labels: 0 reviews, no demo, no sandbox, orange

#2960 Add reindex_no_slots make target (#2947)
  Makefile
  README.md
  requirements.dev.trans.txt
  requirements.trans.txt
Labels: orange

#2939 Add logging of file downloads (#2858)
  src/azul/service/repository_controller.py
Labels: 1 review, orange

#2740 Fix: Extraneous `null` values in hits[].samples[].* (#2071)
  src/azul/indexer/document.py
  src/azul/indexer/index_service.py
  src/azul/indexer/transform.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/transform.py
  src/azul/service/hca_response_v5.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/service/test_response.py
Labels: 4+ reviews, orange, reindex

#2969 Remove existing authentication and cart functionality (#2950)
  UPGRADING.rst
  attic/cart/cart_export_job_manager.py
  attic/cart/cart_export_service.py
  attic/cart/cart_item_manager.py
  attic/cart/test_cart_export_endpoints.py
  attic/cart/test_cart_export_job_manager.py
  attic/cart/test_cart_export_service.py
  attic/cart/test_cart_item_manager.py
  attic/cart/test_user_service.py
  attic/cart/user_service.py
  attic/security/authenticator.py
  attic/security/test_auth_endpoints.py
  attic/security/test_authenticator.py
  environment.py
  lambdas/service/.chalice/config.json.template.py
  lambdas/service/app.py
  scripts/rename_resources.py
  src/azul/__init__.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/security/__init__.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/lambda_iam_policy.py
  terraform/dynamo.tf.json.template.py
  terraform/grafana_dashboard.tf.json.template.py
  terraform/step_function.tf.json.template.py
  test/app_test_case.py
  test/retorts.py
  test/security/__init__.py
  test/service/test_request_builder.py
Labels: 1 review, chain, no demo, orange, sandbox, upgrade

#2888 Fix: Worker threads continue after interrupted portal IT (#2887)
  test/integration_test.py
Labels: 1 review, no demo, orange, sandbox

#2933 Remove final reference to DSS from OpenAPI spec (#2671)
  lambdas/service/app.py
Labels: 0 reviews, no demo, orange, sandbox

#2925 Fix: DefaultCredentialsError when AZUL_TDR_WORKERS to > 1 (#2910)
  src/azul/terra.py
Labels: 2 reviews, orange, sandbox

#2928 Only GitLab runner can deploy to `sandbox` (#2842)
  scripts/check_branch.py
Labels: 2 reviews, orange, sandbox

#2946 Fix: sell_unused_slots.py ignores `--help` and sells slots anyway (#2944)
  scripts/sell_unused_slots.py
  src/azul/bigquery_reservation.py
Labels: 0 reviews, orange

#3001 Remove outdated FIXMEs (#1646)
  lambdas/service/app.py
Labels: 0 reviews, no demo, orange, sandbox

#2847 Fix: Compact manifest rows for related files have main file's DRS URI (#2846)
  src/azul/plugins/metadata/hca/transform.py
  src/azul/service/manifest_service.py
  test/service/test_manifest.py
Labels: 4+ reviews, orange, reindex, sandbox

#2929 Fix brittle coupling with lambda names in manage_queues.py (#1848)
  lambdas/indexer/.chalice/config.json.template.py
  lambdas/service/.chalice/config.json.template.py
  lambdas/service/app.py
  scripts/sell_unused_slots.py
  src/azul/__init__.py
  src/azul/chalice.py
  src/azul/queues.py
  src/azul/service/lambda_iam_policy.py
  terraform/step_function.tf.json.template.py
  test/service/test_manifest_async.py
Labels: 4+ reviews, no demo, orange, sandbox

#2988 Switch from Travis to GitHub Actions for CI (#2768)
  .github/workflows/ci.yml
  attic/.travis.yml
Labels: 0 reviews, no demo, orange, sandbox, urgent

#3017 Enable gzip compression of service responses (#1910)
  lambdas/indexer/.chalice/config.json.template.py
  lambdas/service/.chalice/config.json.template.py
  src/azul/__init__.py
Labels: 0 reviews, orange, sandbox

#3029 Index hca_dev_20201203___20210426 into dcp2 on dev (#3028)
  deployments/dev/environment.py
  deployments/sandbox/environment.py
Labels: no demo, orange, reindex, sandbox
