Repository DataBiosphere/azul, pull requests merged in 2021-08, with the labels that each got.

#3289 [r] Index hca_prod_20201120_dcp2___20210730_dcp8 into dcp8 on prod (#3287)
  deployments/prod/environment.py
Labels: no sandbox, orange, reindex

#3306 Fix: TDR query fails with syntax error (#3305)
  src/azul/bigquery.py
  src/azul/plugins/repository/tdr/__init__.py
  test/test_doctests.py
Labels: sandbox, orange, 2 reviews

#3168 Fix: PFB manifest fails with multiple inner entities of the same type (#3157)
  src/azul/service/avro_pfb.py
  test/service/data/pfb_manifest.results.json
  test/service/test_manifest.py
Labels: sandbox, orange, 2 reviews

#3112 Increase test coverage for ManifestController (#2414)
  src/azul/service/manifest_service.py
  test/service/test_manifest.py
  test/service/test_manifest_async.py
Labels: sandbox, orange, 4+ reviews

#3186 Increase lambda concurrency and BigQuery slots in prod (#3137)
  UPGRADING.rst
  deployments/prod/environment.py
  deployments/sandbox/environment.py
  environment.py
  lambdas/indexer/.chalice/config.json.template.py
  src/azul/__init__.py
  src/azul/bigquery_reservation.py
  src/azul/indexer/index_service.py
Labels: orange, 4+ reviews, upgrade

#3245 Enforce access controls on file downloads (#2957)
  lambdas/service/app.py
  src/azul/drs.py
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/canned/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/service/index_query_service.py
  src/azul/service/repository_controller.py
  test/integration_test.py
  test/service/test_repository_proxy.py
Labels: sandbox, orange, 3 reviews, chain

#3322 Revert "Enforce access controls on file downloads (#2957, PR #3245)"
  lambdas/service/app.py
  src/azul/drs.py
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/canned/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/service/index_query_service.py
  src/azul/service/repository_controller.py
  test/integration_test.py
  test/service/test_repository_proxy.py
Labels: orange, no sandbox

#3261 Can new prod bundles for matrix test cases (#3192)
  requirements.dev.trans.txt
  requirements.trans.txt
  src/azul/plugins/metadata/hca/transform.py
  test/indexer/data/00f48893-5e9d-52cd-b32d-af88edccabfa.manifest.json
  test/indexer/data/00f48893-5e9d-52cd-b32d-af88edccabfa.metadata.json
  test/indexer/data/04836733-0449-4e57-be2e-6f3b8fbdfb12.manifest.json
  test/indexer/data/04836733-0449-4e57-be2e-6f3b8fbdfb12.metadata.json
  test/indexer/data/1ec111a0-7481-571f-b35a-5a0e8fca890a.manifest.json
  test/indexer/data/1ec111a0-7481-571f-b35a-5a0e8fca890a.metadata.json
  test/indexer/data/4b03c1ce-9df1-5cd5-a8e4-48a2fe095081.manifest.json
  test/indexer/data/4b03c1ce-9df1-5cd5-a8e4-48a2fe095081.metadata.json
  test/indexer/data/7eb74d9f-8346-5420-b7e4-b486f99451a8.manifest.json
  test/indexer/data/7eb74d9f-8346-5420-b7e4-b486f99451a8.metadata.json
  test/indexer/data/8338b891-f3fa-5e7b-885f-e4ee5689ee15.manifest.json
  test/indexer/data/8338b891-f3fa-5e7b-885f-e4ee5689ee15.metadata.json
  test/indexer/data/f0731ab4-6b80-4eed-97c9-4984de81a47c.manifest.json
  test/indexer/data/f0731ab4-6b80-4eed-97c9-4984de81a47c.metadata.json
  test/indexer/test_hca_indexer.py
  test/service/test_response.py
Labels: sandbox, orange, 1 review, chain

#3134 Fix: Bam and intermediate loom files have null file source (#3096)
  src/azul/plugins/metadata/hca/transform.py
  test/service/data/pfb_manifest.results.json
  test/service/test_response.py
Labels: sandbox, orange, 2 reviews, chain, reindex

#3223 Add spot for issue reference to PR template (#3219)
  .github/pull_request_template.md
Labels: orange, 0 reviews, no sandbox

#3285 Move operator manual to source tree (#3240)
  OPERATOR.rst
Labels: orange, 1 review, no sandbox

#3262 Add announcement section to PR template (#3257)
  .github/pull_request_template.md
Labels: orange, no sandbox

#3314 Remove references to groups for public accounts (#3296)
  README.md
Labels: orange, 0 reviews, no sandbox

#3109 Convert AZUL_CATALOGS to JSON (#2945)
  UPGRADING.rst
  deployments/dev/environment.py
  deployments/prod/environment.py
  deployments/sandbox/environment.py
  environment.py
  lambdas/service/openapi.json
  scripts/export_environment.py
  scripts/generate_openapi_document.py
  src/azul/__init__.py
  src/azul/plugins/__init__.py
  src/azul/service/catalog_controller.py
  test/azul_test_case.py
  test/service/test_repository_proxy.py
  test/service/test_response.py
Labels: sandbox, orange, 4+ reviews, chain

#3265 Add ability to remove a source from the catalog (#2748)
  scripts/reindex.py
  src/azul/azulclient.py
Labels: sandbox, orange, 2 reviews

#3308 Log authentication failures in TerraClient (#3246)
  src/azul/terra.py
Labels: sandbox, orange, 2 reviews

#3221 Indicate accessible hits (#2955)
  lambdas/service/app.py
  src/azul/service/index_query_service.py
  test/service/test_repository_projects.py
  test/service/test_request_validation.py
  test/service/test_response.py
Labels: orange, 3 reviews

#3182 Make hits.fileTypeSummary consistent with hits.files (#3171)
  docs/hca_file_downloader.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/aggregate.py
  src/azul/plugins/metadata/hca/transform.py
  src/azul/service/hca_response_v5.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/indexer/test_hca_indexer.py
  test/service/data/pfb_manifest.results.json
  test/service/test_repository_projects.py
  test/service/test_repository_specimen.py
  test/service/test_response.py
Labels: sandbox, orange, 4+ reviews, reindex

#3341 Fix: Lambda layer zip file exceeded deployment package size limit (#3329)
  lambdas/lambdas.mk
  lambdas/layer/.gitignore
  lambdas/layer/requirements.trans.txt
  lambdas/layer/requirements.txt
  src/azul/lambda_layer.py
Labels: sandbox, orange, 1 review

#3343 [r] Index hca_prod_20201120_dcp2___20210812_dcp8 into dcp8 on `prod` (#3327)
  deployments/prod/environment.py
Labels: orange, reindex, no sandbox

#3276 Allow catalog.internal to be configurable (#2865)
  UPGRADING.rst
  deployments/dev/environment.py
  deployments/prod/environment.py
  deployments/sandbox/environment.py
  environment.py
  scripts/generate_openapi_document.py
  src/azul/__init__.py
  src/azul/service/catalog_controller.py
  test/azul_test_case.py
  test/integration_test.py
  test/service/test_repository_proxy.py
Labels: sandbox, orange, 3 reviews, chain, upgrade

#3324 Enforce access controls on file downloads (#2957)
  lambdas/service/app.py
  src/azul/drs.py
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/canned/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/service/index_query_service.py
  src/azul/service/repository_controller.py
  test/integration_test.py
  test/service/test_repository_proxy.py
Labels: sandbox, orange, 4+ reviews, chain

#3286 Implement paging for listing snapshots in TDR (#3093, #3195)
  src/azul/terra.py
  test/indexer/test_tdr.py
  test/integration_test.py
Labels: sandbox, orange, 2 reviews

#3183 Include CommandLine item on all /fetch/manifest/files responses (#3142)
  lambdas/service/app.py
  src/azul/service/manifest_controller.py
  src/azul/service/manifest_service.py
  test/service/test_manifest.py
  test/service/test_manifest_async.py
Labels: sandbox, orange, 4+ reviews, chain

#3346 Add PR checkbox for PR title requirements (#3345)
  .github/pull_request_template.md
Labels: orange, 0 reviews, no sandbox

#3363 [r] Fix: AttributeError during prod reindex (#3353)
  src/azul/plugins/metadata/hca/transform.py
Labels: orange, 0 reviews, reindex
