Repository DataBiosphere/azul, pull requests merged in 2021-10, with the labels that each got.

#3455 File backport PRs from a feature branch (#3442)
  OPERATOR.rst
Labels: orange, 1 review, no sandbox

#3282 Cover OAuth 2.0 authentication in integration test (#3266)
  test/integration_test.py
Labels: sandbox, orange, 4+ reviews, chain

#3473 Fix: Many unit tests fail if `AZUL_DSS_QUERY_PREFIX` is set (#3321)
  test/azul_test_case.py
Labels: sandbox, orange, 1 review

#3237 Cover can_bundle.py in integration tests (#3196)
  README.md
  UPGRADING.rst
  src/azul/caching.py
  src/azul/plugins/__init__.py
  test/integration_test.py
Labels: orange, 4+ reviews, upgrade

#3481 Fix: RequestEntityTooLarge with large environment during `make deploy` (#3479)
  Makefile
  lambdas/indexer/.gitignore
  lambdas/indexer/Makefile
  lambdas/indexer/app.py
  lambdas/indexer/vendor/resources/environ.json.template.py
  lambdas/lambdas.mk
  lambdas/layer/app.py
  lambdas/service/.gitignore
  lambdas/service/Makefile
  lambdas/service/app.py
  lambdas/service/vendor/resources/environ.json.template.py
  lambdas/service/vendor/resources/static/oauth2-redirect.html
  lambdas/service/vendor/resources/static/swagger-ui.html.template.mustache
  requirements.dev.trans.txt
  requirements.trans.txt
  src/azul/__init__.py
  src/azul/chalice.py
  test/integration_test.py
  test/test_app_logging.py
  test/test_openapi.py
Labels: sandbox, orange, reqs

#3441 Fix: TDR dev dataset is stale (HumanCellAtlas/dcp2#17)
  UPGRADING.rst
  deployments/dev/environment.py
  deployments/sandbox/environment.py
Labels: sandbox, orange, 1 review, reindex, upgrade

#3488 Derive prefix from snapshot size (HumanCellAtlas/dcp2#17)
  deployments/dev/environment.py
  deployments/sandbox/environment.py
  environment.py
  src/azul/__init__.py
  src/azul/terra.py
Labels: sandbox, orange, reindex

#3465 Fix: `make clean` does not cleanup files from lambdas/layer directory (#3429)
  lambdas/Makefile
Labels: sandbox, orange, 0 reviews, reqs

#3391 Provide the overall latest update date for a project (#3350)
  src/azul/plugins/metadata/hca/aggregate.py
  src/azul/plugins/metadata/hca/transform.py
  src/azul/service/hca_response_v5.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/service/data/pfb_manifest.results.json
  test/service/test_repository_projects.py
  test/service/test_response.py
Labels: sandbox, orange, 4+ reviews, reindex

#3369 Add accessions to project response (#3331)
  lambdas/service/openapi.json
  requirements.dev.trans.txt
  requirements.trans.txt
  requirements.txt
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/aggregate.py
  src/azul/plugins/metadata/hca/transform.py
  src/azul/service/hca_response_v5.py
  test/azul_test_case.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/indexer/data/fa5be5eb-2d64-49f5-8ed8-bd627ac9bc7a.metadata.json
  test/indexer/test_hca_indexer.py
  test/service/data/pfb_manifest.results.json
  test/service/test_repository_projects.py
  test/service/test_response.py
Labels: sandbox, orange, 4+ reviews, reindex, reqs

#3311 Updated README.md with steps for macOS BigSur (#3288)
  README.md
Labels: orange, 4+ reviews, no sandbox

#3477 Fix: `requests` module raises RequestsDependencyWarning (#3402)
  requirements.trans.txt
  requirements.txt
  test/service/test_app_logging.py
  test/test_app_logging.py
Labels: sandbox, orange, 0 reviews, reqs

#3550 Fix: Integration tests may fail to cover managed access functionality (#3422)
  src/azul/__init__.py
  test/azul_test_case.py
  test/integration_test.py
Labels: sandbox, orange, 3 reviews, chain

#3533 Reduce number of shards for IT catalogs (#3515)
  UPGRADING.rst
  src/azul/indexer/index_service.py
Labels: sandbox, orange, 1 review
