Repository DataBiosphere/azul, pull requests merged in 2021-12, with the labels that each got.

#3582 Fix: Manifest command lines use wrong file name (#3570)
  src/azul/service/manifest_service.py
  test/service/test_manifest.py
Labels: sandbox, orange, 2 reviews

#3669 Make dcp11 the default catalog on `prod` (#3656)
  deployments/prod/environment.py
Labels: orange

#3375 Fix: Samples don't reflect downstream entities from stitched subgraphs (#3095)
  attic/src/azul/plugins/repository/local/__init__.py
  src/azul/plugins/metadata/hca/transform.py
  test/indexer/data/79fa91b4-f1fc-534b-a935-b57342804a70.2020-12-10T10:30:00.000000Z.manifest.json
  test/indexer/data/79fa91b4-f1fc-534b-a935-b57342804a70.2020-12-10T10:30:00.000000Z.metadata.json
  test/indexer/test_hca_indexer.py
Labels: sandbox, orange, 3 reviews, reindex

#3678 Merge branch promotions/2021-12-01 into prod
  .github/pull_request_template.md
  attic/src/azul/plugins/repository/local/__init__.py
  deployments/prod/environment.py
  src/azul/plugins/metadata/hca/transform.py
  src/azul/service/manifest_service.py
  terraform/gitlab/gitlab.tf.json.template.py
  test/indexer/data/79fa91b4-f1fc-534b-a935-b57342804a70.2020-12-10T10:30:00.000000Z.manifest.json
  test/indexer/data/79fa91b4-f1fc-534b-a935-b57342804a70.2020-12-10T10:30:00.000000Z.metadata.json
  test/indexer/test_hca_indexer.py
  test/service/test_manifest.py
Labels: orange, no demo, reindex, no sandbox

#3612 Fix: Listing bundles for a snapshot gives zero bundles (#3561)
  UPGRADING.rst
  deployments/dev/environment.py
  deployments/sandbox/environment.py
  test/integration_test.py
Labels: sandbox, orange, chain, 0 reviews, upgrade

#3684 Experiment with shard counts (#3630)
  src/azul/indexer/index_service.py
Labels: orange, reindex, no sandbox

#3687 Update GitLab to 14.5.2
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, no demo, 0 reviews, no sandbox

#3646 Fix: Lambda layer fails to upload to storage bucket (NoSuchBucket) (#3639)
  src/azul/__init__.py
  src/azul/lambda_layer.py
  terraform/Makefile
Labels: sandbox, orange, 1 review

#3690 Backport: 191a0396 (#3630, PR #3684)
  src/azul/indexer/index_service.py
Labels: sandbox, orange, no demo, 0 reviews

#3686 Index additional projects to prod2 (#3667)
  deployments/prod2/environment.py
Labels: orange, 0 reviews, reindex, no sandbox, hotfix

#3696 [r] Index hca_prod_20201120_dcp2___20211213_dcp12 into dcp12 on prod (#3695)
  deployments/prod/environment.py
Labels: orange, 0 reviews, reindex, no sandbox
