Repository DataBiosphere/azul, pull requests merged in 2021-09, with the labels that each got.

#3347 Upgrade requirements from Snyk and dependabot PRs (#3338)
  requirements.dev.trans.txt
  requirements.dev.txt
  requirements.trans.txt
  requirements.txt
Labels: sandbox, orange, 0 reviews, reqs

#3393 Document conflict resolution fixups
  CONTRIBUTING.rst
Labels: orange, no demo, no sandbox

#3379 Make dcp8 the default catalog on `prod` (#3317)
  OPERATOR.rst
  deployments/prod/environment.py
Labels: orange, 0 reviews, no sandbox

#3400 Index hca_prod_20201120_dcp2___20210827_dcp9 into dcp9 on prod (#3383)
  deployments/prod/environment.py
Labels: orange, reindex, no sandbox

#3374 Fix: Lots of `TransportError`s from Elasticsearch during integration test run on `sandbox` and `dev` (#3339)
  deployments/dev/environment.py
  deployments/sandbox/environment.py
Labels: sandbox, orange

#3401 Fix: A crashed portal DB IT causes subsequent IT runs to fail (#3376)
  test/integration_test.py
Labels: sandbox, orange

#3232 Provide body with command lines on responses to /manifest/files (#3177)
  src/azul/service/manifest_controller.py
  src/azul/service/manifest_service.py
  test/service/test_manifest.py
Labels: sandbox, orange, 4+ reviews

#3351 Fix: IT on develop failed during _prepare_notifications (#3326)
  scripts/sell_unused_slots.py
  src/azul/bigquery_reservation.py
  terraform/authentication.tf.json.template.py
Labels: sandbox, orange, 3 reviews

#3366 Clean up old versions of portal database in S3 (#2830)
  README.md
  src/azul/portal_service.py
  test/integration_test.py
Labels: sandbox, orange, 0 reviews

#3405 Fix: `fastavro.writer` heuristic for choosing record types can be defeated (#3396)
  lambdas/.wheels/fastavro-1.3.1-cp38-cp38-manylinux2014_x86_64.whl
  lambdas/.wheels/fastavro-1.4.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  lambdas/layer/Makefile
  requirements.trans.txt
  requirements.txt
  src/azul/service/avro_pfb.py
Labels: sandbox, orange, 2 reviews, reqs

#3323 Upgrade Chalice to 1.24.1 (#3290)
  common.mk
  deployments/sandbox/environment.py
  lambdas/.wheels/grpcio-1.34.1-cp38-cp38-manylinux2014_x86_64.whl
  lambdas/layer/.gitignore
  lambdas/layer/Makefile
  lambdas/service/app.py
  requirements.dev.trans.txt
  requirements.dev.txt
  src/azul/chalice.py
  test/service/test_app_logging.py
  test/test_app_logging.py
Labels: sandbox, orange, 2 reviews, reqs

#3403 Fix: Download of curl manifest fails obscurely from 410 status code (#3127)
  lambdas/service/app.py
  lambdas/service/openapi.json
  src/azul/service/manifest_service.py
  test/service/test_manifest.py
Labels: sandbox, orange, 0 reviews

#3409 Standardize process for back-porting `prod` to `develop` in operator manual (#3378)
  OPERATOR.rst
Labels: orange, no demo

#3423 Index hca_prod_20201120_dcp2___20210910_dcp9 into dcp9 on prod (#3421)
  deployments/prod/environment.py
Labels: orange, reindex, no sandbox

#2931 Add prefix_length to source (#2750)
  Makefile
  UPGRADING.rst
  deployments/dev/environment.py
  deployments/prod/environment.py
  deployments/sandbox/environment.py
  environment.py
  scripts/export_environment.py
  scripts/recan_bundle_tdr.py
  scripts/reindex.py
  src/azul/__init__.py
  src/azul/azulclient.py
  src/azul/indexer/__init__.py
  src/azul/indexer/document.py
  src/azul/indexer/index_controller.py
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/canned/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/terra.py
  src/azul/uuids.py
  test/azul_test_case.py
  test/indexer/__init__.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/indexer/test_indexer_controller.py
  test/indexer/test_tdr.py
  test/integration_test.py
  test/service/test_manifest.py
  test/service/test_repository_proxy.py
  test/service/test_response.py
Labels: sandbox, orange, 4+ reviews, reqs, upgrade

#3433 Fix: Various wheel/Chalice issues (#3428, #3432, #3434)
  lambdas/.wheels/fastavro-1.4.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  lambdas/layer/Makefile
  requirements.dev.trans.txt
  requirements.pip.txt
  requirements.trans.txt
Labels: sandbox, orange, 1 review, reqs

#3430 Backport: ded59b1 (#3421)
  deployments/prod/environment.py
Labels: orange, no demo, no sandbox

#3418 Fix: ManifestPartition.from_json does not convert search_after to tuple (#3291)
  src/azul/service/manifest_service.py
  test/service/test_manifest_async.py
Labels: sandbox, orange, 1 review

#3419 Convert datetime values to strings before indexing (#3416)
  src/azul/indexer/document.py
  src/azul/plugins/metadata/hca/transform.py
  src/azul/service/avro_pfb.py
  src/azul/service/hca_response_v5.py
  test/service/data/pfb_manifest.results.json
Labels: sandbox, orange, 2 reviews, reindex

#3459 Fix: Integration test _assert_catalog_complete fails (#3267)
  test/integration_test.py
Labels: sandbox, orange, chain, 0 reviews

#3397 Limit PFB IDs to 254 or fewer characters (#3313)
  src/azul/service/avro_pfb.py
  test/service/data/pfb_manifest.results.json
  test/service/test_pfb.py
Labels: sandbox, orange, 4+ reviews

#3444 Fix: `register_sam.py` does not inspect sources (#3443)
  scripts/register_sam.py
Labels: sandbox, orange, chain, 0 reviews

#3460 Fix: Integration test doesnt always use the pruning seed (#3452)
  test/integration_test.py
Labels: sandbox, orange, chain, 0 reviews

#3464 Add newlines to body of /manifest/files responses (#3425)
  src/azul/service/manifest_controller.py
  test/service/test_manifest.py
Labels: sandbox, orange, 0 reviews

#3352 Fix: Summary endpoint's file count is inconsistent (#3318)
  src/azul/__init__.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/hca_response_v5.py
  src/azul/service/index_query_service.py
Labels: sandbox, orange, 2 reviews

#3471 Make dcp9 the default catalog on prod (#3406)
  deployments/prod/environment.py
Labels: orange, 0 reviews, no sandbox

#3437 Remove organismAgeValue term facet from service response (#2824)
  lambdas/service/openapi.json
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/transform.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/indexer/test_hca_indexer.py
  test/service/data/pfb_manifest.results.json
  test/service/test_response.py
Labels: sandbox, orange, 0 reviews, reindex

#3415 Enable API Gateway logging in CloudWatch (#3054)
  README.md
  terraform/api_gateway.tf.json.template.py
Labels: sandbox, orange, 1 review

#3467 Amend PR checklist with hand-off between author and operator (#3355)
  .github/pull_request_template.md
Labels: orange, no sandbox

#3470 Fix: Summary endpoint's file count is inconsistent (#3318)
  src/azul/__init__.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/hca_response_v5.py
  src/azul/service/index_query_service.py
Labels: sandbox, orange

#3450 Fix: Layer sharing hides deployment issues (#3330)
  scripts/stage_layer.py
  src/azul/__init__.py
  src/azul/lambda_layer.py
Labels: orange, 2 reviews
