Repository DataBiosphere/azul, pull requests merged in 2021-05, with the labels that each got.

#2827 Allow prefix to be specified per source (#2650)
  UPGRADING.rst
  deployments/dev/environment.py
  deployments/prod/environment.py
  deployments/sandbox/environment.py
  environment.py
  scripts/recan_bundle_tdr.py
  scripts/reindex.py
  src/azul/__init__.py
  src/azul/azulclient.py
  src/azul/indexer/__init__.py
  src/azul/indexer/document.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/terra.py
  test/indexer/test_indexer_controller.py
  test/service/test_repository_proxy.py
Labels: 4+ reviews, DCP demo, no demo, orange, sandbox, upgrade, urgent

#3007 Fix: Sporadic failures related to 'ConflictException' when running make deploy (#1951)
  scripts/prepare_lambda_deployment.py
  terraform/api_gateway.tf.json.template.py
Labels: 1 review, no demo, orange, sandbox

#3012 Fix: Test fails if AZUL_DRS_DOMAIN_NAME is not defined (#2846)
  test/service/test_manifest.py
Labels: 4+ reviews, orange, sandbox, urgent

#3037 [r] Index hca_prod_20201120_dcp2___20210504_dcp5 into dcp5 on prod (#3036)
  deployments/prod/environment.py
Labels: no demo, no sandbox, orange, reindex

#3003 Add extended features to CGM adapter (#3002)
  scripts/cgm_adapter.py
  scripts/sha256_gcs_blobs.py
Labels: dcp demo, no demo, orange, sandbox

#3030 Fix: FIXME references closed ticket (#2829)
  src/azul/service/elasticsearch_service.py
Labels: 1 review, orange, sandbox

#3050 [r] Index hca_dev_20201203__20210507 into dcp2 on dev (#3049)
  deployments/dev/environment.py
  deployments/sandbox/environment.py
Labels: orange, reindex, sandbox

#3064 Make dcp5 the default catalog on prod (#3045)
  deployments/prod/environment.py
Labels: no demo, no sandbox, orange

#2886 [R] Upgrade moto to 2.0.2 (#1718)
  attic/cart/test_cart_export_service.py
  attic/test/retorts.py
  requirements.dev.trans.txt
  requirements.dev.txt
  requirements.trans.txt
  requirements.txt
  src/azul/portal_service.py
  src/azul/service/storage_service.py
  test/azul_test_case.py
  test/health_check_test_case.py
  test/indexer/test_hca_indexer.py
  test/indexer/test_indexer_controller.py
  test/service/__init__.py
  test/service/test_collection_data_access.py
  test/service/test_drs.py
  test/service/test_manifest.py
  test/service/test_manifest_async.py
  test/service/test_portal_service.py
  test/service/test_query_shortener.py
  test/service/test_repository_proxy.py
  test/service/test_storage_service.py
  test/test_doctests.py
  test/version_table_test_case.py
Labels: 4+ reviews, no demo, orange, reqs

#3070 Index hca_dev_20201203___20210520_lattice into dcp2 on dev (#3061)
  deployments/dev/environment.py
  deployments/sandbox/environment.py
Labels: no demo, orange, reindex, sandbox, urgent

#3032 Index 'analysis_file.matrix_cell_count' (#2981)
  requirements.dev.trans.txt
  requirements.txt
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/aggregate.py
  src/azul/plugins/metadata/hca/transform.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/hca_response_v5.py
  test/indexer/data/223d54fb-46c9-5c30-9cae-6b8d5ea71b7e.manifest.json
  test/indexer/data/223d54fb-46c9-5c30-9cae-6b8d5ea71b7e.metadata.json
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/indexer/test_hca_indexer.py
  test/service/test_response.py
Labels: 1 review, orange, reindex, sandbox

#3057 Fix: Queue waiter waits a long time when the queues are empty (#3038)
  src/azul/queues.py
Labels: 1 review, orange, sandbox

#2999 Add OAuth 2.0 authentication and log access tokens (#2951)
  Makefile
  README.md
  UPGRADING.rst
  deployments/dev/environment.py
  deployments/sandbox/environment.py
  environment.py
  lambdas/indexer/app.py
  lambdas/service/app.py
  lambdas/service/vendor/static/oauth2-redirect.html
  lambdas/service/vendor/static/swagger-ui.html.template.mustache
  requirements.trans.txt
  requirements.txt
  src/azul/__init__.py
  src/azul/chalice.py
  src/azul/hmac.py
  src/azul/indexer/index_controller.py
  src/azul/terra.py
  test/service/test_app_logging.py
  test/service/test_repository_proxy.py
  test/service/test_request_logging.py
  test/test_app_logging.py
Labels: 4+ reviews, chain, orange, reqs, upgrade, urgent

#2914 Fix: Curl manifest expires after one hour (#2875)
  lambdas/service/app.py
  src/azul/chalice.py
  src/azul/service/manifest_controller.py
  src/azul/service/manifest_service.py
  test/app_test_case.py
  test/service/test_drs.py
  test/service/test_manifest.py
  test/service/test_manifest_async.py
  test/service/test_response.py
Labels: 3 reviews, chain, orange, sandbox, urgent

#3069 Canned TDR tables expand metadata JSON (#3067)
  scripts/recan_bundle_tdr.py
  test/indexer/data/1b6d8348-d6e9-406a-aa6a-7ee886e52bf9.tables.tdr.json
  test/indexer/test_tdr.py
Labels: 2 reviews, chain, orange, sandbox

#3065 Add facet for distinguishing matrix levels (#2860)
  src/azul/indexer/aggregate.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/aggregate.py
  src/azul/plugins/metadata/hca/transform.py
  src/azul/service/hca_response_v5.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/service/test_response.py
Labels: 0 reviews, orange, reindex, sandbox, urgent

#3081 Index hca_dev_20201203___20210524_lattice into dcp2 on dev (#3075)
  deployments/dev/environment.py
  deployments/sandbox/environment.py
Labels: no demo, orange, reindex, sandbox

#3086 Index hca_prod_20201120_dcp2___20210526_dcp6 into dcp6 on `prod` (#3085)
  deployments/prod/environment.py
Labels: 1 review, no demo, no sandbox, orange, reindex

#3082 Refactor multi-part manifest handling (#2778)
  environment.py
  src/azul/__init__.py
  src/azul/service/manifest_service.py
  src/azul/service/storage_service.py
  test/service/test_manifest.py
  test/service/test_storage_service.py
Labels: chain, no demo, orange, sandbox
