Repository DataBiosphere/azul, pull requests merged in 2021-06, with the labels that each got.

#3063 Disallow ambiguous version of transitive runtime requirements (#3062)
  README.md
  requirements.dev.trans.txt
  requirements.dev.txt
  requirements.trans.txt
  requirements.txt
  scripts/manage_requirements.py
Labels: 1 review, orange, reqs, sandbox

#3104 Move manifest object key from service to generator (#2778)
  src/azul/service/manifest_service.py
  test/service/test_manifest.py
Labels: no demo, orange, sandbox

#3091 Fix: Swagger UI is broken on prod (#3090, #3087)
  README.md
  deployments/prod/environment.py
Labels: 1 review, chain, no demo, no sandbox, orange

#3101 Fix: Extraction of matrix_cell_count is wrong (#3097)
  src/azul/plugins/metadata/hca/aggregate.py
  src/azul/plugins/metadata/hca/transform.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
Labels: 0 reviews, no demo, orange, reindex, sandbox

#3083 Fix: Compact manifest filename is non-human friendly (#3077)
  src/azul/service/manifest_service.py
  test/service/test_manifest.py
Labels: 2 reviews, orange, sandbox

#3058 Add project IDs to samples and files responses (#2993)
  src/azul/service/hca_response_v5.py
  test/service/test_repository_projects.py
  test/service/test_response.py
Labels: 0 reviews, orange, sandbox

#2052 Prototype Avro/PFB export for hand-off (#1430)
  lambdas/service/app.py
  requirements.dev.trans.txt
  requirements.trans.txt
  requirements.txt
  src/azul/indexer/document.py
  src/azul/service/avro_pfb.py
  src/azul/service/manifest_service.py
  test/integration_test.py
  test/service/data/pfb_manifest.results.json
  test/service/test_manifest.py
  test/service/test_pfb.py
Labels: 4+ reviews, orange, reqs, sandbox

#3119 Fix: FileAggregator._group_keys has incorrect type hint (#3108)
  src/azul/indexer/aggregate.py
  src/azul/plugins/metadata/hca/aggregate.py
Labels: 1 review, no demo, orange, sandbox

#2998 Index organically described CGMs (#2958)
  environment.py
  src/azul/__init__.py
  src/azul/plugins/metadata/hca/transform.py
  src/azul/plugins/repository/canned/__init__.py
  test/indexer/test_hca_indexer.py
Labels: 3 reviews, orange, reindex, reqs, sandbox

#3128 Retire velocity script and move it to attic (#3051)
  attic/.github/workflows/velocity.yml
  attic/scripts/velocity.py
  environment.py
  test/test_doctests.py
Labels: 1 review, no demo, no sandbox, orange

#3149 Disable `terra.pfb` manifest integration test (#3138)
  test/integration_test.py
Labels: 2 reviews, no demo, orange, sandbox

#3143 Make dcp6 the default catalog on `prod` (#3139)
  deployments/prod/environment.py
Labels: 1 review, no demo, no sandbox, orange

#3130 Fix: Full manifest generation with no filters times out after 900s (#2778)
  attic/src/azul/requests.py
  requirements.dev.trans.txt
  requirements.dev.txt
  requirements.trans.txt
  requirements.txt
  src/azul/drs.py
  src/azul/http.py
  src/azul/service/async_manifest_service.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/manifest_controller.py
  src/azul/service/manifest_service.py
  src/azul/service/storage_service.py
  src/azul/terra.py
  terraform/s3.tf.json.template.py
  terraform/step_function.tf.json.template.py
  test/app_test_case.py
  test/azul_test_case.py
  test/integration_test.py
  test/service/test_manifest.py
  test/service/test_manifest_async.py
  test/service/test_request_builder.py
Labels: orange, reqs, sandbox

#2995 Fix: Manifest service hard-codes file URLs (#2922)
  src/azul/chalice.py
  src/azul/service/manifest_controller.py
  src/azul/service/manifest_service.py
  test/service/test_manifest.py
Labels: 4+ reviews, chain, no demo, orange, sandbox

#2709 Add subgraph stitching to TDR unit tests (#2397)
  test/indexer/data/4426adc5-b3c5-5aab-ab86-51d8ce44dfbe.result.tdr.json
  test/indexer/data/4426adc5-b3c5-5aab-ab86-51d8ce44dfbe.tables.tdr.json
  test/indexer/test_tdr.py
Labels: 4+ reviews, no demo, orange, sandbox

#3047 [r] Rename SourceName to SourceSpec (#2843)
  deployments/sandbox/environment.py
  scripts/can_bundle.py
  scripts/recan_bundle_tdr.py
  scripts/register_sam.py
  src/azul/azulclient.py
  src/azul/indexer/__init__.py
  src/azul/indexer/document.py
  src/azul/indexer/index_controller.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/repository/canned/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/service/hca_response_v5.py
  src/azul/terra.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/indexer/test_indexer_controller.py
  test/indexer/test_tdr.py
  test/service/test_manifest.py
  test/service/test_response.py
Labels: 4+ reviews, orange, reindex, sandbox

#3144 Add contentDescription facet (#3116)
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/service/hca_response_v5.py
  test/service/test_response.py
Labels: 0 reviews, orange, sandbox

#3010 Contribution guideline on reverting commits
  CONTRIBUTING.rst
Labels: no demo, no sandbox, orange

#3163 [r] Index hca_prod_20210616_lungmap___20210616_lm1 into `lungmap` on `prod` (#3150)
  deployments/prod/environment.py
Labels: 1 review, no demo, no sandbox, orange, reindex

#3169 [R] Fix: Make terraform sometimes fails with ResourcesNotFoundException (#1672)
  requirements.dev.trans.txt
  requirements.dev.txt
Labels: 0 reviews, orange, reqs, sandbox

#3165 Remove support for DCP/1's Grafana instance and health checks (#3053)
  attic/scripts/manage_health_checks.py
  attic/scripts/update_grafana.py
  attic/terraform/grafana_dashboard.tf.json.template.py
  environment.py
  src/azul/__init__.py
  terraform/Makefile
Labels: 0 reviews, orange, sandbox
