Repository DataBiosphere/azul, pull requests merged in 2021-07, with the labels that each got.

#3194 Fix: `make sam` fails due to ambiguous response from TDR (#3193)
  src/azul/terra.py
Labels: 1 review, no demo, orange

#3198 [r] Add dcp7 on prod (#3197)
  deployments/prod/environment.py
Labels: 0 reviews, no demo, no sandbox, orange, reindex

#3178 [r] Index hca_dev_20210621_managedaccess_4298b4de92f34cbbbbfe5bc11b8c2422__20210622 into dcp2 on `dev` (#3158)
  deployments/dev/environment.py
Labels: 0 reviews, no demo, orange, reindex, sandbox

#3207 Merge branch 'prod' into develop
  deployments/prod/environment.py
Labels: no demo, no sandbox, orange

#3023 List and cache repository sources (#2953)
  lambdas/indexer/app.py
  lambdas/service/app.py
  scripts/can_bundle.py
  scripts/register_sam.py
  src/azul/__init__.py
  src/azul/auth.py
  src/azul/azulclient.py
  src/azul/chalice.py
  src/azul/hmac.py
  src/azul/indexer/__init__.py
  src/azul/indexer/index_controller.py
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/canned/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/service/lambda_iam_policy.py
  src/azul/service/repository_controller.py
  src/azul/service/source_cache_service.py
  src/azul/terra.py
  terraform/dynamo.tf.json.template.py
  test/dynamodb_test_case.py
  test/indexer/test_indexer_controller.py
  test/indexer/test_tdr.py
  test/integration_test.py
  test/service/test_app_logging.py
  test/service/test_repository_proxy.py
  test/service/test_source_cache.py
  test/version_table_test_case.py
Labels: 4+ reviews, chain, orange, sandbox

#3173 Fix: Missed SourceSpec renamings in azul.plugins.repository.canned (#2843)
  src/azul/plugins/repository/canned/__init__.py
Labels: 2 reviews, no demo, no sandbox, orange

#3179 Add contentDescription field to fileTypeSummaries (#3170)
  src/azul/plugins/metadata/hca/aggregate.py
  src/azul/service/hca_response_v5.py
  test/indexer/data/fce68057-b0f0-5d11-b9a7-30e8fa3259a8.manifest.json
  test/indexer/data/fce68057-b0f0-5d11-b9a7-30e8fa3259a8.metadata.json
  test/service/test_response.py
Labels: 1 review, chain, orange

#3167 Fix: terra.pfb manifest IT fails on prod (#3138)
  src/azul/service/avro_pfb.py
  test/integration_test.py
  test/service/data/pfb_manifest.results.json
  test/service/test_manifest.py
Labels: 2 reviews, orange, sandbox

#3011 Consolidate base URL composition in tests (#3008)
  test/app_test_case.py
  test/health_check_test_case.py
  test/indexer/test_hca_indexer.py
  test/service/test_app_logging.py
  test/service/test_drs.py
  test/service/test_manifest.py
  test/service/test_manifest_async.py
  test/service/test_pagination.py
  test/service/test_query_shortener.py
  test/service/test_repository_projects.py
  test/service/test_repository_proxy.py
  test/service/test_repository_specimen.py
  test/service/test_request_validation.py
  test/service/test_response.py
Labels: 3 reviews, chain, orange, sandbox

#3211 Fix: Index hca_dev_20210621_managedaccess_4298b4de92f34cbbbbfe5bc11b8c2422__20210622 into dcp2 on `sandbox` (#3158)
  deployments/sandbox/environment.py
Labels: no demo, orange, reindex sandbox, sandbox

#3206 Fix: A sequence_file with submitter file_source fails requirement check (#3202)
  src/azul/plugins/metadata/hca/transform.py
Labels: 1 review, orange, sandbox

#3217 [r] Index hca_prod_20201120_dcp2___20210707_dcp7 into dcp7 on prod (#3209)
  deployments/prod/environment.py
Labels: 0 reviews, no demo, no sandbox, orange, reindex

#3208 Fix: Full manifest without filters is excessively slow (#2778)
  Makefile
  requirements.dev.trans.txt
  requirements.dev.txt
  requirements.trans.txt
  requirements.txt
  src/azul/__init__.py
  src/azul/caching.py
  src/azul/health.py
  src/azul/service/manifest_service.py
  test/azul_test_case.py
  test/service/test_manifest_async.py
Labels: orange, reqs, sandbox

#3216 Fix: Stitching trips over mixed `links` schema versions (#3203)
  src/azul/plugins/repository/tdr/__init__.py
  test/indexer/data/4426adc5-b3c5-5aab-ab86-51d8ce44dfbe.result.tdr.json
Labels: 1 review, orange

#3228 Fix: 'NoneType' object has no attribute 'generate_signed_url' (#3226)
  src/azul/drs.py
  src/azul/plugins/repository/tdr/__init__.py
Labels: 1 review, orange, sandbox, urgent

#3225 Fix: AttributeError for matrix_cell_count in SequenceFile (#3224)
  lambdas/.wheels/fastavro-1.3.1-cp38-cp38-manylinux2014_x86_64.whl
  lambdas/.wheels/grpcio-1.34.1-cp38-cp38-manylinux2014_x86_64.whl
  lambdas/layer/Makefile
  requirements.trans.txt
  requirements.txt
  src/azul/plugins/metadata/hca/transform.py
  test/indexer/data/02e69c25-71e2-48ca-a87b-e256938c6a98.manifest.json
  test/indexer/data/02e69c25-71e2-48ca-a87b-e256938c6a98.metadata.json
  test/indexer/data/f0731ab4-6b80-4eed-97c9-4984de81a47c.metadata.json
  test/indexer/test_hca_indexer.py
  test/service/test_response.py
Labels: orange, reindex, reqs, urgent

#3218 Fix: OSError writing contributions with parallel_bulk in `prod` (dcp7) (#3200)
  src/azul/indexer/index_service.py
Labels: 2 reviews, orange, sandbox, urgent

#3059 Determine set of publicly accessible snapshots via TDR (#2978)
  README.md
  UPGRADING.rst
  environment.py
  lambdas/service/app.py
  scripts/provision_credentials.py
  scripts/register_sam.py
  src/azul/__init__.py
  src/azul/deployment.py
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/service/repository_controller.py
  src/azul/terra.py
  terraform/authentication.tf.json.template.py
  test/integration_test.py
  test/service/test_repository_proxy.py
Labels: 2 reviews, chain, orange, upgrade, urgent

#3103 Implicit filter on sources (snapshots) to which current user has access (#2954)
  lambdas/service/app.py
  src/azul/plugins/repository/canned/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/service/index_query_service.py
  test/indexer/__init__.py
  test/indexer/test_tdr.py
  test/service/__init__.py
  test/service/test_manifest.py
  test/service/test_pagination.py
  test/service/test_repository_specimen.py
  test/service/test_request_validation.py
  test/service/test_response.py
Labels: 0 reviews, orange

#3239 Fix: A project in dcp7 catalog causes AssertionError (#3238)
  src/azul/plugins/metadata/hca/contributor_matrices.py
Labels: orange

#3242 Merge branch 'prod' to develop
  src/azul/plugins/metadata/hca/contributor_matrices.py
Labels: no sandbox, orange

#3107 Improve resilience of BigQuery slot management (#3013)
  scripts/reindex.py
  scripts/sell_unused_slots.py
  src/azul/bigquery_reservation.py
Labels: 2 reviews, orange, sandbox

#2997 Track generated OpenAPI definition as JSON in the source tree (#2987)
  .github/workflows/ci.yml
  .gitlab-ci.yml
  Makefile
  README.md
  lambdas/service/openapi.json
  scripts/.gitignore
  scripts/generate_openapi_document.py
  src/azul/health.py
Labels: 4+ reviews, chain, orange, sandbox

#3102 Explain warning-related test failures in README (#3060)
  README.md
Labels: 4+ reviews, no demo, no sandbox, orange

#3205 Refactor flake8 plugin (#3204)
  .flake8/azul_flake8.py
  CONTRIBUTING.rst
  test/test_azul_flake8.py
Labels: 2 reviews, chain, no demo, orange, sandbox

#3191 Switch when label is added in operator checklist
  .github/pull_request_template.md
Labels: 0 reviews, no demo, no sandbox, orange

#3236 Fix: Lower deployments unnecessarily share an Google OAuth 2.0 client (#3080)
  README.md
  UPGRADING.rst
  environment.py
Labels: 1 review, no demo, no sandbox, orange, upgrade

#3210 Add test of donor fields from subgraph without donor entity (#3160)
  test/indexer/data/0722b70c-6778-423d-8fe9-869e2a515d35.manifest.json
  test/indexer/data/0722b70c-6778-423d-8fe9-869e2a515d35.metadata.json
  test/indexer/data/1fd499c5-f397-4bff-9af0-eb42c37d5fbe.manifest.json
  test/indexer/data/1fd499c5-f397-4bff-9af0-eb42c37d5fbe.metadata.json
  test/indexer/test_hca_indexer.py
Labels: 3 reviews, no demo, orange, sandbox

#3254 Fix: `load_script` raises `ModuleNotFoundError: No module named 'args'` (#3249)
  scripts/can_bundle.py
  scripts/reindex.py
  scripts/sell_unused_slots.py
  src/azul/args.py
Labels: 0 reviews, chain, orange, sandbox

#3263 Make dcp7 the default catalog on `prod` (#3243)
  deployments/prod/environment.py
Labels: 0 reviews, no demo, no sandbox, orange

#3092 Fix: Swagger UI breaks if AZUL_GOOGLE_OAUTH2_CLIENT_ID is not set (#3088)
  deployments/prod/environment.py
  lambdas/service/app.py
  lambdas/service/vendor/static/swagger-ui.html.template.mustache
  src/azul/__init__.py
Labels: 1 review, orange, sandbox

#3268 Provision separate OAuth 2.0 client for sandbox deployment (#3080)
  deployments/sandbox/environment.py
Labels: 0 reviews, orange

#3189 Fix flake8 import ambiguity in scripts (#3156)
  .flake8/azul_flake8.py
  src/azul/indexer/__init__.py
Labels: 0 reviews, no demo, no sandbox, orange

#3279 Fix formatting in UPGRADING.rst (#3146)
  UPGRADING.rst
Labels: no demo, no sandbox, orange
