Repository DataBiosphere/azul, pull requests merged in 2021-02, with the labels that each got.

#2640 Clarify stitching log message (#2507)
  src/azul/plugins/repository/tdr/__init__.py
Labels: 0 reviews, orange, reindex, sandbox

#2712 Add file source to hits in service response (#2705)
  src/azul/plugins/metadata/hca/contributor_matrices.py
  src/azul/plugins/metadata/hca/transform.py
  src/azul/service/hca_response_v5.py
  src/azul/service/index_query_service.py
  test/indexer/test_hca_indexer.py
  test/service/test_repository_projects.py
  test/service/test_repository_specimen.py
  test/service/test_response.py
Labels: 0 reviews, orange, reindex, sandbox

#2559 Protect against invalid or harmful file paths in `curl` manifest (#2398)
  src/azul/service/manifest_service.py
Labels: 4+ reviews, orange, sandbox

#2638 Refactor links parsing (#2560)
  src/azul/plugins/repository/tdr/__init__.py
Labels: 2 reviews, orange

#2754 Change RepositoryPlugin.source to .sources (#2747)
  src/azul/azulclient.py
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/service/catalog_controller.py
  test/service/test_response.py
Labels: chain, no demo, orange, sandbox

#2756 Change AZUL_TDR_SOURCE to AZUL_TDR_SOURCES (#2755)
  UPGRADING.rst
  deployments/dev/environment.py
  deployments/prod/environment.py
  deployments/sandbox/environment.py
  environment.py
  scripts/register_sam.py
  src/azul/__init__.py
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/portal_service.py
  test/service/test_tdr.py
Labels: no demo, orange, sandbox, upgrade

#2760 Add `source` argument to RepositoryPlugin.list_bundles and .fetch_bundle (#2749)
  scripts/args.py
  scripts/can_bundle.py
  scripts/can_dss_bundle.py
  scripts/can_tdr_bundle.py
  scripts/kibana_proxy.py
  scripts/reindex.py
  scripts/subscribe.py
  src/azul/azulclient.py
  src/azul/indexer/index_controller.py
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr/__init__.py
  test/indexer/test_indexer_controller.py
  test/integration_test.py
  test/service/test_tdr.py
Labels: orange, reindex, sandbox

#2542 Allow total_estimated_cells to be None (#2271)
  src/azul/indexer/aggregate.py
  src/azul/plugins/metadata/hca/aggregate.py
  src/azul/service/manifest_service.py
  test/indexer/test_hca_indexer.py
  test/service/test_manifest.py
  test/service/test_response.py
Labels: 4+ reviews, orange, reindex, sandbox

#2411 Fix: Unit tests for TDR plugin should use canned bundle verbatim (#2374)
  scripts/can_dss_bundle.py
  scripts/recan_bundle_tdr.py
  src/azul/json.py
  src/azul/plugins/repository/tdr/__init__.py
  test/indexer/__init__.py
  test/indexer/data/1b6d8348-d6e9-406a-aa6a-7ee886e52bf9.result.tdr.json
  test/indexer/data/1b6d8348-d6e9-406a-aa6a-7ee886e52bf9.tables.tdr.json
  test/indexer/test_tdr.py
  test/service/test_tdr.py
Labels: 3 reviews, chain, orange, sandbox

#2746 Create a tool to validate a staging area (#2742)
  scripts/validate_staging_area.py
Labels: 0 reviews, no demo, no sandbox, orange

#2674 Verify snapshot Google project using TDR API (#2504)
  scripts/register_sam.py
  src/azul/strings.py
  src/azul/terra.py
Labels: 4+ reviews, chain, orange, sandbox

#2788 Fix: Bundle notifications don't include the source of the bundle (#2787)
  scripts/can_bundle.py
  scripts/recan_bundle_tdr.py
  src/azul/azulclient.py
  src/azul/indexer/__init__.py
  src/azul/indexer/document.py
  src/azul/indexer/index_controller.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/hca/transform.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr/__init__.py
  test/indexer/__init__.py
  test/indexer/test_hca_indexer.py
  test/indexer/test_indexer_controller.py
  test/indexer/test_projects.py
  test/indexer/test_tdr.py
  test/integration_test.py
  test/service/__init__.py
  test/service/test_manifest.py
  test/service/test_response.py
Labels: chain, no demo, orange, reindex, sandbox

#2782 Create 'lungmap' and 'it3lungmap' catalogs (#2537)
  deployments/dev/environment.py
  deployments/sandbox/environment.py
  test/integration_test.py
Labels: 0 reviews, orange, reindex, sandbox

#2775 [r] Index snaptest{2,3} into dcp2ebi on dev (#2774)
  deployments/dev/environment.py
  deployments/sandbox/environment.py
  environment
Labels: no demo, orange, reindex

#2551 Curl manifest for zarray file format does not include auxiliary files (#2538)
  src/azul/service/manifest_service.py
  test/service/test_manifest.py
Labels: 4+ reviews, orange

#2441 Explicitly couple names of handler and lambda function (#1848)
  lambdas/indexer/.chalice/config.json.template.py
  lambdas/indexer/app.py
  lambdas/service/.chalice/config.json.template.py
  lambdas/service/app.py
  src/azul/__init__.py
  src/azul/chalice.py
  src/azul/service/async_manifest_service.py
  src/azul/service/lambda_iam_policy.py
  terraform/step_function.tf.json.template.py
  test/service/test_async_manifest_service.py
Labels: 4+ reviews, no demo, orange

#2762 Make data file URL injection more generic (#2545)
  src/azul/plugins/metadata/hca/contributor_matrices.py
  src/azul/service/hca_response_v5.py
  src/azul/service/index_query_service.py
  test/service/test_response.py
Labels: 0 reviews, orange

#2720 Remove references to DRS, DSS, and CLI from Swagger page (#2671)
  README.md
  attic/scripts/apidev.py
  attic/scripts/apidev_static/swagger-editor.html
  lambdas/service/app.py
  src/azul/chalice.py
  src/azul/vendored/README.md
  src/azul/vendored/frozendict/__init__.py
  test/test_openapi.py
Labels: 2 reviews, orange

#2745 [r] Fix missing organ value of CGM files (#2735)
  src/azul/plugins/metadata/hca/transform.py
  test/service/test_response.py
Labels: 0 reviews, orange, reindex

#2703 Fix: ES returns too many headers during bundle deletion (#2455)
  src/azul/indexer/document.py
  src/azul/indexer/index_service.py
  src/azul/service/cart_item_manager.py
  src/azul/service/elasticsearch_service.py
  test/azul_test_case.py
  test/docker_container_test_case.py
  test/indexer/test_hca_indexer.py
Labels: 2 reviews, orange, reindex

#2794 Fix order of index notifications for reindex script (#2085)
  scripts/reindex.py
Labels: 0 reviews, orange

#2801 Move staging area validation tool to separate repository (#2772)
  scripts/validate_staging_area.py
Labels: no demo, no sandbox, orange

#2809 Track source name and ID in bundle FQIDs (#2625)
  CONTRIBUTING.rst
  scripts/can_bundle.py
  scripts/envhook.py
  scripts/export_environment.py
  scripts/recan_bundle_tdr.py
  scripts/register_sam.py
  src/azul/azulclient.py
  src/azul/indexer/__init__.py
  src/azul/indexer/document.py
  src/azul/indexer/index_controller.py
  src/azul/modules.py
  src/azul/objects.py
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/service/catalog_controller.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/hca_response_v5.py
  src/azul/service/manifest_service.py
  src/azul/terra.py
  terraform/api_gateway.tf.json.template.py
  test/indexer/__init__.py
  test/indexer/test_hca_indexer.py
  test/indexer/test_indexer_controller.py
  test/indexer/test_tdr.py
  test/integration_test.py
  test/service/test_pagination.py
  test/test_app_logging.py
  test/test_doctests.py
  test/test_tagging.py
Labels: no demo, orange, partial, reindex sandbox

#2812 Cache TDRClient instances per plugin class and thread (#2625)
  src/azul/__init__.py
  src/azul/caching.py
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/strings.py
  src/azul/terra.py
  test/test_doctests.py
Labels: chain, no demo, orange, partial, reindex sandbox, sandbox

#2820 [r] Revert catalog dcp2 back to snapshot hca_dev_20201203___20201210 in dev (#2819)
  deployments/dev/environment.py
  deployments/sandbox/environment.py
Labels: no demo, orange, reindex, sandbox

#2800 Add file size to project matrices (#2795)
  src/azul/plugins/metadata/hca/contributor_matrices.py
  src/azul/plugins/metadata/hca/transform.py
  test/indexer/test_hca_indexer.py
  test/service/test_response.py
Labels: 0 reviews, orange, reindex

#2808 Reactivate test_multipart_upload_ok_with_n_parts (#1424)
  test/service/test_storage_service.py
Labels: 0 reviews, no demo, orange

#2816 Fix: TDRSourceName should inherit SourceName (#2815)
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/terra.py
Labels: no demo, orange

#2838 Fix: curl manifest download trashes file on response error (#2833)
  src/azul/service/manifest_service.py
  test/service/test_manifest.py
Labels: 0 reviews, orange

#2780 Fix: test_fetch_bundle fails in `prod` deployment (#2776)
  scripts/recan_bundle_tdr.py
  test/indexer/data/1b6d8348-d6e9-406a-aa6a-7ee886e52bf9.result.tdr.json
  test/indexer/data/1b6d8348-d6e9-406a-aa6a-7ee886e52bf9.tables.tdr.json
  test/indexer/test_tdr.py
Labels: 4+ reviews, orange
