Repository DataBiosphere/azul, pull requests merged in 2022-06, with the labels that each got.

#4232 Update GitLab to 14.10.4 (#4014)
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, no sandbox

#4106 Do not populate download URLs for phantom files (#3956)
  src/azul/plugins/metadata/hca/service/contributor_matrices.py
  src/azul/plugins/metadata/hca/service/response.py
  src/azul/service/repository_service.py
  test/indexer/data/1b6d8348-d6e9-406a-aa6a-7ee886e52bf9.result.tdr.json
  test/indexer/data/1b6d8348-d6e9-406a-aa6a-7ee886e52bf9.tables.tdr.json
  test/service/test_response.py
Labels: sandbox, orange, 2 reviews

#4235 Fix: TDR timeouts don't raise the correct exception (#4229)
  src/azul/terra.py
Labels: orange, base, 0 reviews

#3672 Scan GitLab instances with clamav every week (#3614)
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, 1 review, no sandbox

#4236 Fix: Service should return 503 response when Terra client times out (#3968)
  src/azul/chalice.py
  src/azul/service/source_controller.py
Labels: sandbox, orange, 0 reviews

#4238 Update GitLab to 15.0.2 (#4014)
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, no sandbox

#4237 Log DRS response from TDR (#4185)
  src/azul/drs.py
Labels: sandbox, orange, partial, 0 reviews

#4242 Make dcp16 the default catalog on `prod` (#4226)
  deployments/prod/environment.py
Labels: orange, base, 0 reviews, no sandbox

#4230 Index updated project into `lm2` on `prod` (#4225)
  deployments/prod/environment.py
Labels: orange, 0 reviews, no sandbox

#4241 Index `dcp17` in `prod` (#4240)
  deployments/prod/environment.py
Labels: orange, 0 reviews, reindex, no sandbox, chained

#4245 Promotion 2022-06-10 (#4244)
  deployments/prod/environment.py
  src/azul/chalice.py
  src/azul/drs.py
  src/azul/logging.py
  src/azul/plugins/metadata/hca/service/contributor_matrices.py
  src/azul/plugins/metadata/hca/service/response.py
  src/azul/service/repository_service.py
  src/azul/service/source_controller.py
  src/azul/terra.py
  terraform/gitlab/Dockerfile
  terraform/gitlab/gitlab.tf.json.template.py
  test/indexer/data/1b6d8348-d6e9-406a-aa6a-7ee886e52bf9.result.tdr.json
  test/indexer/data/1b6d8348-d6e9-406a-aa6a-7ee886e52bf9.tables.tdr.json
  test/service/test_response.py
Labels: orange, reindex, no sandbox

#4246 Hotfix: Add support for for phantom files (#3956)
  test/service/test_response.py
Labels: orange, no sandbox, hotfix

#4112 Fix: GitLab IT test_indexing fails with stalled index in sandbox (#3835)
  src/azul/queues.py
Labels: sandbox, orange, 2 reviews

#4252 Remove 1 project from `dcp17` in `prod` (#4251)
  deployments/prod/environment.py
Labels: orange, 0 reviews, reindex, no sandbox

#4068 Disallow '||' joiners in metadata (#3911)
  src/azul/__init__.py
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/service/manifest_service.py
  test/indexer/test_tdr.py
Labels: sandbox, orange, 4+ reviews

#4266 Improve logging of tallies (#4265)
  src/azul/indexer/index_controller.py
Labels: sandbox, orange, base

#4268 Increase SQS message retention to 1 week (#4267)
  terraform/sqs.tf.json.template.py
Labels: sandbox, orange, 0 reviews

#4269 Fix: Typos in README section on VPN access to GitLab (#4260)
  README.md
  src/azul/indexer/index_service.py
Labels: sandbox, orange

#4270 Update GitLab to 15.1.0 (#4014)
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, no sandbox

#4273 Make dcp17 the default catalog on `prod` (#4259)
  deployments/prod/environment.py
Labels: orange, 0 reviews, no sandbox

#4278 Promotion 2022-06-29 (#4277)
  .github/PULL_REQUEST_TEMPLATE/backport.md
  .github/PULL_REQUEST_TEMPLATE/hotfix.md
  .github/PULL_REQUEST_TEMPLATE/promotion.md
  .github/pull_request_template.md
  README.md
  deployments/prod/environment.py
  requirements.dev.trans.txt
  requirements.trans.txt
  requirements.txt
  src/azul/indexer/index_controller.py
  src/azul/indexer/index_service.py
  terraform/gitlab/gitlab.tf.json.template.py
  terraform/sqs.tf.json.template.py
Labels: orange, 0 reviews, no sandbox
