Repository DataBiosphere/azul, pull requests merged in 2022-07, with the labels that each got.

#4282 Index updated project into `lm2` on `dev` (#4279)
  deployments/dev/environment.py
  deployments/sandbox/environment.py
Labels: orange, 0 reviews, reindex

#4287 [r] Index dcp18 in prod (#4283)
  deployments/prod/environment.py
Labels: orange, 0 reviews, reindex, no sandbox

#4284 Update GitLab to 15.1.1 (#4014)
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, 0 reviews, no sandbox

#4281 Fix: Transient SignatureDoesNotMatch error from GCS during IT (#4185)
  src/azul/drs.py
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/service/repository_controller.py
  test/integration_test.py
  test/service/test_repository_proxy.py
Labels: sandbox, orange, 2 reviews

#4294 Derive set of available indices from current catalog (#4262)
  lambdas/service/app.py
  lambdas/service/openapi.json
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/service/catalog_controller.py
  test/service/test_request_validation.py
  test/service/test_response.py
Labels: sandbox, orange, 0 reviews

#4293 Disable test_concurrent_portal_db_crud, add FIXME (#4285)
  test/integration_test.py
Labels: sandbox, orange, no demo, partial, 0 reviews

#4144 Optionally put API Gateways in GitLab VPC (#4001, #4168)
  README.md
  UPGRADING.rst
  environment.py
  lambdas/indexer/.chalice/config.json.template.py
  lambdas/service/.chalice/config.json.template.py
  lambdas/service/app.py
  lambdas/service/vendor/resources/static/swagger-ui.html.template.mustache
  scripts/prepare_lambda_deployment.py
  scripts/reset_lambda_role.py
  src/azul/__init__.py
  src/azul/chalice.py
  src/azul/indexer/lambda_iam_policy.py
  src/azul/lambdas.py
  src/azul/service/lambda_iam_policy.py
  src/azul/terraform.py
  terraform/Makefile
  terraform/api_gateway.tf.json.template.py
  terraform/gitlab/gitlab.tf.json.template.py
  terraform/modules.tf.json.template.py
Labels: sandbox, orange, 3 reviews, upgrade

#4193 Verify source spec at indexing time (#3827)
  src/azul/azulclient.py
  src/azul/indexer/index_service.py
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/canned/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/terra.py
Labels: orange, 1 review

#4305 Update GitLab to 15.1.2 (#4014)
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, no sandbox

#4317 Spec for filters argument should be driven by field types (#2254)
  lambdas/service/app.py
  lambdas/service/openapi.json
  src/azul/aws_service_model.py
  src/azul/enums.py
  src/azul/indexer/__init__.py
  src/azul/indexer/document.py
  src/azul/indexer/index_controller.py
  src/azul/openapi/schema.py
  src/azul/plugins/metadata/hca/indexer/aggregate.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  src/azul/service/avro_pfb.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/manifest_controller.py
  src/azul/types.py
  test/indexer/__init__.py
  test/indexer/test_hca_indexer.py
  test/service/__init__.py
  test/service/data/pfb_manifest.results.json
  test/service/data/pfb_manifest.schema.json
  test/service/test_response.py
Labels: sandbox, orange

#4321 Promotions 2022-07-20 (#4320)
  README.md
  UPGRADING.rst
  environment.py
  lambdas/indexer/.chalice/config.json.template.py
  lambdas/service/.chalice/config.json.template.py
  lambdas/service/app.py
  lambdas/service/openapi.json
  lambdas/service/vendor/resources/static/swagger-ui.html.template.mustache
  requirements.trans.txt
  requirements.txt
  scripts/prepare_lambda_deployment.py
  scripts/reset_lambda_role.py
  src/azul/__init__.py
  src/azul/azulclient.py
  src/azul/chalice.py
  src/azul/indexer/index_service.py
  src/azul/indexer/lambda_iam_policy.py
  src/azul/lambdas.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/repository/canned/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/service/avro_pfb.py
  src/azul/service/catalog_controller.py
  src/azul/service/lambda_iam_policy.py
  src/azul/terra.py
  src/azul/terraform.py
  terraform/Makefile
  terraform/api_gateway.tf.json.template.py
  terraform/gitlab/gitlab.tf.json.template.py
  terraform/gitlab/vpn/Makefile
  terraform/modules.tf.json.template.py
  test/integration_test.py
  test/service/data/pfb_manifest.results.json
  test/service/test_request_validation.py
  test/service/test_response.py
Labels: orange, no sandbox, upgrade

#4331 Fix: Service rejects organism age ranges of integers (#4330)
  requirements.dev.trans.txt
  requirements.trans.txt
  src/azul/indexer/document.py
  src/azul/openapi/schema.py
  test/service/test_response.py
  test/test_doctests.py
Labels: sandbox, orange, reqs

#4329 Update GitLab to 15.1.3 (#4014)
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, no sandbox

#4296 Fix: ES exception when indexing mix of DSS and TDR canned bundles (#3971)
  requirements.dev.trans.txt
  test/indexer/data/17a3d288-01a0-464a-9599-7375fda3353d.manifest.json
  test/indexer/data/1b6d8348-d6e9-406a-aa6a-7ee886e52bf9.manifest.json
  test/indexer/data/2a87dc5c-0c3c-4d91-a348-5d784ab48b92.manifest.json
  test/indexer/data/3db604da-940e-49b1-9bcc-25699a55b295.manifest.json
  test/indexer/data/3f8176ff-61a7-4504-a57c-fc70f38d5b13.manifest.json
  test/indexer/data/411cd8d5-5990-43cd-84cc-6c7796b8a76d.manifest.json
  test/indexer/data/412cd8d5-5990-43cd-84cc-6c7796b8a76d.manifest.json
  test/indexer/data/4afbb0ea-81ad-49dc-9b12-9f77f4f50be8.manifest.json
  test/indexer/data/56a338fe-7554-4b5d-96a2-7df127a7640b.manifest.json
  test/indexer/data/587d74b4-1075-4bbf-b96a-4d1ede0481b2.manifest.json
  test/indexer/data/8543d32f-4c01-48d5-a79f-1c5439659da3.manifest.json
  test/indexer/data/8c90d4fe-9a5d-4e3d-ada2-0414b666b880.manifest.json
  test/indexer/data/94f2ba52-30c8-4de0-a78e-f95a3f8deb9c.manifest.json
  test/indexer/data/97f0cc83-f0ac-417a-8a29-221c77debde8.manifest.json
  test/indexer/data/9dec1bd6-ced8-448a-8e45-1fc7846d8995.manifest.json
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.manifest.json
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.results.json
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-04T11:33:44.698028Z.manifest.json
  test/indexer/data/b0850e79-5544-49fe-b54d-e29b9fc3f61f.manifest.json
  test/indexer/data/b2216048-7eaa-45f4-8077-5a3fb4204953.manifest.json
  test/indexer/data/b7fc737e-9b7b-4800-8977-fe7c94e131df.manifest.json
  test/indexer/data/c94a43f9-257f-4cd0-b2fe-eaf6d5d37d18.manifest.json
  test/indexer/data/cfab8304-dc9f-439e-af29-f8eb75b0729d.manifest.json
  test/indexer/data/d0e17014-9a58-4763-9e66-59894efbdaa8.manifest.json
  test/indexer/data/d5e01f9d-615f-4153-8a56-f2317d7d9ce8.manifest.json
  test/indexer/data/dcccb551-4766-4210-966c-f9ee25d19190.manifest.json
  test/indexer/data/e0ae8cfa-2b51-4419-9cde-34df44c6458a.manifest.json
  test/indexer/data/e2c3054e-9fba-4d7a-b85b-a2220d16da73.manifest.json
  test/indexer/data/f0731ab4-6b80-4eed-97c9-4984de81a47c.manifest.json
  test/indexer/data/f79257a7-dfc6-46d6-ae00-ba4b25313c10.manifest.json
  test/indexer/data/fa5be5eb-2d64-49f5-8ed8-bd627ac9bc7a.manifest.json
  test/indexer/data/ffac201f-4b1c-4455-bd58-19c1a9e863b4.manifest.json
  test/indexer/test_hca_indexer.py
  test/service/data/pfb_manifest.results.json
  test/service/test_drs.py
  test/service/test_manifest.py
  test/service/test_response.py
Labels: sandbox, orange, 4+ reviews

#4327 Use one WAF for both indexer and service (#4303)
  terraform/api_gateway.tf.json.template.py
Labels: sandbox, orange, 0 reviews

#4328 Split TDR plugin into tdr_hca and ABC (#4224)
  UPGRADING.rst
  deployments/dev/environment.py
  deployments/prod/environment.py
  deployments/sandbox/environment.py
  scripts/generate_openapi_document.py
  scripts/post_deploy.py
  scripts/recan_bundle_tdr.py
  scripts/reindex.py
  src/azul/__init__.py
  src/azul/indexer/document.py
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/tdr.py
  src/azul/plugins/repository/tdr_hca/__init__.py
  src/azul/strings.py
  src/azul/terra.py
  test/indexer/test_tdr.py
  test/service/test_repository_proxy.py
  test/service/test_response.py
  test/test_doctests.py
Labels: sandbox, orange, partial, base, 0 reviews, upgrade

#4337 Update GitLab 15.2.0 (#4014)
  OPERATOR.rst
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, 0 reviews, no sandbox

#4340 Make dcp18 the default catalog on `prod` (#4315)
  deployments/prod/environment.py
Labels: orange, 0 reviews, no sandbox

#4318 Workaround: IT on prod timeout waiting for queues (#4299)
  OPERATOR.rst
Labels: sandbox, orange, partial, 1 review

#4272 Manage CloudTrail trail in 'shared' TF component (#4197)
  README.md
  UPGRADING.rst
  deployments/dev.shared/environment.py
  deployments/dev/environment.py
  deployments/prod.shared/environment.py
  deployments/prod/environment.py
  environment.py
  src/azul/__init__.py
  src/azul/deployment.py
  src/azul/terraform.py
  terraform/gitlab/Makefile
  terraform/providers.tf.json.template.py
  terraform/shared/.gitignore
  terraform/shared/Makefile
  terraform/shared/backend.tf.json.template.py
  terraform/shared/common.tf.json.template.py
  terraform/shared/providers.tf.json.template.py
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, orange, 4+ reviews, upgrade
