Repository DataBiosphere/azul, pull requests merged in 2022-02, with the labels that each got.

#3797 Fix: Logs by imported test modules don't show on CI (#3780)
  src/azul/es.py
  src/azul/indexer/index_service.py
  src/azul/logging.py
  test/app_test_case.py
  test/azul_test_case.py
  test/docker_container_test_case.py
  test/es_test_case.py
  test/indexer/test_hca_indexer.py
  test/indexer/test_indexer_controller.py
  test/integration_test.py
  test/service/test_drs.py
  test/service/test_manifest.py
  test/service/test_pagination.py
  test/service/test_repository_proxy.py
Labels: sandbox, orange

#3794 Fix: `scripts/kibana_proxy.py` fails to connect to ES (#3787)
  README.md
  scripts/kibana_proxy.py
Labels: orange, 1 review, no sandbox

#3802 Fix: Can't easily override AZUL_DEBUG for all deployments locally (#3796)
  UPGRADING.rst
  scripts/export_environment.py
Labels: sandbox, orange, upgrade

#3611 Enable GitLab ALB request logging (#3604)
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, 4+ reviews, no sandbox

#3800 Fix: prod2 IT subgraph partitioning fails to locate bundles (#3767)
  deployments/prod2/environment.py
Labels: orange, 1 review, chain, no sandbox

#3816 Hotfix: (2) Managed access IT fails on prod (#3810)
  test/integration_test.py
Labels: orange, 0 reviews, no sandbox

#3806 Fix: Unit tests fail due to ES TransportErrors (#3795)
  test/es_test_case.py
Labels: sandbox, orange, 1 review

#3819 [r] Index hca_prod_20201120_dcp2___20220201_dcp13 into dcp13 on prod (#3814)
  deployments/prod/environment.py
Labels: orange, 0 reviews, reindex, no sandbox

#3754 Fix: PFB exports missing DRS links (#3689)
  src/azul/json.py
  src/azul/service/avro_pfb.py
  src/azul/service/manifest_service.py
  src/azul/types.py
  test/service/data/pfb_manifest.results.json
  test/service/test_manifest.py
Labels: sandbox, orange, 4+ reviews

#3824 Promotion 2022/02/02 (#3815)
  README.md
  UPGRADING.rst
  deployments/prod/environment.py
  deployments/prod2/environment.py
  requirements.trans.txt
  requirements.txt
  scripts/export_environment.py
  scripts/kibana_proxy.py
  src/azul/__init__.py
  src/azul/es.py
  src/azul/indexer/index_service.py
  src/azul/json.py
  src/azul/logging.py
  src/azul/plugins/metadata/hca/transform.py
  src/azul/service/avro_pfb.py
  src/azul/service/manifest_service.py
  src/azul/types.py
  terraform/gitlab/gitlab.tf.json.template.py
  test/app_test_case.py
  test/azul_test_case.py
  test/docker_container_test_case.py
  test/es_test_case.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/indexer/test_hca_indexer.py
  test/indexer/test_indexer_controller.py
  test/integration_test.py
  test/service/data/pfb_manifest.results.json
  test/service/test_drs.py
  test/service/test_manifest.py
  test/service/test_pagination.py
  test/service/test_repository_proxy.py
  test/service/test_response.py
Labels: orange, 0 reviews, reindex, no sandbox, reqs, upgrade

#3822 Fix: Timeout aggregating batch of tallies for Tabula Muris (#3660)
  src/azul/indexer/index_controller.py
  src/azul/iterators.py
  test/indexer/test_indexer_controller.py
Labels: sandbox, orange

#3829 Fix: SerializationError during aggregation (#3812)
  src/azul/__init__.py
  src/azul/indexer/document.py
  src/azul/indexer/index_service.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/aggregate.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/indexer/test_hca_indexer.py
  test/service/test_request_builder.py
Labels: sandbox, orange, reindex

#3783 Index more dcp2 projects to `prod2` (#3752)
  deployments/prod2/environment.py
Labels: orange, 2 reviews, reindex, no sandbox

#3821 Update GitLab to 14.7.1
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, no demo, no sandbox

#3825 Backport 67c29770 and a1dca360 (#3810, PR #3811, PR #3816)
  test/integration_test.py
Labels: orange, no demo

#3682 Fix: Unable to filter on `accessions` (#3505)
  lambdas/service/app.py
  lambdas/service/openapi.json
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/transform.py
  src/azul/service/avro_pfb.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/repository_controller.py
  test/integration_test.py
  test/service/__init__.py
  test/service/test_response.py
Labels: sandbox, orange, 4+ reviews, reindex

#3840 Index hca_prod_20201120_dcp2___20220209_dcp13 into dcp13 on prod (#3838)
  deployments/prod/environment.py
Labels: orange, reindex, no sandbox

#3842 Promotion 2022/02/10 (#3841)
  OPERATOR.rst
  deployments/prod/environment.py
  deployments/prod2/environment.py
  lambdas/service/app.py
  lambdas/service/openapi.json
  scripts/kibana_proxy.py
  src/azul/__init__.py
  src/azul/indexer/document.py
  src/azul/indexer/index_controller.py
  src/azul/indexer/index_service.py
  src/azul/iterators.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/aggregate.py
  src/azul/plugins/metadata/hca/transform.py
  src/azul/service/avro_pfb.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/repository_controller.py
  terraform/gitlab/gitlab.tf.json.template.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/indexer/test_hca_indexer.py
  test/indexer/test_indexer_controller.py
  test/integration_test.py
  test/service/__init__.py
  test/service/test_request_builder.py
  test/service/test_response.py
Labels: orange, reindex, no sandbox

#3818 Fix: Debugging the managed access IT is extremely tedious (#3785)
  test/integration_test.py
Labels: sandbox, orange, 0 reviews

#3801 Fix: Integration tests lists all bundles twice (#3784)
  test/integration_test.py
Labels: sandbox, orange, 0 reviews

#3863 Fix: `make create` fails on fully populated indices (#3862)
  src/azul/indexer/index_service.py
  src/azul/json_freeze.py
  test/indexer/test_hca_indexer.py
  test/indexer/test_notifications.py
Labels: sandbox, orange

#3860 Fix: Transient failure while running IT in sandbox deployment (#3834)
  test/integration_test.py
Labels: sandbox, orange, chain, 0 reviews

#3861 Fix: Transient Fatal Python error fails test job in GitLab (#3859)
  scripts/export_environment.py
Labels: sandbox, orange

#3583 Fix: Integration test does not cover remote reindexing (#2789)
  src/azul/azulclient.py
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/tdr/__init__.py
  test/integration_test.py
Labels: sandbox, orange, 2 reviews

#3867 Index dcp13 in prod2 (#3843)
  deployments/prod2/environment.py
Labels: orange, 2 reviews, reindex, no sandbox

#3876 Promotion 2022/02/16 (#3875)
  OPERATOR.rst
  deployments/prod2/environment.py
  environment.py
  scripts/export_environment.py
  scripts/sell_unused_slots.py
  src/azul/__init__.py
  src/azul/azulclient.py
  src/azul/bigquery_reservation.py
  src/azul/indexer/index_service.py
  src/azul/json_freeze.py
  src/azul/lambdas.py
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/tdr/__init__.py
  test/indexer/test_hca_indexer.py
  test/indexer/test_notifications.py
  test/integration_test.py
Labels: orange, 0 reviews, no sandbox

#3884 Fix: IT in GitLab prod fails due to AssertionError (#3880)
  test/integration_test.py
Labels: orange, no sandbox

#3871 Mention firecloud-cgl in onboarding docs (#3866)
  .github/ISSUE_TEMPLATE/onboarding.md
Labels: orange, no sandbox

#3864 Document commit title tags for hotfixes (#3769)
  .github/pull_request_template.md
  CONTRIBUTING.rst
Labels: orange, 1 review, no sandbox

#3676 Sort by combination of cell suspension and project cell counts (#3581)
  lambdas/service/openapi.json
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/aggregate.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/service/test_response.py
Labels: sandbox, orange, 4+ reviews, reindex

#3882 Remove workaround for missing creation_time in BQ Reservation (#3360)
  requirements.dev.trans.txt
  requirements.trans.txt
  requirements.txt
  src/azul/bigquery_reservation.py
Labels: sandbox, orange, 0 reviews, reqs

#3883 Remove `hits.projects.{foo}Accessions` from response (#3334)
  lambdas/service/openapi.json
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/transform.py
  src/azul/service/hca_response_v5.py
  test/azul_test_case.py
  test/indexer/data/4426adc5-b3c5-5aab-ab86-51d8ce44dfbe.result.tdr.json
  test/indexer/data/4426adc5-b3c5-5aab-ab86-51d8ce44dfbe.tables.tdr.json
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/indexer/test_hca_indexer.py
  test/service/data/pfb_manifest.results.json
  test/service/test_repository_projects.py
  test/service/test_response.py
Labels: sandbox, orange, 0 reviews, reindex

#3865 In operator manual document need for promotion issues (#3775)
  OPERATOR.rst
Labels: orange, 1 review, no sandbox

#3694 Enforce user authentication on curl download (#2956)
  src/azul/auth.py
  src/azul/service/manifest_controller.py
  src/azul/service/manifest_service.py
  test/integration_test.py
  test/service/test_manifest.py
  test/service/test_manifest_async.py
  test/test_doctests.py
Labels: orange, 3 reviews, chain
