Repository DataBiosphere/azul, pull requests merged in 2022-08, with the labels that each got.

#4347 Update GitLab to 15.2.1 (#4014)
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, no sandbox

#4155 Free up storage space on GitLab every week (#3616)
  README.md
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, 2 reviews, no sandbox

#4286 Create issue template for off-boarding (#4206)
  .github/ISSUE_TEMPLATE/offboarding.md
Labels: orange, 2 reviews, no sandbox

#4336 Derive supported manifest formats from current catalog (#4335)
  lambdas/service/app.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/service/manifest_controller.py
  src/azul/service/manifest_service.py
  test/integration_test.py
  test/service/test_manifest.py
  test/service/test_manifest_async.py
  test/service/test_request_validation.py
Labels: sandbox, orange, 1 review, base

#4372 Hotfix: index `dcp19` in `prod` (#4366)
  deployments/prod/environment.py
Labels: orange, 0 reviews, reindex, no sandbox, hotfix

#4351 Create CloudWatch alarm for number of 5xx errors (#4010)
  terraform/cloudwatch.tf.json.template.py
Labels: sandbox, orange, 2 reviews

#4376 Hotfix: Verifying source at indexing time overloads TDR (#3827)
  src/azul/azulclient.py
  src/azul/indexer/index_service.py
Labels: orange, partial, no sandbox, hotfix

#4377 Backport: 277b0187 (#3827, PR #4376) and fbaa1d97 (#4366, PR #4372)
  deployments/prod/environment.py
  src/azul/azulclient.py
  src/azul/indexer/index_service.py
Labels: orange, no sandbox

#4391 Fix: Can't deploy a private API (#4375)
  terraform/api_gateway.tf.json.template.py
Labels: sandbox, orange

#4359 Fix: Health checks hard-code HCA entity types (#4358)
  lambdas/indexer/app.py
  lambdas/service/app.py
  src/azul/chalice.py
  src/azul/health.py
  src/azul/indexer/index_controller.py
  src/azul/service/__init__.py
  src/azul/service/catalog_controller.py
  src/azul/service/repository_controller.py
  src/azul/service/source_controller.py
  test/health_check_test_case.py
  test/indexer/test_indexer_controller.py
  test/service/test_drs.py
Labels: sandbox, orange, base, 0 reviews

#4383 Remove work around for empty file_format (#4099)
  src/azul/plugins/metadata/hca/service/response.py
Labels: sandbox, orange, 0 reviews

#4413 Fix: Compact manifest without filters fails to generate (#4261)
  src/azul/service/manifest_service.py
  test/service/__init__.py
  test/service/test_manifest.py
  test/service/test_manifest_async.py
  test/service/test_pagination.py
Labels: sandbox, orange

#4409 Make dcp19 the default catalog on `prod` (#4379)
  deployments/prod/environment.py
Labels: orange, 0 reviews, no sandbox

#4380 Reduce GitLab update churn (#4345)
  OPERATOR.rst
Labels: orange, 0 reviews, no sandbox

#4407 Create issue template for off-boarding (#4206)
  .github/ISSUE_TEMPLATE/offboarding.md
Labels: orange, 0 reviews, no sandbox

#4393 Fix: Cannot deploy after GCP role was deleted (#4390)
  src/azul/__init__.py
  terraform/authentication.tf.json.template.py
Labels: sandbox, orange, 0 reviews

#4412 Fix: Downloads from /repository/files/{file_id} time out with 504 & 503 (#4384)
  src/azul/service/manifest_service.py
  test/service/test_manifest.py
Labels: sandbox, orange, 0 reviews
