Repository DataBiosphere/azul, pull requests merged in 2022-11, with the labels that each got.

#4725 Fix: Elasticsearch domains should be in a VPC (#4688)
  UPGRADING.rst
  lambdas/indexer/.chalice/config.json.template.py
  lambdas/service/.chalice/config.json.template.py
  scripts/kibana_proxy.py
  scripts/prepare_lambda_deployment.py
  src/azul/chalice.py
  src/azul/deployment.py
  src/azul/indexer/lambda_iam_policy.py
  src/azul/service/lambda_iam_policy.py
  terraform/api_gateway.tf.json.template.py
  terraform/elasticsearch.tf.json.template.py
  terraform/gitlab/gitlab.tf.json.template.py
  terraform/modules.tf.json.template.py
Labels: sandbox, orange, 1 review, reindex, upgrade

#4763 Hotfix: Missing treatment_protocol in prod snapshot (#4736)
  .github/PULL_REQUEST_TEMPLATE/hotfix.md
  deployments/prod/environment.py
Labels: orange, partial, 0 reviews, no sandbox, hotfix

#4760 Promotion 2022-11-23 (#4748)
  UPGRADING.rst
  src/azul/azulclient.py
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/canned/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr.py
  src/azul/terra.py
  terraform/gitlab/gitlab.tf.json.template.py
  terraform/s3.tf.json.template.py
  terraform/shared/shared.tf.json.template.py
Labels: orange, 0 reviews, no sandbox, upgrade

#4749 [R] Upgrade setuptools to 65.5.1 (PR #4738, PR #4739, PR #4743, PR #4750)
  bin/wheels/runtime/googleapis_common_protos-1.57.0-py2.py3-none-any.whl
  requirements.all.txt
  requirements.dev.trans.txt
  requirements.pip.txt
  requirements.trans.txt
Labels: sandbox, orange, 1 review, reqs

#4767 Update GitLab to 15.6.0 (#4014)
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, no sandbox

#4766 Backport: 4dc1651 (#4736, PR #4763)
  .github/PULL_REQUEST_TEMPLATE/hotfix.md
  deployments/prod/environment.py
Labels: orange, 0 reviews, no sandbox

#4740 Fix: S3 Block Public Access setting should be enabled at the bucket-level (#4691)
  scripts/migrate_terraform_state.py
  src/azul/terraform.py
  terraform/.terraform.lock.hcl
  terraform/Makefile
  terraform/gitlab/.terraform.lock.hcl
  terraform/s3.tf.json.template.py
  terraform/shared/.terraform.lock.hcl
  terraform/shared/Makefile
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, orange, partial, 1 review

#4742 Modify offboarding issue template (#4206, #4669)
  .github/ISSUE_TEMPLATE/offboarding.md
Labels: orange, 0 reviews, no sandbox
