Repository DataBiosphere/azul, pull requests merged in 2022-01, with the labels that each got.

#3720 Mention `drop!` hunk comments in contribution guide
  CONTRIBUTING.rst
Labels: orange, no sandbox

#3685 Fix: Unexpected bundles appearing in manifest (#3567)
  src/azul/service/manifest_service.py
  test/integration_test.py
  test/service/test_manifest.py
Labels: sandbox, orange, 2 reviews, chain

#3706 Fix: next and previous links should not include the implicit source filter (#3701)
  src/azul/service/__init__.py
  src/azul/service/drs_controller.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/manifest_service.py
  src/azul/service/repository_controller.py
  src/azul/service/repository_service.py
  src/azul/service/source_controller.py
  test/service/test_manifest.py
  test/service/test_pagination.py
Labels: sandbox, orange, chain, 0 reviews

#3577 Fix: Summary of donors, specimens and cells are 0 for `DCP/2 Analysis` (#3281)
  src/azul/plugins/metadata/hca/transform.py
  test/indexer/test_hca_indexer.py
Labels: sandbox, orange, 2 reviews, reindex

#3729 Update GitLab to 14.6.1
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, no demo, no sandbox

#3723 Make dcp12 the default catalog on prod (#3717)
  deployments/prod/environment.py
Labels: orange, 1 review, no sandbox

#3735 Update GitLab to 14.6.2
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, no demo, no sandbox

#3734 Fix: Failure to create BDBag manifest for Tabula Muris project (#2442)
  lambdas/service/.chalice/config.json.template.py
Labels: sandbox, orange

#3738 Fix: previous link broken with page size of one (#3732)
  src/azul/service/elasticsearch_service.py
Labels: sandbox, orange, chain

#3733 Index additional dcp1 projects to prod2 (#3724)
  deployments/prod2/environment.py
Labels: orange, reindex, no sandbox

#3750 Backport: 5b8ab619 (#3717, PR #3723)
  deployments/prod/environment.py
Labels: orange, no demo, no sandbox

#3751 Backport: a30c224f (#3724, PR #3733)
  deployments/prod2/environment.py
Labels: orange, no sandbox

#3726 Fix: Projects endpoint is slow (#3248)
  src/azul/indexer/index_service.py
Labels: sandbox, orange, 1 review, reindex

#3670 Fix: `test_snapshot_listing` IT fails with less than 6 snapshots (#3662)
  test/integration_test.py
Labels: sandbox, orange, 0 reviews

#3765 Give `prod2` its own ES instance (#3757)
  deployments/prod2/environment.py
Labels: orange, 0 reviews, no sandbox

#3753 Fix: Problems with backporting instructions in operator manual (#3746)
  OPERATOR.rst
Labels: orange, 0 reviews, no sandbox

#3730 Allow for sorting by submission and update date, whichever is more recent (#3679)
  lambdas/service/openapi.json
  src/azul/indexer/aggregate.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/aggregate.py
  src/azul/plugins/metadata/hca/transform.py
  src/azul/service/avro_pfb.py
  src/azul/service/hca_response_v5.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/indexer/test_hca_indexer.py
  test/service/data/pfb_manifest.results.json
  test/service/test_repository_projects.py
  test/service/test_response.py
Labels: orange, 0 reviews, reindex

#3651 Add summary cell counts based on projects index (#3521)
  lambdas/service/openapi.json
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/hca_response_v5.py
  src/azul/service/repository_service.py
  test/indexer/data/4f2fc365-9f97-51ca-bbfe-fe30cefc333d.manifest.json
  test/indexer/data/4f2fc365-9f97-51ca-bbfe-fe30cefc333d.metadata.json
  test/indexer/data/80baee6e-00a5-4fdc-bfe3-d339ff8a7178.manifest.json
  test/indexer/data/80baee6e-00a5-4fdc-bfe3-d339ff8a7178.metadata.json
  test/indexer/data/ddb8f660-1160-4f6c-9ce4-c25664ac62c9.manifest.json
  test/indexer/data/ddb8f660-1160-4f6c-9ce4-c25664ac62c9.metadata.json
  test/indexer/data/f71165c6-4f59-5284-b498-b9a29dccf413.manifest.json
  test/indexer/data/f71165c6-4f59-5284-b498-b9a29dccf413.metadata.json
  test/service/test_response.py
Labels: sandbox, orange, 3 reviews, chain

#3755 Add ajandu@ucsc.edu's SSH key to GitLab `dev`
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, no demo, 0 reviews, no sandbox

#3781 Add summary cell counts based on projects index, follow-up (#3521)
  lambdas/service/openapi.json
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/hca_response_v5.py
  src/azul/service/repository_service.py
  test/indexer/data/2c7d06b8-658e-4c51-9de4-a768322f84c5.manifest.json
  test/indexer/data/2c7d06b8-658e-4c51-9de4-a768322f84c5.metadata.json
  test/indexer/data/f71165c6-4f59-5284-b498-b9a29dccf413.manifest.json
  test/indexer/data/f71165c6-4f59-5284-b498-b9a29dccf413.metadata.json
  test/service/test_response.py
Labels: sandbox, orange

#3771 Upgrade to Elasticsearch 7.10 (#3006)
  UPGRADING.rst
  deployments/dev/environment.py
  deployments/prod/environment.py
  deployments/prod2/environment.py
  deployments/sandbox/environment.py
  environment.py
  requirements.dev.trans.txt
  requirements.trans.txt
  requirements.txt
  src/azul/indexer/document.py
  src/azul/indexer/index_service.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/transform.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/manifest_service.py
  terraform/elasticsearch.tf.json.template.py
  test/azul_test_case.py
  test/es_test_case.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/indexer/test_hca_indexer.py
  test/indexer/test_projects.py
  test/service/test_pagination.py
  test/service/test_response.py
Labels: sandbox, orange, reindex, reqs, upgrade

#3395 Fix: Implicit filter on sourceId collides with explicit one (#3372)
  lambdas/service/app.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/service/__init__.py
  src/azul/service/drs_controller.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/manifest_controller.py
  src/azul/service/manifest_service.py
  src/azul/service/repository_controller.py
  src/azul/service/repository_service.py
  test/integration_test.py
  test/service/test_manifest_async.py
Labels: sandbox, orange, 2 reviews

#3773 Remove uneeded authentication from BDBag IT (#3302)
  test/integration_test.py
Labels: orange, no demo, 0 reviews

#3789 [u r R] Promotions/2022-01-26 (#3788)
  UPGRADING.rst
  deployments/dev/environment.py
  deployments/prod/environment.py
  deployments/prod2/environment.py
  deployments/sandbox/environment.py
  environment.py
  lambdas/service/app.py
  lambdas/service/openapi.json
  requirements.dev.trans.txt
  requirements.trans.txt
  requirements.txt
  src/azul/indexer/document.py
  src/azul/indexer/index_service.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/transform.py
  src/azul/service/__init__.py
  src/azul/service/drs_controller.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/hca_response_v5.py
  src/azul/service/manifest_controller.py
  src/azul/service/manifest_service.py
  src/azul/service/repository_controller.py
  src/azul/service/repository_service.py
  terraform/elasticsearch.tf.json.template.py
  terraform/gitlab/gitlab.tf.json.template.py
  test/azul_test_case.py
  test/es_test_case.py
  test/indexer/data/2c7d06b8-658e-4c51-9de4-a768322f84c5.manifest.json
  test/indexer/data/2c7d06b8-658e-4c51-9de4-a768322f84c5.metadata.json
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/indexer/data/f71165c6-4f59-5284-b498-b9a29dccf413.manifest.json
  test/indexer/data/f71165c6-4f59-5284-b498-b9a29dccf413.metadata.json
  test/indexer/test_hca_indexer.py
  test/indexer/test_projects.py
  test/integration_test.py
  test/service/test_manifest_async.py
  test/service/test_pagination.py
  test/service/test_response.py
Labels: orange, reindex, no sandbox, upgrade

#3776 Update GitLab to 14.7.0
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, no demo, 0 reviews, no sandbox

#3512 Add project.publications.official_hca_publication and doi to response (#3502)
  requirements.trans.txt
  requirements.txt
  src/azul/plugins/metadata/hca/transform.py
  test/es_test_case.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T113344.698028Z.results.json
  test/indexer/test_hca_indexer.py
  test/service/test_response.py
Labels: orange, 1 review, reindex, reqs

#3779 Fix: Managed access IT references outdated catalog name (#3772)
  src/azul/__init__.py
  test/integration_test.py
Labels: sandbox, orange, 0 reviews
