Repository DataBiosphere/azul, pull requests merged in 2022-05, with the labels that each got.

#4140 Plugin-ify the service response population (#3817)
  src/azul/indexer/document.py
  src/azul/indexer/document_service.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  src/azul/plugins/metadata/hca/service/aggregation.py
  src/azul/plugins/repository/canned/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/manifest_service.py
  src/azul/service/repository_controller.py
  src/azul/service/repository_service.py
  test/indexer/__init__.py
  test/integration_test.py
  test/service/test_manifest.py
  test/service/test_request_builder.py
  test/service/test_response.py
Labels: sandbox, orange, partial

#4161 Add achave11's SSH key to GitLab dev (#4157)
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, chain, 0 reviews, no sandbox

#4163 Update GitLab to 14.9.4 (#4014)
  .github/PULL_REQUEST_TEMPLATE/backport.md
  .github/PULL_REQUEST_TEMPLATE/gitlab.md
  .github/PULL_REQUEST_TEMPLATE/hotfix.md
  .github/pull_request_template.md
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, no demo, no sandbox

#4166 Update GitLab to 14.10.1 (#4014)
  OPERATOR.rst
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, no demo, 0 reviews, no sandbox

#4070 Create CloudWatch metric filter for number of 5xx errors (#4009)
  attic/terraform/route53_health_check.tf.json.template.py
  deployments/dev/environment.py
  deployments/prod/environment.py
  environment.py
  terraform/cloudwatch.tf.json.template.py
Labels: sandbox, orange, 2 reviews

#3466 Use `furl` instead of `str` for URLs where possible (#3398)
  lambdas/service/app.py
  lambdas/service/openapi.json
  scripts/cgm_adapter.py
  scripts/generate_openapi_document.py
  scripts/locust/service.py
  scripts/manifest_404.py
  scripts/recan_bundle_tdr.py
  src/azul/__init__.py
  src/azul/azulclient.py
  src/azul/chalice.py
  src/azul/drs.py
  src/azul/health.py
  src/azul/oauth2.py
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/service/__init__.py
  src/azul/service/drs_controller.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/manifest_controller.py
  src/azul/service/manifest_service.py
  src/azul/service/repository_controller.py
  src/azul/service/repository_service.py
  src/azul/terra.py
  test/app_test_case.py
  test/health_check_test_case.py
  test/indexer/test_tdr.py
  test/integration_test.py
  test/service/test_drs.py
  test/service/test_pagination.py
  test/service/test_repository_proxy.py
  test/test_openapi.py
Labels: sandbox, orange, 4+ reviews

#4153 Upgrade Chalice to 1.27.0 (#4146)
  common.mk
  lambdas/service/app.py
  requirements.dev.trans.txt
  requirements.dev.txt
  requirements.trans.txt
  scripts/prepare_lambda_deployment.py
  src/azul/service/repository_controller.py
  test/health_check_test_case.py
  test/integration_test.py
  test/service/test_manifest_async.py
  test/service/test_request_validation.py
Labels: orange, 2 reviews, base, reqs

#4113 Rename `chain` label to `base`; add `chained` label for chained PRs (#4105)
  .github/PULL_REQUEST_TEMPLATE/gitlab.md
  .github/pull_request_template.md
  CONTRIBUTING.rst
  OPERATOR.rst
Labels: orange, 3 reviews, no sandbox

#4162 Fix: IT assertion for snapshot listing with unreg SA conflates 401 and 500 (#4086)
  test/integration_test.py
Labels: sandbox, orange, 2 reviews

#4181 Promotion 2022-05-11 (#4180)
  .github/PULL_REQUEST_TEMPLATE/gitlab.md
  .github/pull_request_template.md
  CONTRIBUTING.rst
  OPERATOR.rst
  attic/terraform/route53_health_check.tf.json.template.py
  common.mk
  deployments/dev/environment.py
  deployments/prod/environment.py
  environment.py
  lambdas/service/app.py
  lambdas/service/openapi.json
  requirements.dev.trans.txt
  requirements.dev.txt
  requirements.trans.txt
  scripts/cgm_adapter.py
  scripts/generate_openapi_document.py
  scripts/locust/service.py
  scripts/manifest_404.py
  scripts/prepare_lambda_deployment.py
  scripts/recan_bundle_tdr.py
  src/azul/__init__.py
  src/azul/azulclient.py
  src/azul/chalice.py
  src/azul/drs.py
  src/azul/health.py
  src/azul/oauth2.py
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr/__init__.py
  src/azul/service/__init__.py
  src/azul/service/drs_controller.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/manifest_controller.py
  src/azul/service/manifest_service.py
  src/azul/service/repository_controller.py
  src/azul/service/repository_service.py
  src/azul/terra.py
  terraform/cloudwatch.tf.json.template.py
  test/app_test_case.py
  test/health_check_test_case.py
  test/indexer/test_tdr.py
  test/integration_test.py
  test/service/test_drs.py
  test/service/test_manifest_async.py
  test/service/test_pagination.py
  test/service/test_repository_proxy.py
  test/service/test_request_validation.py
  test/test_openapi.py
Labels: orange, no sandbox

#4147 5xx errors from Azul should point to the root cause (#4065)
  src/azul/terra.py
Labels: sandbox, orange, 4+ reviews

#4164 CloudWatch logging of GitLab VPN connections (#4027)
  terraform/gitlab/gitlab.tf.json.template.py
Labels: sandbox, orange, 1 review

#4169 Create CloudWatch alarm for number of 5xx errors (#4010)
  scripts/rename_resources.py
  terraform/cloudwatch.tf.json.template.py
Labels: sandbox, orange, base, 0 reviews

#4149 Cover indexing with TDR plugin in test_response (#4145)
  scripts/recan_bundle_tdr.py
  test/azul_test_case.py
  test/indexer/data/1b6d8348-d6e9-406a-aa6a-7ee886e52bf9.result.tdr.json
  test/indexer/data/1b6d8348-d6e9-406a-aa6a-7ee886e52bf9.tables.tdr.json
  test/indexer/test_tdr.py
  test/service/__init__.py
  test/service/test_repository_proxy.py
  test/service/test_request_validation.py
  test/service/test_response.py
  test/test_doctests.py
Labels: sandbox, orange, 1 review, base

#4084 Put Azul behind AWS WAF (#4000)
  scripts/prepare_lambda_deployment.py
  terraform/api_gateway.tf.json.template.py
  terraform/gitlab/gitlab.tf.json.template.py
Labels: sandbox, orange, 4+ reviews

#4213 Index `dcp16` in `prod` (#4208)
  deployments/prod/environment.py
Labels: orange, 0 reviews, reindex, no sandbox

#4217 Promotion 2022-05-25 (#4216)
  deployments/prod/environment.py
  scripts/prepare_lambda_deployment.py
  src/azul/plugins/metadata/hca/indexer/aggregate.py
  terraform/api_gateway.tf.json.template.py
  terraform/gitlab/gitlab.tf.json.template.py
  test/indexer/data/fa5be5eb-2d64-49f5-8ed8-bd627ac9bc7a.metadata.json
  test/service/test_response.py
Labels: orange, 0 reviews, reindex, no sandbox, upgrade

#4220 Backport a593e166 (#4186, #4067)
  src/azul/terra.py
Labels: sandbox, orange, port

#4222 Update RancherOS to 1.5.8 and Docker to 19.03.15 (#4221)
  terraform/gitlab/Dockerfile
  terraform/gitlab/gitlab.tf.json.template.py
Labels: no sandbox
