Repository DataBiosphere/azul, pull requests merged in 2022-12, with the labels that each got.

#4765 Fix: AnVIL indexer doesn't follow downstream links from files to files (#4761)
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/anvil/service/response.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  test/indexer/data/3fdc952d-7eec-a8d9-be70-876aa4377a53.results.json
Labels: sandbox, orange, 1 review, base, reindex

#4735 Host Swagger UI code internally (#4685)
  lambdas/service/app.py
  lambdas/service/vendor/resources/static/swagger-ui-bundle.js
  lambdas/service/vendor/resources/static/swagger-ui-standalone-preset.js
  lambdas/service/vendor/resources/static/swagger-ui.css
  lambdas/service/vendor/resources/static/swagger-ui.html.template.mustache
Labels: sandbox, orange, 1 review

#4789 Fix: `make clean` deletes too many files on Ubuntu (#4785)
  Makefile
  requirements.all.txt
  requirements.dev.trans.txt
Labels: sandbox, orange, reqs

#4781 Update GitLab to 15.6.1 (#4014)
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, no sandbox

#4628 Fix: Order of contributors in project metadata is not preserved (#4364)
  src/azul/collections.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  src/humancellatlas/data/metadata/api.py
  test/indexer/__init__.py
  test/indexer/test_hca_indexer.py
  test/service/__init__.py
  test/service/test_response.py
Labels: sandbox, orange, 3 reviews, reindex

#4498 Eliminate personal service accounts (#4424)
  .github/ISSUE_TEMPLATE/offboarding.md
  README.md
  UPGRADING.rst
  deployments/anvilbox/environment.py
  deployments/dev/.example.environment.local.py
  deployments/prod/.example.environment.local.py
  deployments/sandbox/.example.environment.local.py
  deployments/sandbox/environment.py
  environment
  environment.py
  scripts/provision_credentials.py
  src/azul/__init__.py
Labels: sandbox, orange, 2 reviews, upgrade

#4741 Update to AnVIL schema v4 (#4617)
  deployments/anvilbox/environment.py
  deployments/anvildev/environment.py
  scripts/can_bundle.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/anvil/service/response.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  test/indexer/data/3fdc952d-7eec-a8d9-be70-876aa4377a53.manifest.json
  test/indexer/data/3fdc952d-7eec-a8d9-be70-876aa4377a53.metadata.json
  test/indexer/data/3fdc952d-7eec-a8d9-be70-876aa4377a53.result.tdr.json
  test/indexer/data/3fdc952d-7eec-a8d9-be70-876aa4377a53.results.json
  test/indexer/data/9b78f049-83fc-a99b-83bc-8d40e34265cd.result.tdr.json
  test/indexer/data/9b78f049-83fc-a99b-83bc-8d40e34265cd.results.json
  test/indexer/test_anvil.py
  test/test_doctests.py
Labels: sandbox, orange, 3 reviews, reindex

#4800 Use Terraform to configure API Gateway access logs in CloudWatch (#3412, #4795)
  attic/scripts/log_api_gateway.py
  src/azul/terraform.py
  terraform/api_gateway.tf.json.template.py
Labels: sandbox, orange

#4801 Fix: RuntimeError in MP upload tests (#4678)
  src/azul/service/manifest_service.py
  src/azul/service/storage_service.py
  test/service/test_storage_service.py
Labels: sandbox, orange

#4799 Enable sending of CloudTrail events to CloudWatch logs (#4196)
  UPGRADING.rst
  src/azul/__init__.py
  terraform/api_gateway.tf.json.template.py
  terraform/elasticsearch.tf.json.template.py
  terraform/gitlab/gitlab.tf.json.template.py
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, orange, 1 review, base, upgrade

#4815 Disable monitoring for `dev` (#4807)
  deployments/anvildev/environment.py
  deployments/dev/environment.py
Labels: orange, partial, base, 0 reviews, no sandbox

#4817 Fix: _select, _deauth and _preauth emit envhook warnings (#4813)
  Makefile
  README.md
  bin/wheels/runtime/certifi-2022.9.24-py3-none-any.whl
  bin/wheels/runtime/googleapis_common_protos-1.56.4-py2.py3-none-any.whl
  bin/wheels/runtime/packaging-21.3-py3-none-any.whl
  bin/wheels/runtime/protobuf-4.21.10-cp37-abi3-manylinux2014_x86_64.whl
  bin/wheels/runtime/pyparsing-3.0.9-py3-none-any.whl
  environment
  requirements.all.txt
  requirements.dev.trans.txt
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, orange, reqs

#4806 Create support role to manage incidents with AWS support (#4793)
  UPGRADING.rst
  deployments/dev.shared/environment.py
  environment.py
  src/azul/__init__.py
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, orange, reqs, upgrade

#4811 Remove left-overs from #4334 and #4752 (#4744, #4769, #4772)
  attic/scripts/migrate_terraform_state.py
  scripts/rename_resources.py
  terraform/Makefile
  terraform/shared/Makefile
Labels: sandbox, orange

#4821 Hotfix: Index `dcp23` in `prod` (#4818)
  deployments/prod/environment.py
Labels: orange, no sandbox, hotfix

#4803 Ensure IAM password policies have strong configurations (#4692)
  UPGRADING.rst
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, orange, 1 review, upgrade

#4826 Hotfix: Cannot index Ingest spreadsheets due to missing Submitter item (#4825)
  src/azul/plugins/metadata/hca/indexer/transform.py
Labels: orange, no sandbox, hotfix

#4834 Backport: 79c3086c (#4825, PR #4826) and c58df854 (#4818, PR #4821)
  deployments/prod/environment.py
  src/azul/plugins/metadata/hca/indexer/transform.py
Labels: sandbox, orange, 0 reviews

#4802 Ensure security contact information is registered (#4764)
  UPGRADING.rst
  deployments/dev.shared/environment.py
  environment.py
  src/azul/__init__.py
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, orange, 1 review, upgrade

#4833 Fix: File fields `size` and `name` are inconsistently named in AnVIL (#4642)
  src/azul/plugins/metadata/anvil/__init__.py
  test/integration_test.py
Labels: sandbox, orange, 1 review

#4796 Consolidate scripted calls of `terraform` (#4783)
  scripts/rename_resources.py
  src/azul/terraform.py
Labels: sandbox, orange, 2 reviews, base

#4845 Fix: Population of contents.sequencing_inputs disregards graph relationships (#2907)
  src/azul/plugins/metadata/hca/indexer/transform.py
  test/service/test_manifest.py
Labels: sandbox, orange, 0 reviews, reindex

#4849 Add four new dataset facets for AnVIL (#4495)
  src/azul/plugins/metadata/anvil/__init__.py
Labels: sandbox, orange, 1 review

#4856 Make dcp23 the default catalog on prod (#4839)
  deployments/prod/environment.py
Labels: orange, 0 reviews, no sandbox

#4842 Move CloudTrail trail to default region (#4831)
  UPGRADING.rst
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, orange, 1 review, base, upgrade
