Repository DataBiosphere/azul, pull requests merged in 2022-09, with the labels that each got.

#4420 Backport: 88fe1cda (#4122)
  deployments/prod/environment.py
Labels: orange, no sandbox

#4434 Promotions 2022-09-01 (#4433)
  .github/ISSUE_TEMPLATE/offboarding.md
  OPERATOR.rst
  src/azul/__init__.py
  src/azul/service/manifest_service.py
  terraform/authentication.tf.json.template.py
  test/service/test_manifest.py
Labels: orange, no sandbox

#4422 Fix: TDR requests are retried on connect (#4381)
  src/azul/__init__.py
  src/azul/terra.py
Labels: sandbox, orange, 0 reviews

#4427 Fix: Manifest handover requires bypassing the private API (#4399)
  src/azul/service/manifest_controller.py
Labels: sandbox, orange, 1 review

#4431 Fix: Tunnelblick client doesn't support split tunnels (#3930)
  README.md
  terraform/gitlab/vpn/Makefile
Labels: orange, no sandbox

#4439 Update GitLab to 15.3.3 (#4014)
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, no sandbox

#4426 Add support for compact manifest for AnVIL (#4349)
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/service/manifest_service.py
  test/integration_test.py
Labels: sandbox, orange, 0 reviews

#4437 Fix: Listing snapshots masks problems with OAuth client (#4435)
  scripts/post_deploy.py
  src/azul/plugins/repository/tdr.py
  src/azul/terra.py
Labels: sandbox, orange, 0 reviews

#4432 Fix: Non-route lambda handlers in service log hardcoded requestId (#4418)
  lambdas/indexer/app.py
  src/azul/chalice.py
Labels: orange, 1 review

#4450 Track main AnVIL deployments in PR checklists (#4122)
  .github/PULL_REQUEST_TEMPLATE/backport.md
  .github/PULL_REQUEST_TEMPLATE/gitlab.md
  .github/PULL_REQUEST_TEMPLATE/hotfix.md
  .github/PULL_REQUEST_TEMPLATE/promotion.md
  .github/pull_request_template.md
Labels: orange, no sandbox

#4464 Fix: 403 from TDR causes managed-access IT to fail (#4460)
  src/azul/terra.py
Labels: sandbox, orange, 0 reviews

#4441 Modify off-boarding issue template (#4206)
  .github/ISSUE_TEMPLATE/offboarding.md
Labels: orange, 0 reviews, no sandbox

#4459 Backport: 5801f064 (#4454)
  deployments/prod/environment.py
  environment.py
  src/azul/__init__.py
Labels: sandbox, orange

#4453 Remove `organismAgeUnit` term facet (#2796)
  lambdas/service/openapi.json
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.results.json
  test/indexer/test_hca_indexer.py
  test/service/data/pfb_manifest.results.json
  test/service/data/pfb_manifest.schema.json
  test/service/test_response.py
Labels: orange, 0 reviews, reindex
