Repository DataBiosphere/azul, pull requests merged in 2023-03, with the labels that each got.

#5012 Index updated projects into `lm3` on `prod` for LungMAP (#4921)
  deployments/prod/environment.py
Labels: orange, 0 reviews, reindex, no sandbox

#5020 Index 11 AnVIL schema v5 snapshots (#5014)
  deployments/anvilbox/environment.py
  deployments/anvildev/environment.py
Labels: sandbox, orange, 0 reviews, reindex

#5026 Rename shared (aka versioned aka config) bucket (#4918)
  UPGRADING.rst
  scripts/replicate_versioned_bucket.py
  src/azul/__init__.py
  src/azul/deployment.py
  terraform/shared/Makefile
  terraform/shared/shared.tf.json.template.py
Labels: orange, partial, upgrade

#4920 Forward ALB logs from S3 to CloudWatch (#4178)
  lambdas/indexer/app.py
  src/azul/__init__.py
  src/azul/deployment.py
  src/azul/indexer/lambda_iam_policy.py
  src/azul/indexer/log_forwarding_controller.py
  src/azul/indexer/log_forwarding_service.py
  src/azul/terraform.py
  terraform/api_gateway.tf.json.template.py
  terraform/shared/shared.tf.json.template.py
  test/azul_test_case.py
  test/test_deployment.py
  test/test_log_forwarding.py
Labels: sandbox, orange, 4+ reviews, base

#5027 Fix: Prod fails test_indexing IT for newly added lm3 project (#5023)
  deployments/prod/environment.py
Labels: orange, base, 0 reviews, no sandbox

#5028 Make dcp24 the default catalog on prod (#5010)
  deployments/prod/environment.py
Labels: orange, base, 0 reviews, no sandbox

#5029 Rename `shared` (aka `versioned` aka `config`) bucket (#4918)
  README.md
  UPGRADING.rst
  attic/scripts/replicate_versioned_bucket.py
  deployments/anvilbox/environment.py
  deployments/anvildev/environment.py
  deployments/anvilprod/environment.py
  deployments/dev/environment.py
  deployments/prod/environment.py
  deployments/sandbox/environment.py
  environment.py
  src/azul/__init__.py
  src/azul/lambda_layer.py
  src/azul/portal_service.py
  src/azul/service/lambda_iam_policy.py
  terraform/backend.tf.json.template.py
  terraform/lambda_layer.tf.json.template.py
  terraform/shared/Makefile
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, orange, upgrade

#5033 Promotion 2023-03-08 (#5032)
  UPGRADING.rst
  deployments/anvilbox/environment.py
  deployments/anvildev/environment.py
  deployments/prod/environment.py
  lambdas/indexer/app.py
  scripts/replicate_versioned_bucket.py
  src/azul/__init__.py
  src/azul/deployment.py
  src/azul/indexer/lambda_iam_policy.py
  src/azul/indexer/log_forwarding_controller.py
  src/azul/indexer/log_forwarding_service.py
  src/azul/terraform.py
  terraform/api_gateway.tf.json.template.py
  terraform/gitlab/gitlab.tf.json.template.py
  terraform/shared/Makefile
  terraform/shared/shared.tf.json.template.py
  test/azul_test_case.py
  test/test_deployment.py
  test/test_log_forwarding.py
Labels: orange, 1 review, no sandbox, upgrade

#5031 Enable access logging on AWS Config bucket (#5004)
  UPGRADING.rst
  terraform/shared/shared.tf.json.template.py
Labels: orange, base, 0 reviews, upgrade

#5040 Index 11 AnVIL schema v5 snapshots with supplemetary file fix (#5037)
  deployments/anvilbox/environment.py
  deployments/anvildev/environment.py
Labels: sandbox, orange, 0 reviews, reindex, chained

#5036 Enable VPC flow logs (#4176)
  UPGRADING.rst
  terraform/gitlab/gitlab.tf.json.template.py
  terraform/shared/shared.tf.json.template.py
Labels: orange, 0 reviews, no sandbox, upgrade

#5049 Promotion 2023-03-15 (#5048)
  README.md
  UPGRADING.rst
  attic/scripts/replicate_versioned_bucket.py
  deployments/anvilbox/environment.py
  deployments/anvildev/environment.py
  deployments/anvilprod/environment.py
  deployments/dev/environment.py
  deployments/prod/environment.py
  deployments/sandbox/environment.py
  environment.py
  src/azul/__init__.py
  src/azul/lambda_layer.py
  src/azul/portal_service.py
  src/azul/service/lambda_iam_policy.py
  terraform/backend.tf.json.template.py
  terraform/lambda_layer.tf.json.template.py
  terraform/shared/Makefile
  terraform/shared/shared.tf.json.template.py
Labels: orange, no sandbox, upgrade

#5066 Scan GitLab EC2 instance with Amazon Inspector (#4189)
  UPGRADING.rst
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, no sandbox, upgrade

#5052 S3 server access logging for `shared` bucket (#4960)
  UPGRADING.rst
  terraform/shared/shared.tf.json.template.py
Labels: orange, 0 reviews, no sandbox, upgrade

#5074 Hotfix: Index `dcp25` in `prod` (#5050)
  deployments/prod/environment.py
Labels: orange, 1 review, no sandbox, hotfix

#4976 Forward S3 access logs from S3 to CloudWatch (#4961)
  lambdas/indexer/app.py
  src/azul/indexer/lambda_iam_policy.py
  src/azul/indexer/log_forwarding_controller.py
  src/azul/indexer/log_forwarding_service.py
  terraform/api_gateway.tf.json.template.py
  test/test_log_forwarding.py
Labels: sandbox, orange, 2 reviews

#5072 Index updated projects into lm3 on prod for LungMAP (#4921)
  deployments/prod/environment.py
Labels: sandbox, orange, 0 reviews

#5075 Fix: `s3_access_log_bucket_policy` includes redundant condition on source account (#5071)
  UPGRADING.rst
  src/azul/deployment.py
Labels: sandbox, orange, 0 reviews, upgrade

#5085 Backport: 2edf7213 (#5050, PR #5080) and a6ccd38f (#5050, PR #5074)
  deployments/prod/environment.py
Labels: orange, no sandbox

#5013 S3 Block Public Access setting should be enabled (#4713)
  UPGRADING.rst
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, orange, 0 reviews, upgrade
