Repository DataBiosphere/azul, pull requests merged in 2023-09, with the labels that each got.

#5492 Backport: 228df19 (#5487, PR #5488)
  deployments/prod/environment.py
Labels: orange, no sandbox

#5486 Resolve vulnerabilities in AMI for GitLab (DataBiosphere/azul-private#95)
  UPGRADING.rst
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, 0 reviews, no sandbox, upgrade

#5508 Fix: PFB manifests in AnVIL should expire after 1 hour (DataBiosphere/azul-private#96)
  src/azul/service/manifest_controller.py
  src/azul/service/manifest_service.py
  test/service/test_manifest.py
  test/service/test_manifest_async.py
Labels: sandbox, orange, 0 reviews

#5510 Fix: Alarm raised for aggregate lambda errors during a reindex (#5495)
  lambdas/indexer/app.py
  src/azul/chalice.py
Labels: sandbox, orange, 1 review

#5513 Index dcp31 in prod (#5507)
  deployments/prod/environment.py
Labels: orange, 0 reviews, reindex, no sandbox

#5521 Promotion 2023-09-11 (#5520)
  deployments/prod/environment.py
Labels: orange, 0 reviews, reindex, no sandbox

#5502 Fix: GitHub job timeout for unit tests is too high (#5484)
  .github/workflows/ci.yml
Labels: orange, 0 reviews, no sandbox

#5504 Fix: `test_accessions_fields` does not assert anything (#5485)
  test/indexer/test_indexer.py
Labels: sandbox, orange, 0 reviews

#5523 Update GitLab to 16.3.2 and ClamAV to 1.2.0-1 (#4014)
  src/azul/__init__.py
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, no sandbox

#5531 Hotfix: project entorhinalCortexAlzheimers is missing genus_species (#5530)
  deployments/prod/environment.py
Labels: orange, no sandbox, hotfix

#5465 Fix: Needless layer update when deploying same commit twice (#5454)
  lambdas/lambdas.mk
Labels: sandbox, orange, 0 reviews

#5491 Index anvil2 in anvilprod (#5489)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
Labels: sandbox, orange, 2 reviews, reindex

#5527 Prepare for vacation (#5408)
  UPGRADING.rst
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, no sandbox, upgrade

#5529 Fix: Contribute Lambda causes throttle alarms during IT re-index (#5462)
  lambdas/indexer/app.py
Labels: sandbox, orange, 0 reviews

#5511 Reject empty sources during deployment (partial #5498)
  scripts/post_deploy_tdr.py
  src/azul/terra.py
Labels: sandbox, orange, no demo, partial, 1 review

#5538 Fix: IT fails on empty BED file in anvilprod (partial #5537)
  test/integration_test.py
Labels: sandbox, orange, no demo, partial, 0 reviews

#5463 Fix: Logs by different containers are hard to distinguish (#4468)
  UPGRADING.rst
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, 0 reviews, no sandbox, upgrade

#5548 Delete unused Docker images from ECR (2nd follow-up, #5189)
  UPGRADING.rst
  src/azul/docker.py
  terraform/shared/shared.tf.json.template.py
Labels: orange, no sandbox, upgrade

#5532 Backport: fac2b66a (#5530, PR #5531)
  deployments/prod/environment.py
Labels: orange, no sandbox

#5550 Reduce GCP permissions for developers to Viewer (DataBiosphere/azul-private#25)
  OPERATOR.rst
Labels: orange, no sandbox

#5516 Fix: Insecure Transportation Security Protocol Supported (TLS 1.0) (DataBiosphere/azul-private#15)
  UPGRADING.rst
  terraform/api_gateway.tf.json.template.py
  terraform/gitlab/gitlab.tf.json.template.py
Labels: sandbox, orange, 1 review, upgrade

#5559 Fix: GitLab IT failure in anvilprod for catalog_complete subtest (#5546)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
Labels: sandbox, orange, 0 reviews, reindex

#5455 Alarm for excessive number of requests blocked by WAF (#5286)
  terraform/cloudwatch.tf.json.template.py
Labels: sandbox, orange, 2 reviews

#5572 Mention partiality of changes in commit titles (#5415)
  .github/PULL_REQUEST_TEMPLATE/backport.md
  .github/PULL_REQUEST_TEMPLATE/gitlab.md
  .github/PULL_REQUEST_TEMPLATE/hotfix.md
  .github/PULL_REQUEST_TEMPLATE/promotion.md
  .github/pull_request_template.md
  .github/pull_request_template.md.template.py
  CONTRIBUTING.rst
Labels: orange, no sandbox

#5571 Remove incomplete authentication for cached manifests (#3328)
  requirements.all.txt
  requirements.dev.trans.txt
  requirements.dev.txt
  src/azul/deployment.py
  src/azul/service/manifest_controller.py
  src/azul/service/manifest_service.py
  test/service/test_manifest.py
  test/service/test_manifest_async.py
Labels: orange, no demo, partial, reqs

#5553 Increase retention of non-current object versions in shared bucket (#5552)
  UPGRADING.rst
  terraform/shared/shared.tf.json.template.py
Labels: orange, 0 reviews, no sandbox, upgrade

#5558 Increase retention of Elasticsearch domain error logs (#5557)
  src/azul/__init__.py
  terraform/elasticsearch.tf.json.template.py
Labels: sandbox, orange, 0 reviews
