Repository DataBiosphere/azul, pull requests merged in 2023-06, with the labels that each got.

#5265 Hotfix: Unit without value for donor age in project 5f607e50 (#5264)
  deployments/prod/environment.py
Labels: orange, 0 reviews, no sandbox, hotfix

#5261 Fix: Transient IT failure due to AssertionError in GitLab dev (#5251)
  test/integration_test.py
Labels: sandbox, orange, 0 reviews

#5267 Backport 298c42a1 (#5264, PR #5265) and d3f00622 (#5254, PR #5259)
  deployments/prod/environment.py
Labels: orange, 0 reviews, no sandbox

#5248 Back up DynamoDB versions table (#5174)
  terraform/dynamo.tf.json.template.py
Labels: sandbox, orange, 0 reviews

#5310 Fix: Sporadic DNS resolution errors on GitLab (#5226)
  UPGRADING.rst
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, no sandbox, upgrade

#5273 Fix: IT subtest managed_access_indices fails on AnVIL (#5167)
  test/integration_test.py
Labels: sandbox, orange, 2 reviews

#5285 Expose project/dataset accessibility as a facet (#5268)
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/service/elasticsearch_service.py
  test/service/test_response.py
  test/service/test_response_anvil.py
Labels: sandbox, orange, 1 review

#5306 Hotfix: Make dcp28 the default catalog on prod (#5290)
  deployments/prod/environment.py
Labels: orange, 0 reviews, no sandbox, hotfix

#5317 Backport: 8acc12e (#5290, PR #5306)
  deployments/prod/environment.py
Labels: orange, no sandbox

#5305 Fix: IT subtests manifest and repository_files fail due to lack of files (#5168)
  test/integration_test.py
Labels: sandbox, orange

#5321 Revert "Fix: IT subtests manifest and repository_files fail due to lack of files (#5168, PR #5305)
  test/integration_test.py
Labels: sandbox, orange, 0 reviews

#5244 Fix: Error when creating log forwarding bucket notification (#5030)
  src/azul/terraform.py
Labels: orange, 3 reviews

#5322 Fix: STS token can expire mid-deployment (#5302)
  OPERATOR.rst
  environment
Labels: sandbox, orange

#5304 Update GitLab to 16.0.3 (#4014)
  src/azul/__init__.py
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, 1 review, no sandbox

#5327 Fix: Replaced buckets remain empty in `browser` component (#5324)
  terraform/browser/browser.tf.json.template.py
Labels: orange, no sandbox

#5332 Index dcp29 in prod (#5328)
  deployments/prod/environment.py
Labels: orange, 0 reviews, reindex, no sandbox

#5326 Fix transient IT failure (#5167)
  test/integration_test.py
Labels: sandbox, orange, 0 reviews

#5313 Replace snapshot and remove workaround (#5229)
  deployments/anvilprod/environment.py
  test/integration_test.py
Labels: sandbox, orange, 2 reviews, reindex

#5335 Promotion 2023-06-21 (#5334)
  OPERATOR.rst
  UPGRADING.rst
  deployments/anvilprod/environment.py
  deployments/prod/environment.py
  environment
  src/azul/__init__.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/service/elasticsearch_service.py
  src/azul/terraform.py
  terraform/browser/browser.tf.json.template.py
  terraform/gitlab/gitlab.tf.json.template.py
  terraform/shared/shared.tf.json.template.py
  test/integration_test.py
  test/service/test_response.py
  test/service/test_response_anvil.py
Labels: orange, 0 reviews, reindex, no sandbox, upgrade

#5323 Ensure that each Bundle instance is a complete subgraph (#4941)
  src/azul/plugins/repository/tdr_anvil/__init__.py
Labels: sandbox, orange, 0 reviews

#5309 Store complete DRS URLs during indexing (#5276)
  lambdas/service/app.py
  lambdas/service/openapi.json
  src/azul/indexer/__init__.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  src/azul/plugins/metadata/hca/service/contributor_matrices.py
  src/azul/plugins/metadata/hca/service/response.py
  src/azul/plugins/repository/canned/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/plugins/repository/tdr_hca/__init__.py
  src/azul/service/avro_pfb.py
  src/azul/service/manifest_service.py
  src/azul/service/repository_controller.py
  src/azul/service/repository_service.py
  test/azul_test_case.py
  test/indexer/data/00f48893-5e9d-52cd-b32d-af88edccabfa.dss.hca.json
  test/indexer/data/02e69c25-71e2-48ca-a87b-e256938c6a98.dss.hca.json
  test/indexer/data/04836733-0449-4e57-be2e-6f3b8fbdfb12.dss.hca.json
  test/indexer/data/0722b70c-6778-423d-8fe9-869e2a515d35.dss.hca.json
  test/indexer/data/1b6d8348-d6e9-406a-aa6a-7ee886e52bf9.tdr.hca.json
  test/indexer/data/1fd499c5-f397-4bff-9af0-eb42c37d5fbe.dss.hca.json
  test/indexer/data/2c7d06b8-658e-4c51-9de4-a768322f84c5.dss.hca.json
  test/indexer/data/4426adc5-b3c5-5aab-ab86-51d8ce44dfbe.tdr.hca.json
  test/indexer/data/4b03c1ce-9df1-5cd5-a8e4-48a2fe095081.dss.hca.json
  test/indexer/data/79fa91b4-f1fc-534b-a935-b57342804a70.2020-12-10T10:30:00.000000Z.dss.hca.json
  test/indexer/data/7eb74d9f-8346-5420-b7e4-b486f99451a8.dss.hca.json
  test/indexer/data/80baee6e-00a5-4fdc-bfe3-d339ff8a7178.dss.hca.json
  test/indexer/data/826dea02-e274-affe-aabc-eb3db63ad068.results.json
  test/indexer/data/826dea02-e274-affe-aabc-eb3db63ad068.tdr.anvil.json
  test/indexer/data/8338b891-f3fa-5e7b-885f-e4ee5689ee15.dss.hca.json
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.results.json
  test/indexer/data/fce68057-b0f0-5d11-b9a7-30e8fa3259a8.dss.hca.json
  test/indexer/test_indexer.py
  test/indexer/test_tdr.py
  test/service/test_manifest.py
  test/service/test_repository_proxy.py
  test/service/test_response.py
  test/service/test_response_anvil.py
Labels: sandbox, orange, 1 review, reindex

#5347 Make anvilprod private and index AnVIL snapshots from TDR prod (#5283)
  deployments/anvilprod/environment.py
  environment.py
  scripts/check_branch.py
  src/azul/__init__.py
  src/azul/deployment.py
  test/integration_test.py
  test/test_check_branch.py
Labels: sandbox, orange, reindex

#5349 Index AnVIL snapshots from TDR dev in anvildev and anvilbox (#5283, #4398)
  UPGRADING.rst
  deployments/anvilbox/environment.py
  deployments/anvildev/environment.py
  src/azul/terra.py
  test/integration_test.py
Labels: orange, reindex, upgrade

#5307 Enable FIPS mode on GitLab instance (#5280)
  UPGRADING.rst
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, 1 review, no sandbox, upgrade

#5356 Make dcp29 the default catalog on production (#5351)
  deployments/prod/environment.py
Labels: orange, 0 reviews, no sandbox

#5343 Exclude noisy events from api_unauthorized alarm (#5325)
  UPGRADING.rst
  terraform/shared/shared.tf.json.template.py
Labels: orange, 0 reviews, no sandbox, upgrade

#5333 Create alarm for abnormally high VPC ingress and egress (#5282)
  terraform/cloudwatch.tf.json.template.py
Labels: sandbox, orange
