Repository DataBiosphere/azul, pull requests merged in 2023-02, with the labels that each got.

#4946 Update GitLab to 15.8.1 (#4014)
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, no demo, no sandbox

#4944 Integrate monitoring SNS topic with Slack (#4011)
  README.md
  UPGRADING.rst
  deployments/anvildev/environment.py
  deployments/dev/environment.py
  deployments/prod/environment.py
  environment.py
  src/azul/__init__.py
  terraform/cloudwatch.tf.json.template.py
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, orange, 1 review, upgrade

#4926 Rename Azul storage buckets (#4646)
  UPGRADING.rst
  deployments/anvilbox/environment.py
  deployments/anvildev/environment.py
  deployments/anvilprod/environment.py
  deployments/dev/environment.py
  deployments/prod/environment.py
  deployments/sandbox/environment.py
  scripts/rename_resources.py
Labels: sandbox, orange, 1 review, upgrade

#4951 Fix: GitHub jobs are run twice (#4939)
  .github/workflows/ci.yml
Labels: orange, 0 reviews, no sandbox

#4959 Fix: Storage bucket is still being removed from TF state (#4958)
  UPGRADING.rst
  scripts/rename_resources.py
Labels: orange, 3 reviews, upgrade

#4948 Cover AnVIL service response in unit tests (#4931)
  lambdas/service/app.py
  test/indexer/__init__.py
  test/indexer/test_anvil.py
  test/service/test_response.py
Labels: sandbox, orange, 1 review

#4973 Fix: Service app.repository_controller should be cached (#4957)
  lambdas/service/app.py
  terraform/api_gateway.tf.json.template.py
Labels: sandbox, orange

#4975 Index updated projects into `lm3` on `prod` for LungMAP (#4921)
  deployments/prod/environment.py
Labels: orange, 0 reviews, reindex, no sandbox

#4977 Fix: Many caches persist between test cases (#4956)
  src/azul/logging.py
  src/azul/service/drs_controller.py
  src/azul/service/repository_controller.py
  src/azul/service/source_service.py
  test/app_test_case.py
  test/azul_test_case.py
  test/health_check_test_case.py
  test/indexer/__init__.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.results.json
  test/indexer/test_anvil.py
  test/indexer/test_health_check.py
  test/indexer/test_indexer.py
  test/indexer/test_indexer_controller.py
  test/indexer/test_notifications.py
  test/indexer/test_projects.py
  test/indexer/test_tdr.py
  test/service/__init__.py
  test/service/test_app_logging.py
  test/service/test_cache_poisoning.py
  test/service/test_drs.py
  test/service/test_health_check.py
  test/service/test_manifest.py
  test/service/test_manifest_async.py
  test/service/test_pagination.py
  test/service/test_repository_projects.py
  test/service/test_repository_proxy.py
  test/service/test_repository_specimen.py
  test/service/test_request_builder.py
  test/service/test_request_validation.py
  test/service/test_response.py
  test/service/test_response_anvil.py
  test/service/test_storage_service.py
  test/test_app_logging.py
  test/test_doctests.py
  test/test_tagging.py
Labels: sandbox, orange, reindex

#4981 Index `dcp24` in `prod` (#4979)
  deployments/prod/environment.py
Labels: orange, 0 reviews, reindex, no sandbox

#4980 Fix: Chatbot role policy is too restrictive and causes persistent alarms (#4966)
  UPGRADING.rst
  terraform/shared/shared.tf.json.template.py
Labels: orange, 0 reviews, upgrade

#4820 Fix: GitLab backup script should start instance after completing (#4819)
  OPERATOR.rst
  scripts/create_gitlab_snapshot.py
Labels: orange, 4+ reviews, no sandbox

#5001 Fix: Failed notifications for `dcp24` due to empty donor age (#4999)
  deployments/prod/environment.py
Labels: orange, 1 review, no sandbox

#4974 Fix: Storage and portal service tests leak file handles (#4564)
  bin/wheels/runtime/wrapt-1.14.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  bin/wheels/runtime/wrapt-1.15.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  requirements.all.txt
  requirements.dev.trans.txt
  requirements.dev.txt
  requirements.trans.txt
  test/azul_test_case.py
  test/service/test_storage_service.py
Labels: sandbox, orange, reqs

#4906 Fix: Invalid value for URL param version should cause 4xx error (#4878)
  lambdas/service/app.py
  scripts/cgm_adapter.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  src/azul/plugins/repository/canned/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr.py
  src/azul/time.py
  test/service/test_drs.py
  test/service/test_repository_proxy.py
  test/service/test_request_validation.py
  test/service/test_response.py
Labels: sandbox, orange, 4+ reviews

#4998 Enable ALB access logs for private Azul deployments (#4649)
  terraform/api_gateway.tf.json.template.py
Labels: sandbox, orange, base
