Repository DataBiosphere/azul, pull requests merged in 2023-08, with the labels that each got.

#5439 Prepare for vacation (#5408)
  .github/CODEOWNERS
  UPGRADING.rst
  terraform/gitlab/gitlab.tf.json.template.py
Labels: sandbox, orange, partial, upgrade

#5395 Index new AnVIL CMG snapshots (#5392)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
  scripts/update_subgraph_counts.py
  terraform/api_gateway.tf.json.template.py
Labels: orange, base, 0 reviews, reindex

#5451 Promotion 2023-08-03 (#5450)
  .github/CODEOWNERS
  .gitlab-ci.yml
  Dockerfile
  Makefile
  OPERATOR.rst
  README.md
  UPGRADING.rst
  bin/wheels/runtime/boto3-1.27.1-py3-none-any.whl
  bin/wheels/runtime/boto3-1.28.12-py3-none-any.whl
  bin/wheels/runtime/certifi-2023.5.7-py3-none-any.whl
  bin/wheels/runtime/certifi-2023.7.22-py3-none-any.whl
  bin/wheels/runtime/fastavro-1.6.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  bin/wheels/runtime/fastavro-1.8.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  bin/wheels/runtime/googleapis_common_protos-1.59.1-py2.py3-none-any.whl
  bin/wheels/runtime/googleapis_common_protos-1.60.0-py2.py3-none-any.whl
  bin/wheels/runtime/grpcio_status-1.56.0-py3-none-any.whl
  bin/wheels/runtime/grpcio_status-1.56.2-py3-none-any.whl
  deployments/anvilbox/environment.py
  deployments/anvildev/environment.py
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
  lambdas/indexer/app.py
  lambdas/service/app.py
  requirements.all.txt
  requirements.dev.trans.txt
  requirements.dev.txt
  requirements.pip.txt
  requirements.trans.txt
  requirements.txt
  scripts/create_gitlab_snapshot.py
  scripts/update_subgraph_counts.py
  src/azul/__init__.py
  src/azul/chalice.py
  src/azul/drs.py
  src/azul/indexer/document.py
  src/azul/indexer/index_service.py
  src/azul/indexer/log_forwarding_controller.py
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/tdr.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/plugins/repository/tdr_hca/__init__.py
  src/azul/service/avro_pfb.py
  terraform/api_gateway.tf.json.template.py
  terraform/cloudwatch.tf.json.template.py
  terraform/gitlab/gitlab.tf.json.template.py
  terraform/gitlab/runner/Dockerfile
  test/service/data/pfb_manifest.schema.json
Labels: orange, no sandbox, reqs, upgrade

#5442 Fix: Noisy alarm from EC2 for CreateNetworkInterface during initial deploy (#5363)
  UPGRADING.rst
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, orange, 0 reviews, upgrade

#5453 Deploy consortia tab of AnVIL portal (#5452)
  deployments/anvildev.browser/environment.py
  deployments/anvilprod.browser/environment.py
  terraform/browser/browser.tf.json.template.py
  terraform/browser/ptm_add_response_headers.js
  terraform/browser/ptm_next_path_mapper.js
Labels: sandbox, orange, 1 review

#5396 Index new AnVIL GTEx snapshots (#5393)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
Labels: sandbox, orange, reindex

#5444 Allow null values in PFBs (#2462)
  src/azul/service/avro_pfb.py
  test/service/data/pfb_manifest.results.json
  test/service/data/pfb_manifest.schema.json
  test/service/test_pfb.py
Labels: sandbox, orange

#5447 Alarm on detection of new vulnerabilities by Inspector (#5301, #4175)
  UPGRADING.rst
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, orange, 0 reviews, upgrade

#5458 Fix: Alarms for Lambda metrics (#5060, #4997)
  terraform/cloudwatch.tf.json.template.py
Labels: sandbox, orange, 0 reviews

#5460 Fix: Project e0009214 from dcp1 catalog failed to index in prod (#5366)
  src/azul/plugins/metadata/hca/bundle.py
  src/azul/service/manifest_service.py
Labels: orange, 1 review, no sandbox

#5474 Hotfix: Index `dcp30` in prod (#5473)
  deployments/prod/environment.py
Labels: orange, reindex, no sandbox, hotfix

#5464 Improve caching of DRS and TDR clients (#5357)
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/tdr.py
  src/azul/terra.py
Labels: sandbox, orange, 0 reviews

#5477 Ignore cached manifests older than 1 hour (partial DataDiosphere/azul-private#96)
  src/azul/service/manifest_service.py
  test/service/test_manifest.py
Labels: sandbox, orange, partial

#5478 Backport: d5af05c9 (#5473, PR #5474)
  deployments/prod/environment.py
Labels: orange, no sandbox

#5483 Remove safety net from source cache format transition (#5204)
  src/azul/service/source_service.py
Labels: orange, base, no sandbox

#5488 Hotfix: Make `dcp30` the default catalog on prod (#5487)
  deployments/prod/environment.py
Labels: orange, no sandbox, hotfix
