Repository DataBiosphere/azul, pull requests merged in 2023-11, with the labels that each got.

#5664 Index anvil3 in anvilprod (#5616)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
Labels: sandbox, orange, 1 review

#5651 Fix: AWS Inspector fails to post findings to SNS topic (#5612)
  UPGRADING.rst
  terraform/shared/shared.tf.json.template.py
Labels: orange, 1 review, no sandbox, upgrade

#5680 Check snapshot status after ES software updates (#5677)
  OPERATOR.rst
Labels: orange, 0 reviews, no sandbox

#5679 Index dcp33 in prod (#5678)
  deployments/prod/environment.py
Labels: orange, 0 reviews, reindex, no sandbox

#5674 Plugin-ify the reconciliation of inner entities (#2783, #5673)
  .flake8/azul_flake8.py
  src/azul/azulclient.py
  src/azul/indexer/__init__.py
  src/azul/indexer/aggregate.py
  src/azul/indexer/document.py
  src/azul/indexer/index_service.py
  src/azul/indexer/transform.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/anvil/bundle.py
  src/azul/plugins/metadata/anvil/indexer/aggregate.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/bundle.py
  src/azul/plugins/metadata/hca/indexer/aggregate.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/service/__init__.py
  src/azul/service/manifest_service.py
  src/azul/service/repository_controller.py
  src/azul/service/repository_service.py
  src/azul/terra.py
  src/azul/types.py
  test/hca_metadata_api/test.py
  test/indexer/test_indexer.py
  test/integration_test.py
Labels: sandbox, orange, base

#5684 Fix: TerraClient prematurely raises TerraTimeoutException (#5682)
  src/azul/terra.py
Labels: sandbox, orange, 0 reviews

#5686 Promotion 2023-11-08 (#5685)
  .flake8/azul_flake8.py
  OPERATOR.rst
  UPGRADING.rst
  bin/wheels/runtime/charset_normalizer-3.3.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  bin/wheels/runtime/charset_normalizer-3.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  bin/wheels/runtime/protobuf-4.24.4-cp37-abi3-manylinux2014_x86_64.whl
  bin/wheels/runtime/protobuf-4.25.0-cp37-abi3-manylinux2014_x86_64.whl
  deployments/prod/environment.py
  requirements.all.txt
  requirements.dev.trans.txt
  requirements.pip.txt
  requirements.trans.txt
  src/azul/__init__.py
  src/azul/azulclient.py
  src/azul/indexer/__init__.py
  src/azul/indexer/aggregate.py
  src/azul/indexer/document.py
  src/azul/indexer/index_service.py
  src/azul/indexer/transform.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/anvil/bundle.py
  src/azul/plugins/metadata/anvil/indexer/aggregate.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/bundle.py
  src/azul/plugins/metadata/hca/indexer/aggregate.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/service/__init__.py
  src/azul/service/manifest_service.py
  src/azul/service/repository_controller.py
  src/azul/service/repository_service.py
  src/azul/terra.py
  src/azul/types.py
  terraform/gitlab/gitlab.tf.json.template.py
  terraform/shared/shared.tf.json.template.py
  test/hca_metadata_api/test.py
  test/indexer/test_indexer.py
  test/integration_test.py
Labels: orange, reindex, no sandbox, upgrade

#5671 Fix: False positive AWS Inspector findings after GitLab deploy (#5617)
  UPGRADING.rst
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, 0 reviews, no sandbox, upgrade

#5669 Fix: Simultaneous requests for same manifest cause redundant generations (#3271, DataBiosphere/azul-private#110, #5668)
  lambdas/service/app.py
  lambdas/service/openapi.json
  src/azul/__init__.py
  src/azul/bytes.py
  src/azul/service/async_manifest_service.py
  src/azul/service/lambda_iam_policy.py
  src/azul/service/manifest_controller.py
  src/azul/service/manifest_service.py
  terraform/step_function.tf.json.template.py
  test/integration_test.py
  test/service/test_manifest_async.py
  test/test_doctests.py
Labels: sandbox, orange, API

#5649 Index AnVIL dataset description from DUOS (#5547)
  deployments/anvilbox/environment.py
  deployments/anvildev/environment.py
  environment.py
  lambdas/service/app.py
  lambdas/service/openapi.json
  src/azul/__init__.py
  src/azul/chalice.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/terra.py
  test/indexer/__init__.py
  test/indexer/data/2370f948-2783-aeb6-afea-e022897f4dcf.tdr.anvil.json
  test/indexer/test_anvil.py
  test/indexer/test_indexer.py
  test/integration_test.py
Labels: sandbox, orange, API, 0 reviews, reindex

#5694 Promotion 2023-11-15 (#5693)
  UPGRADING.rst
  lambdas/service/app.py
  lambdas/service/openapi.json
  src/azul/__init__.py
  src/azul/bytes.py
  src/azul/service/async_manifest_service.py
  src/azul/service/lambda_iam_policy.py
  src/azul/service/manifest_controller.py
  src/azul/service/manifest_service.py
  terraform/gitlab/gitlab.tf.json.template.py
  terraform/step_function.tf.json.template.py
  test/integration_test.py
  test/service/test_manifest_async.py
  test/test_doctests.py
Labels: orange, API, no sandbox, upgrade

#5697 Fix: HPRC Dataset should be dropped from anvil3 (#5690)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
Labels: orange, 0 reviews, no sandbox

#5692 Fix: Throttle alarms still go off during reindex in prod (#5688)
  lambdas/indexer/app.py
Labels: sandbox, orange, 0 reviews

#5700 Fix: Clients from azul.deployment.aws use unrefreshable credentials (#5699)
  environment
  scripts/envhook.py
  src/azul/deployment.py
Labels: sandbox, orange

#5479 Fix: Service Lambda times out, causing alarms (#5472)
  src/azul/deployment.py
  src/azul/es.py
  src/azul/logging.py
Labels: sandbox, orange, partial, 2 reviews

#5710 Promotion 2023-11-22 (#5709)
  deployments/anvilbox/environment.py
  deployments/anvildev/environment.py
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
  environment
  environment.py
  lambdas/indexer/app.py
  lambdas/service/app.py
  lambdas/service/openapi.json
  scripts/envhook.py
  src/azul/__init__.py
  src/azul/chalice.py
  src/azul/deployment.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/terra.py
  test/indexer/__init__.py
  test/indexer/data/2370f948-2783-aeb6-afea-e022897f4dcf.tdr.anvil.json
  test/indexer/test_anvil.py
  test/indexer/test_indexer.py
  test/integration_test.py
Labels: orange, API, no sandbox

#5707 Create bundles index for AnVIL (#5214)
  lambdas/service/app.py
  lambdas/service/openapi.json
  src/azul/collections.py
  src/azul/indexer/document_service.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  test/indexer/__init__.py
  test/indexer/data/826dea02-e274-affe-aabc-eb3db63ad068.results.json
  test/indexer/test_anvil.py
  test/integration_test.py
  test/service/test_response_anvil.py
Labels: orange, API, 1 review, base, reindex

#5730 Fix `KeyError: 'azul_docker_version'` when running unit tests in PyCharm (#5729)
  environment.boot
  scripts/envhook.py
  scripts/export_environment.py
Labels: sandbox, orange
