Repository DataBiosphere/azul, pull requests merged in 2023-05, with the labels that each got.

#5180 Update GitLab to 15.11.1 and ClamAV to 1.1.0-1 (#4014)
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, no sandbox

#5182 Fix: Transient failure of OpenAPIIntegrationTest (#5179)
  terraform/api_gateway.tf.json.template.py
Labels: sandbox, orange, 0 reviews

#5163 Fix: Invalid JSON for search_after or …before should cause 4xx (#4996)
  lambdas/service/app.py
  test/service/test_request_validation.py
  test/service/test_response.py
Labels: sandbox, orange, 1 review

#5059 Index supplementary files for AnVIL (#5000)
  scripts/can_bundle.py
  src/azul/azulclient.py
  src/azul/indexer/__init__.py
  src/azul/indexer/index_controller.py
  src/azul/indexer/index_service.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/anvil/service/response.py
  src/azul/plugins/repository/canned/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/plugins/repository/tdr_hca/__init__.py
  src/azul/service/source_service.py
  src/azul/types.py
  test/indexer/data/826dea02-e274-affe-aabc-eb3db63ad068.result.tdr.json
  test/indexer/data/826dea02-e274-affe-aabc-eb3db63ad068.results.json
  test/indexer/test_indexer_controller.py
  test/indexer/test_notifications.py
  test/integration_test.py
  test/service/__init__.py
  test/service/test_response_anvil.py
Labels: sandbox, orange, 3 reviews, base, reindex

#5199 Promotion 2023-05-10 (#5198)
  deployments/prod/environment.py
  lambdas/service/app.py
  scripts/can_bundle.py
  src/azul/azulclient.py
  src/azul/indexer/__init__.py
  src/azul/indexer/index_controller.py
  src/azul/indexer/index_service.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/anvil/service/response.py
  src/azul/plugins/repository/canned/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/plugins/repository/tdr_hca/__init__.py
  src/azul/service/source_service.py
  src/azul/types.py
  test/indexer/data/826dea02-e274-affe-aabc-eb3db63ad068.result.tdr.json
  test/indexer/data/826dea02-e274-affe-aabc-eb3db63ad068.results.json
  test/indexer/test_indexer_controller.py
  test/indexer/test_notifications.py
  test/integration_test.py
  test/service/__init__.py
  test/service/test_request_validation.py
  test/service/test_response.py
  test/service/test_response_anvil.py
Labels: orange, API, reindex, no sandbox

#5201 Hotfix: Index dcp27 in prod (#5186)
  deployments/prod/environment.py
Labels: orange, 0 reviews, reindex, no sandbox, hotfix

#5205 Hotfix: Snapshots from dcp25 & dcp27 contain || in metadata (#5203)
  deployments/prod/environment.py
Labels: orange, no sandbox, hotfix

#5192 Update GitLab to 15.11.2 (#4014)
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, no sandbox

#5181 Fix: Missing items in onboarding checklist for probationary period (#5176)
  .github/ISSUE_TEMPLATE/onboarding.md
Labels: orange, 0 reviews, no sandbox

#5213 Backport: 14fa66b (#5203, PR #5205) and 2adf4a9 (#5186, PR #5201)
  deployments/prod/environment.py
Labels: orange, no sandbox

#5196 Fix: /index/{entity_type}/{uuid} needlessly performs ES aggregations (#4136, #4131)
  src/azul/service/repository_service.py
  test/integration_test.py
Labels: sandbox, orange, 0 reviews

#5157 Trigger an alarm on absence of logs (#5133)
  UPGRADING.rst
  terraform/cloudwatch.tf.json.template.py
  terraform/shared/shared.tf.json.template.py
Labels: orange, 2 reviews, upgrade

#5216 Fix: IT subtest catalog_complete fails on GitLab anvildev (#5200, #2625)
  src/azul/indexer/index_service.py
  test/integration_test.py
Labels: orange, 0 reviews

#5211 Encrypt GitLab data and root volume and snapshots (#4022)
  UPGRADING.rst
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, 0 reviews, no sandbox

#5185 Use TDR roleMap endpoint for list of accessible snapshots (#4937)
  src/azul/chalice.py
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/tdr.py
  src/azul/service/source_controller.py
  src/azul/service/source_service.py
  src/azul/terra.py
  test/azul_test_case.py
  test/service/__init__.py
  test/service/test_cache_poisoning.py
  test/service/test_repository_proxy.py
Labels: sandbox, orange, 2 reviews

#5209 Keep GitLab instances updated (#3962)
  OPERATOR.rst
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, 2 reviews, no sandbox

#5225 Fix: Partition sizing ignores supplementary bundles (#5207)
  UPGRADING.rst
  deployments/anvilbox/environment.py
  deployments/anvildev/environment.py
  deployments/anvilprod/environment.py
  scripts/update_subgraph_counts.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
Labels: sandbox, orange, 1 review, upgrade

#5223 Fix: PR checklist should mention unchaining steps (#5190)
  .github/PULL_REQUEST_TEMPLATE/backport.md
  .github/PULL_REQUEST_TEMPLATE/gitlab.md
  .github/PULL_REQUEST_TEMPLATE/hotfix.md
  .github/PULL_REQUEST_TEMPLATE/promotion.md
  .github/pull_request_template.md
  .github/pull_request_template.md.template.py
  OPERATOR.rst
Labels: orange, 2 reviews, no sandbox

#5233 Fix: `source environment` causes a ModuleNotFoundError (#5143)
  scripts/envhook.py
Labels: sandbox, orange, 0 reviews

#5230 Fix: S3 server access logs are inherently incomplete (#5043)
  UPGRADING.rst
  terraform/shared/shared.tf.json.template.py
Labels: orange, 0 reviews, no sandbox, upgrade

#5243 Promotion 2023-05-25 (#5242)
  OPERATOR.rst
  UPGRADING.rst
  deployments/anvilbox/environment.py
  deployments/anvildev/environment.py
  deployments/anvilprod/environment.py
  scripts/create_gitlab_snapshot.py
  scripts/update_subgraph_counts.py
  src/azul/chalice.py
  src/azul/indexer/index_service.py
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/tdr.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/service/source_controller.py
  src/azul/service/source_service.py
  src/azul/terra.py
  terraform/cloudwatch.tf.json.template.py
  terraform/gitlab/gitlab.tf.json.template.py
  terraform/shared/shared.tf.json.template.py
  test/app_test_case.py
  test/azul_test_case.py
  test/integration_test.py
  test/service/__init__.py
  test/service/test_cache_poisoning.py
  test/service/test_repository_proxy.py
  test/test_content_type.py
Labels: orange, 0 reviews, no sandbox, upgrade

#5240 Revert "Fix: S3 server access logs are inherently incomplete (#5043, PR #5230)"
  UPGRADING.rst
  terraform/shared/shared.tf.json.template.py
Labels: orange, 0 reviews, no sandbox, upgrade

#5160 Fix: Swagger UI for indexer is a stub (#5051, #5228)
  .github/workflows/ci.yml
  .gitlab-ci.yml
  Makefile
  README.md
  lambdas/Makefile
  lambdas/indexer/app.py
  lambdas/indexer/openapi.json
  lambdas/lambdas.mk
  lambdas/service/app.py
  lambdas/service/openapi.json
  scripts/generate_openapi_document.py
  src/azul/openapi/params.py
  src/azul/openapi/spec.py
Labels: sandbox, orange, 4+ reviews

#5231 Fix: IT fails in anvilprod due to multiple values for is_supplementary (#5229)
  test/integration_test.py
Labels: orange, 0 reviews

#5250 Use git fetch instead of pull when smoke-testing GitLab
  OPERATOR.rst
Labels: orange, 0 reviews, no sandbox

#5187 Send GitLab host logs to CloudWatch (#3894)
  UPGRADING.rst
  terraform/gitlab/gitlab.tf.json.template.py
Labels: sandbox, orange, 2 reviews, upgrade
