Repository DataBiosphere/azul, pull requests merged in 2023-10, with the labels that each got.

#5575 GitLab updates cause false positive insufficient_data alarms (#5518)
  UPGRADING.rst
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, 0 reviews, no sandbox, upgrade

#5576 Fix: Post-deploy script potentially overloads TDR (#5522)
  scripts/post_deploy_tdr.py
Labels: sandbox, orange, 0 reviews

#5578 Make dcp31 the default catalog on prod (#5574)
  deployments/prod/environment.py
Labels: orange, 0 reviews, no sandbox

#5579 Fix: ES requests are not logged before they are made (#4233)
  src/azul/es.py
  src/azul/indexer/index_service.py
  src/azul/logging.py
  test/es_test_case.py
  test/indexer/test_indexer.py
Labels: sandbox, orange

#5361 Refactor indices to accomodate replicas (#5358)
  src/azul/__init__.py
  src/azul/collections.py
  src/azul/indexer/document.py
  src/azul/indexer/document_service.py
  src/azul/indexer/index_service.py
  src/azul/service/elasticsearch_service.py
  test/indexer/__init__.py
  test/indexer/test_indexer.py
  test/indexer/test_projects.py
  test/service/__init__.py
  test/service/test_response.py
Labels: sandbox, orange, base, 0 reviews

#5573 Alarm when WAF rate limit kicks in (#5554)
  src/azul/__init__.py
  terraform/api_gateway.tf.json.template.py
  terraform/cloudwatch.tf.json.template.py
Labels: sandbox, orange, 1 review

#5589 Refactor indices to accomodate replicas (#5358)
  src/azul/__init__.py
Labels: sandbox, orange

#5584 Update GitLab to 16.4.1 and ClamAV to 1.2.0-7 (#4014)
  src/azul/__init__.py
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, 1 review, no sandbox

#5539 Fix: Alarm on detection of new vulnerabilities by Inspector (#5301, #4175)
  UPGRADING.rst
  terraform/gitlab/gitlab.tf.json.template.py
  terraform/shared/shared.tf.json.template.py
Labels: orange, 1 review, no sandbox, upgrade

#5525 Resolve vulnerabilities in azul-pycharm image (DataBiosphere/azul-private#94)
  Makefile
  UPGRADING.rst
  requirements.all.txt
  requirements.dev.trans.txt
  src/azul/__init__.py
Labels: sandbox, orange, 1 review, reqs, upgrade

#5600 Fix: Aggregates do not read sources from ES (#5563)
  src/azul/indexer/document.py
  src/azul/indexer/index_service.py
Labels: sandbox, orange, base, 0 reviews

#5604 Index dcp32 in prod (#5601)
  deployments/prod/environment.py
Labels: orange, 0 reviews, reindex, no sandbox

#5594 Prevent unintentional generation of expensive manifests (#5533, #4050, #3571)
  lambdas/indexer/app.py
  lambdas/indexer/openapi.json
  lambdas/service/app.py
  lambdas/service/openapi.json
  src/azul/service/manifest_controller.py
  src/azul/service/manifest_service.py
  terraform/step_function.tf.json.template.py
  test/integration_test.py
  test/service/test_manifest.py
  test/service/test_manifest_async.py
  test/service/test_request_validation.py
Labels: sandbox, orange, API, partial

#5517 Resolve vulnerabilities in azul-elasticsearch image (DataBiosphere/azul-private#93
  UPGRADING.rst
  src/azul/__init__.py
  test/es_test_case.py
Labels: sandbox, orange, 1 review, upgrade

#5620 Fix: Project `a1375150` in `dcp32` failed to index (#5619)
  deployments/prod/environment.py
Labels: orange, partial, 0 reviews, no sandbox

#5627 Fix: update_subgraph_counts script raises an AssertionError (#5514)
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/tdr_hca/__init__.py
Labels: sandbox, orange, 0 reviews

#5632 Promotion 2023-10-18 (#5631)
  UPGRADING.rst
  deployments/prod/environment.py
  lambdas/indexer/app.py
  lambdas/indexer/openapi.json
  lambdas/service/app.py
  lambdas/service/openapi.json
  requirements.all.txt
  requirements.dev.txt
  src/azul/__init__.py
  src/azul/service/manifest_controller.py
  src/azul/service/manifest_service.py
  terraform/step_function.tf.json.template.py
  test/es_test_case.py
  test/integration_test.py
  test/service/test_manifest.py
  test/service/test_manifest_async.py
  test/service/test_request_validation.py
Labels: orange, API, 0 reviews, upgrade

#5633 Resolve vulnerabilities in docker image (DataBiosphere/azul-private#108)
  UPGRADING.rst
  src/azul/__init__.py
  terraform/gitlab/gitlab.tf.json.template.py
  terraform/gitlab/runner/Dockerfile
Labels: sandbox, orange, 0 reviews, upgrade

#5636 Fix: Transient `test_get_cached_manifest` unit test failure (#5621)
  test/service/test_manifest.py
Labels: sandbox, orange

#5596 Fix: Request for 210 projects returns "Internal server error" (#3886)
  lambdas/service/app.py
  lambdas/service/openapi.json
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/hca/__init__.py
  test/service/test_response.py
Labels: sandbox, orange, API, 1 review

#5602 Fix: GitLab updates cause false positive insufficient_data alarms (#5518)
  UPGRADING.rst
  terraform/gitlab/gitlab.tf.json.template.py
Labels: sandbox, orange, 1 review, upgrade

#5623 Fix: AWS Inspector fails to post findings to SNS topic (#5612)
  UPGRADING.rst
  terraform/shared/shared.tf.json.template.py
Labels: orange, 1 review, no sandbox, upgrade

#5468 Index replica entities (#5359)
  deployments/anvilprod/environment.py
  deployments/prod/environment.py
  environment.py
  src/azul/__init__.py
  src/azul/azulclient.py
  src/azul/indexer/document.py
  src/azul/indexer/document_service.py
  src/azul/indexer/index_controller.py
  src/azul/indexer/index_service.py
  src/azul/indexer/transform.py
  src/azul/json.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  test/indexer/__init__.py
  test/indexer/data/826dea02-e274-affe-aabc-eb3db63ad068.results.json
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.results.json
  test/indexer/test_indexer.py
  test/indexer/test_indexer_controller.py
Labels: sandbox, orange, 1 review, base, reindex

#5646 Fix: FASTQ files described as analysis_file instead of sequence_file (#5606)
  deployments/prod/environment.py
Labels: orange, partial, 1 review, reindex, no sandbox

#5564 Fix: Lambda servicecachehealth times out (partial #5467)
  src/azul/health.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/terra.py
  test/health_check_test_case.py
  test/indexer/test_health_check.py
  test/service/test_health_check.py
Labels: sandbox, orange, partial, 2 reviews

#5628 Reduce predictability of manifest keys (DataBiosphere/azul-private#110, #5658)
  UPGRADING.rst
  attic/scripts/scrape_aws_service_model.py
  attic/src/azul/aws_service_model.py
  attic/terraform/gitlab/aws_service_model.json.gz
  bin/wheels/runtime/msgpack-1.0.7-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  requirements.all.txt
  requirements.dev.trans.txt
  requirements.dev.txt
  requirements.txt
  src/azul/__init__.py
  src/azul/attrs.py
  src/azul/deployment.py
  src/azul/service/async_manifest_service.py
  src/azul/service/lambda_iam_policy.py
  src/azul/service/manifest_controller.py
  src/azul/service/manifest_service.py
  src/azul/types.py
  terraform/authentication.tf.json.template.py
  terraform/gitlab/gitlab.tf.json.template.py
  test/integration_test.py
  test/service/test_manifest.py
  test/service/test_manifest_async.py
  test/test_doctests.py
Labels: sandbox, orange, reqs, upgrade

#5647 Index anvil3 in anvilprod (#5616)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
Labels: sandbox, orange, 0 reviews, reindex

#5657 Make dcp32 the default catalog on prod (#5642)
  deployments/prod/environment.py
Labels: orange, 0 reviews, no sandbox
