Repository DataBiosphere/azul, pull requests merged in 2023-07, with the labels that each got.

#5344 Maintain a version number for the API (#4332)
  .github/PULL_REQUEST_TEMPLATE/promotion.md
  .github/pull_request_template.md
  .github/pull_request_template.md.template.py
  lambdas/indexer/app.py
  lambdas/service/app.py
Labels: sandbox, orange

#5331 Fix: IT subtests manifest and repository_files fail due to lack of files (#5168)
  test/integration_test.py
Labels: sandbox, orange, 0 reviews

#5378 Fix: AnVIL deployments conflate indexer and public SAs (#4398, #5381)
  src/azul/terra.py
  test/integration_test.py
Labels: sandbox, orange, 0 reviews

#5382 Update GitLab to v16.1.2, AMI to v2.0.0.21 (#4014)
  src/azul/__init__.py
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, 1 review, no sandbox

#5380 Fix: GitLab diagram is inaccurate (#5379)
  docs/gitlab.monopic
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, no sandbox

#5383 Allow `||` joiners in dcp1 metadata (#5366)
  src/azul/indexer/__init__.py
  src/azul/indexer/index_service.py
  src/azul/plugins/metadata/anvil/bundle.py
  src/azul/plugins/metadata/hca/bundle.py
  src/azul/service/manifest_service.py
Labels: sandbox, orange, 0 reviews, reindex

#5385 Fix: AnVIL deployments conflate indexer and public SAs (#4398, #5381)
  src/azul/terra.py
  test/integration_test.py
Labels: sandbox, orange, 1 review

#5362 Suppress unauthorized alarms for visiting Inspector console (#5291)
  UPGRADING.rst
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, orange, 0 reviews, upgrade

#5241 Alarms for Lambda metrics (#5060, #4997)
  lambdas/indexer/app.py
  lambdas/service/app.py
  src/azul/__init__.py
  src/azul/chalice.py
  src/azul/indexer/log_forwarding_controller.py
  terraform/cloudwatch.tf.json.template.py
Labels: sandbox, orange, 4+ reviews

#5394 Encapsulate source JSON representations (partial, #3889)
  scripts/can_bundle.py
  src/azul/indexer/__init__.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  test/integration_test.py
Labels: sandbox, orange, partial, 1 review

#5402 Make anvilprod and hammerbox public (#5400)
  README.md
  UPGRADING.rst
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
  src/azul/__init__.py
  src/azul/oauth2.py
  src/azul/plugins/repository/tdr.py
  src/azul/terra.py
  terraform/authentication.tf.json.template.py
  test/indexer/test_tdr.py
  test/integration_test.py
  test/service/test_repository_proxy.py
Labels: sandbox, orange, upgrade

#5410 Delete unused Docker images from ECR (follow-up, #5189)
  scripts/copy_images_to_ecr.py
Labels: orange, no sandbox, upgrade

#5409 Fix: False positive for `unauthorized` alarm from MandoService (#5407)
  UPGRADING.rst
  terraform/shared/shared.tf.json.template.py
Labels: orange, 0 reviews, no sandbox

#5341 Update/harden docker.elastic.co/elasticsearch/elasticsearch (#5292)
  UPGRADING.rst
  src/azul/__init__.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  test/es_test_case.py
  test/indexer/__init__.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.results.json
Labels: sandbox, orange, 2 reviews, upgrade

#5401 Fix: Transient IT timeout in prod (#5367, #5374)
  .gitlab-ci.yml
Labels: sandbox, orange, 0 reviews

#5166 Update AnVIL catalogs in `anvilprod` with replacement snapshots (#5155)
  UPGRADING.rst
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
  src/azul/drs.py
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/tdr.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/plugins/repository/tdr_hca/__init__.py
Labels: sandbox, orange, 4+ reviews, base, reindex, upgrade

#5399 Alarms for Lambda metrics (#5060, #4997)
  lambdas/indexer/app.py
  lambdas/service/app.py
  src/azul/__init__.py
  src/azul/chalice.py
  src/azul/indexer/log_forwarding_controller.py
  terraform/cloudwatch.tf.json.template.py
Labels: sandbox, orange, 2 reviews

#5412 Encapsulate source JSON representations (#3889)
  src/azul/indexer/document.py
  src/azul/indexer/index_service.py
Labels: sandbox, orange, 0 reviews

#5427 Hotfix: AttributeError in test_auth_list_snapshots on prod (#5426)
  test/indexer/test_tdr.py
Labels: orange, no sandbox, hotfix

#5275 CloudWatch metrics and alarms for GitLab EC2 instance (partial, #5139)
  UPGRADING.rst
  terraform/gitlab/gitlab.tf.json.template.py
Labels: sandbox, orange, partial, 1 review, upgrade

#5433 Fix: `make requirements` fails on Apple Silicone (#5432)
  bin/wheels/runtime/boto3-1.27.1-py3-none-any.whl
  bin/wheels/runtime/boto3-1.28.12-py3-none-any.whl
  bin/wheels/runtime/fastavro-1.6.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  bin/wheels/runtime/fastavro-1.8.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  requirements.all.txt
  requirements.dev.trans.txt
  requirements.dev.txt
  requirements.pip.txt
  requirements.txt
  src/azul/service/avro_pfb.py
  test/service/data/pfb_manifest.schema.json
Labels: sandbox, orange, reqs

#5411 Harden Azul build image (#5388)
  Dockerfile
  Makefile
  README.md
Labels: sandbox, orange, 0 reviews

#5352 Grow GitLab data volume in `dev` and document the process (#5348)
  OPERATOR.rst
  scripts/create_gitlab_snapshot.py
Labels: orange, 2 reviews, no sandbox

#5418 Make anvildev and anvilbox public (#5413)
  UPGRADING.rst
  deployments/anvilbox/environment.py
  deployments/anvildev/environment.py
Labels: sandbox, orange, upgrade

#5430 Backport: 2a043bd (#5426, PR #5427) (#5429)
  test/indexer/test_tdr.py
Labels: sandbox, orange, 0 reviews

#5369 Keep `docker` Docker images updated (#5298)
  UPGRADING.rst
  src/azul/__init__.py
  terraform/gitlab/gitlab.tf.json.template.py
  terraform/gitlab/runner/Dockerfile
Labels: sandbox, orange, 0 reviews, upgrade
