Repository DataBiosphere/azul, pull requests merged in 2023-01, with the labels that each got.

#4804 Enable S3 bucket access logging on the CloudTrail bucket (#4792)
  UPGRADING.rst
  terraform/s3.tf.json.template.py
  terraform/shared/shared.tf.json.template.py
Labels: orange, 3 reviews, no sandbox, upgrade

#4862 Update GitLab to 15.7.0 (#4014)
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, no sandbox

#4869 Update gitpython to 3.1.30 (PR #4860)
  requirements.all.txt
  requirements.dev.trans.txt
  requirements.dev.txt
Labels: sandbox, orange, no demo, 0 reviews, reqs

#4871 Fix: VPN connections fail to authenticate due to expired CRL (#4865)
  terraform/gitlab/vpn/Makefile
Labels: orange, no sandbox

#4872 Combine logged request query and headers into one JSON literal (#4868)
  src/azul/chalice.py
  test/service/test_app_logging.py
  test/test_app_logging.py
Labels: sandbox, orange, 0 reviews

#4805 Ensure log metric filters and alarms exist for CIS recommendations (#4794, #4853)
  UPGRADING.rst
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, orange, 0 reviews, upgrade

#4876 Fix: BQ queries fail on GitLab due to reported lack of reservation (#4771)
  src/azul/terra.py
Labels: sandbox, orange, 0 reviews

#4754 Ensure the default security group of every VPC restricts all traffic (#4689)
  scripts/import_default_vpc.py
  scripts/import_gitlab_security_group.py
  src/azul/terraform.py
  terraform/gitlab/gitlab.tf.json.template.py
  terraform/shared/Makefile
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, orange, 4+ reviews

#4894 Update GitLab to 15.7.2 (#4014)
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, no demo, no sandbox

#4893 Disable original CloudTrail trail (#4832, #4829)
  UPGRADING.rst
  deployments/dev/environment.py
  deployments/prod/environment.py
  environment.py
  scripts/rename_resources.py
  src/azul/__init__.py
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, orange, 0 reviews, upgrade

#4891 Fix: Alarms for CIS recommendations treat missing data as OK (#4880)
  UPGRADING.rst
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, orange, 0 reviews, upgrade

#4900 Fix: Invalid mix of search_after and search_before should cause 4xx error (#4879)
  lambdas/service/app.py
Labels: sandbox, orange, 0 reviews

#4899 Rename `biosamples.donor_age_at_collection_age_range` to `.donor_age_at_collection` (#4897)
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/anvil/indexer/aggregate.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/anvil/service/response.py
  test/indexer/data/9b78f049-83fc-a99b-83bc-8d40e34265cd.results.json
Labels: sandbox, orange, base, 0 reviews, reindex

#4857 Fix offboarding template (#4798)
  .github/ISSUE_TEMPLATE/offboarding.md
Labels: orange, 0 reviews, no sandbox

#4905 Fix: CodeQL is broken for chained PRs (#4901)
  .github/workflows/ci.yml
Labels: orange, 1 review, no sandbox

#4913 Promotion 2023-01-18 (#4909)
  .github/ISSUE_TEMPLATE/offboarding.md
  UPGRADING.rst
  deployments/dev/environment.py
  deployments/prod/environment.py
  environment.py
  lambdas/service/app.py
  scripts/import_default_vpc.py
  scripts/import_gitlab_security_group.py
  scripts/rename_resources.py
  src/azul/__init__.py
  src/azul/chalice.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/anvil/indexer/aggregate.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/anvil/service/response.py
  src/azul/terra.py
  src/azul/terraform.py
  terraform/gitlab/gitlab.tf.json.template.py
  terraform/shared/Makefile
  terraform/shared/shared.tf.json.template.py
  test/indexer/data/9b78f049-83fc-a99b-83bc-8d40e34265cd.results.json
  test/service/test_app_logging.py
  test/test_app_logging.py
Labels: orange, 1 review, reindex, no sandbox, upgrade

#4908 Fix: CIS 2.6 (S3 access logging on CloudTrail bucket) still flagged in dev (#4907)
  UPGRADING.rst
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, orange, 1 review, upgrade

#4904 Fix: Invalid value for URL param order should cause 4xx error (#4877)
  lambdas/service/app.py
  test/service/test_request_validation.py
Labels: orange, 1 review

#4927 [r] Index updated project into lm3 on prod for LungMAP (#4921)
  deployments/prod/environment.py
Labels: orange, 0 reviews, reindex, no sandbox

#4933 Index updated project into lm3 on prod for LungMAP (#4921)
  deployments/prod/environment.py
Labels: orange, 1 review, 0 reviews, no sandbox

#4925 Include diagnoses as inner entities for all outer entities (#4922)
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/anvil/service/response.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  test/indexer/data/826dea02-e274-affe-aabc-eb3db63ad068.result.tdr.json
  test/indexer/data/826dea02-e274-affe-aabc-eb3db63ad068.results.json
Labels: sandbox, orange, 1 review, reindex

#4854 Eliminate burner accounts (#4673)
  OPERATOR.rst
  README.md
  UPGRADING.rst
Labels: sandbox, orange, 4+ reviews, upgrade

#4935 Hotfix: Remove hardcoded reference to lm2 catalog in IT (#4934)
  test/integration_test.py
Labels: orange, 1 review, no sandbox, hotfix

#4936 Backport: c1b2b25 (#4934, PR #4935)
  test/integration_test.py
Labels: sandbox, orange

#4768 Integrate monitoring SNS topic with Slack (#4011)
  README.md
  UPGRADING.rst
  deployments/anvildev/environment.py
  deployments/dev/environment.py
  deployments/prod/environment.py
  environment.py
  src/azul/__init__.py
  terraform/cloudwatch.tf.json.template.py
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, orange, 4+ reviews, upgrade

#4889 Mandate use of git-secrets (#4858)
  .github/ISSUE_TEMPLATE/onboarding.md
  README.md
Labels: sandbox, orange, 4+ reviews, base
