Repository DataBiosphere/azul, pull requests merged in 2024-11, with the labels that each got.

#6674 Backport: 673e82a0 (#6661, PR #6653)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
Labels: sandbox, orange, 0 reviews

#6672 Clarify and enforce bundle FQID equality semantics (#6671)
  src/azul/indexer/__init__.py
  src/azul/indexer/document.py
  src/azul/indexer/transform.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  test/indexer/test_indexer.py
  test/indexer/test_projects.py
  test/integration_test.py
Labels: sandbox, orange, 0 reviews

#6670 Fix: Various problems in can_bundle script (#6669)
  scripts/can_bundle.py
  src/azul/indexer/index_service.py
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  test/indexer/test_indexer_controller.py
  test/integration_test.py
Labels: sandbox, orange

#6677 Fix: Indexing integration test is complicated and inefficient (#6676)
  src/azul/indexer/__init__.py
  src/azul/plugins/__init__.py
  test/integration_test.py
Labels: sandbox, orange, 0 reviews

#6627 Index orphaned replicas (#6626)
  scripts/can_bundle.py
  scripts/post_deploy_tdr.py
  src/azul/azulclient.py
  src/azul/indexer/document.py
  src/azul/indexer/index_service.py
  src/azul/indexer/transform.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/anvil/bundle.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  src/azul/plugins/repository/canned/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/plugins/repository/tdr_hca/__init__.py
  src/azul/service/manifest_service.py
  src/azul/terra.py
  src/azul/uuids.py
  terraform/authentication.tf.json.template.py
  test/indexer/data/6b0f6c0f-5d80-a242-accb-840921351cd5.tdr.anvil.json
  test/indexer/data/6c87f0e1-509d-46a4-b845-7584df39263b.tables.tdr.json
  test/indexer/data/826dea02-e274-affe-aabc-eb3db63ad068.results.json
  test/indexer/data/826dea02-e274-affe-aabc-eb3db63ad068.tdr.anvil.json
  test/indexer/data/9a135c9a-069b-a90e-b588-eaf8d1aeeac9.tdr.anvil.json
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.results.json
  test/indexer/data/c67e7adb-1a9c-a3b9-bc91-eb10a428374a.tdr.anvil.json
  test/indexer/test_anvil.py
  test/indexer/test_tdr.py
  test/integration_test.py
  test/service/test_manifest.py
Labels: sandbox, orange, base, 0 reviews, reindex:dev, reindex:anvildev, reindex:anvilprod

#6623 Include orphans in manifest when filtering by only project/dataset (#6619)
  src/azul/indexer/document_service.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/anvil/service/filter.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/service/filter.py
  src/azul/service/avro_pfb.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/manifest_service.py
  src/azul/service/repository_service.py
  test/service/test_filters.py
  test/service/test_manifest.py
  test/service/test_request_builder.py
Labels: sandbox, orange, 0 reviews

#6700 Fix: Inspector findings missing from report (#6692)
  .github/PULL_REQUEST_TEMPLATE/upgrade.md
  .github/pull_request_template.md.template.py
Labels: sandbox, orange, 0 reviews

#6701 Add updated snapshot for project 6135382f to `lm8` (#6689)
  deployments/prod/environment.py
Labels: sandbox, orange, 0 reviews, reindex:prod, reindex:partial

#6708 Make anvil8 default catalog and remove anvil7 (#6707)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
Labels: orange, 0 reviews, no sandbox, reindex:anvilprod, reindex:partial

#6711 Promotion 2024-11-12 prod (#6699)
  .github/PULL_REQUEST_TEMPLATE/upgrade.md
  .github/pull_request_template.md.template.py
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
  deployments/prod/environment.py
  scripts/can_bundle.py
  scripts/post_deploy_tdr.py
  src/azul/azulclient.py
  src/azul/indexer/__init__.py
  src/azul/indexer/document.py
  src/azul/indexer/document_service.py
  src/azul/indexer/index_service.py
  src/azul/indexer/transform.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/anvil/bundle.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/anvil/service/filter.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  src/azul/plugins/metadata/hca/service/filter.py
  src/azul/plugins/repository/canned/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/plugins/repository/tdr_hca/__init__.py
  src/azul/service/avro_pfb.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/manifest_service.py
  src/azul/service/repository_service.py
  src/azul/terra.py
  src/azul/uuids.py
  terraform/authentication.tf.json.template.py
  test/indexer/data/6b0f6c0f-5d80-a242-accb-840921351cd5.tdr.anvil.json
  test/indexer/data/6c87f0e1-509d-46a4-b845-7584df39263b.tables.tdr.json
  test/indexer/data/826dea02-e274-affe-aabc-eb3db63ad068.results.json
  test/indexer/data/826dea02-e274-affe-aabc-eb3db63ad068.tdr.anvil.json
  test/indexer/data/9a135c9a-069b-a90e-b588-eaf8d1aeeac9.tdr.anvil.json
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.results.json
  test/indexer/data/c67e7adb-1a9c-a3b9-bc91-eb10a428374a.tdr.anvil.json
  test/indexer/test_anvil.py
  test/indexer/test_indexer.py
  test/indexer/test_indexer_controller.py
  test/indexer/test_projects.py
  test/indexer/test_tdr.py
  test/integration_test.py
  test/service/test_filters.py
  test/service/test_manifest.py
  test/service/test_request_builder.py
Labels: orange, no sandbox, reindex:prod, reindex:partial

#6710 Promotion 2024-11-12 anvilprod (#6699)
  .github/PULL_REQUEST_TEMPLATE/upgrade.md
  .github/pull_request_template.md.template.py
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
  deployments/prod/environment.py
  scripts/can_bundle.py
  scripts/post_deploy_tdr.py
  src/azul/azulclient.py
  src/azul/indexer/__init__.py
  src/azul/indexer/document.py
  src/azul/indexer/document_service.py
  src/azul/indexer/index_service.py
  src/azul/indexer/transform.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/anvil/bundle.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/anvil/service/filter.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  src/azul/plugins/metadata/hca/service/filter.py
  src/azul/plugins/repository/canned/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/plugins/repository/tdr_hca/__init__.py
  src/azul/service/avro_pfb.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/manifest_service.py
  src/azul/service/repository_service.py
  src/azul/terra.py
  src/azul/uuids.py
  terraform/authentication.tf.json.template.py
  test/indexer/data/6b0f6c0f-5d80-a242-accb-840921351cd5.tdr.anvil.json
  test/indexer/data/6c87f0e1-509d-46a4-b845-7584df39263b.tables.tdr.json
  test/indexer/data/826dea02-e274-affe-aabc-eb3db63ad068.results.json
  test/indexer/data/826dea02-e274-affe-aabc-eb3db63ad068.tdr.anvil.json
  test/indexer/data/9a135c9a-069b-a90e-b588-eaf8d1aeeac9.tdr.anvil.json
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.results.json
  test/indexer/data/c67e7adb-1a9c-a3b9-bc91-eb10a428374a.tdr.anvil.json
  test/indexer/test_anvil.py
  test/indexer/test_indexer.py
  test/indexer/test_indexer_controller.py
  test/indexer/test_projects.py
  test/indexer/test_tdr.py
  test/integration_test.py
  test/service/test_filters.py
  test/service/test_manifest.py
  test/service/test_request_builder.py
Labels: sandbox, orange, reindex:anvilprod

#6695 Use two-phase deployment for `prod.shared` (#6680)
  .github/PULL_REQUEST_TEMPLATE/anvilprod-promotion.md
  .github/PULL_REQUEST_TEMPLATE/prod-promotion.md
  .github/PULL_REQUEST_TEMPLATE/upgrade.md
  .github/pull_request_template.md.template.py
Labels: orange, 0 reviews, no sandbox

#6718 Index dcp44 in prod (#6717)
  deployments/prod/environment.py
Labels: 0 reviews, no sandbox, reindex:prod, reindex:partial

#6624 Fix: Service Lambda timeouts cause user-facing 5xx responses (#6284)
  lambdas/indexer/app.py
  lambdas/indexer/openapi.json
  lambdas/layer/app.py
  lambdas/service/app.py
  lambdas/service/openapi.json
  scripts/generate_openapi_document.py
  src/azul/chalice.py
  src/azul/health.py
  src/azul/openapi/spec.py
  src/azul/terraform.py
  test/integration_test.py
  test/test_app_logging.py
  test/test_openapi.py
Labels: sandbox, orange, API, 3 reviews

#6483 Fix: Content Security Policy (CSP) Not Implemented (DataBiosphere/azul-private#6)
  lambdas/service/app.py
  scripts/convert_environment.py
  src/azul/chalice.py
  src/azul/csp.py
  src/azul/terraform.py
  src/azul/threads.py
  swagger/oauth2-redirect.html.template.mustache
  swagger/swagger-ui.html.template.mustache
  test/integration_test.py
  test/service/test_app_logging.py
  test/test_app_logging.py
  test/test_doctests.py
Labels: sandbox, orange, 4+ reviews

#6705 Fix: Left-overs from orphan-related PRs (#6691)
  src/azul/indexer/index_service.py
  src/azul/plugins/metadata/anvil/bundle.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/repository/canned/__init__.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/service/manifest_service.py
  test/indexer/__init__.py
  test/integration_test.py
  test/pfb_test_case.py
  test/service/data/manifest/terra/pfb_entities.json
  test/service/data/manifest/terra/pfb_schema.json
  test/service/data/manifest/verbatim/pfb/anvil/pfb_entities.json
  test/service/data/manifest/verbatim/pfb/anvil/pfb_schema.json
  test/service/data/manifest/verbatim/pfb/hca/pfb_entities.json
  test/service/data/manifest/verbatim/pfb/hca/pfb_schema.json
  test/service/test_manifest.py
  test/service/test_pfb.py
Labels: sandbox, orange, 1 review, base

#6726 Hotfix prod: Remove snapshot for 248c5dc3-6b75-4fb4-ad8a-cc771968483f from prod (#6725)
  deployments/prod/environment.py
Labels: orange, no sandbox, hotfix

#6729 Hotfix prod: Adjust prod project count (#6725)
  deployments/prod/environment.py
Labels: orange, 1 review, no sandbox, hotfix

#6713 Upgrade dependencies 2024-11-11 (#6698)
  docker_images.json
  environment.boot
  environment.py
  requirements.all.txt
  requirements.dev.trans.txt
Labels: sandbox, orange, reqs, deploy:gitlab, deploy:shared, backup:gitlab

#6712 Improve linkage of PR CL items for admin (#6706)
  .github/ISSUE_TEMPLATE/upgrade.md
  .github/PULL_REQUEST_TEMPLATE/anvilprod-promotion.md
  .github/PULL_REQUEST_TEMPLATE/prod-promotion.md
  .github/PULL_REQUEST_TEMPLATE/upgrade.md
  .github/pull_request_template.md
  .github/pull_request_template.md.template.py
  scripts/export_environment.py
Labels: sandbox, orange, 2 reviews

#6703 Fix: CloudWatch alarms left triggered after _hibernate function is used (#6702)
  environment
Labels: orange, 1 review, no sandbox

#6733 Fix: Enable orphans with any dataset filter, not just ID (#6728)
  src/azul/service/manifest_service.py
  test/service/test_manifest.py
Labels: sandbox, orange
