Repository DataBiosphere/azul, pull requests merged in 2024-10, with the labels that each got.

#6562 Fix: Inspector reports should link to CVEs (#6557)
  scripts/export_inspector_findings.py
Labels: orange, 0 reviews

#6608 Fix: Lungmap.net link to Data Browser is broken (#6603)
  terraform/browser/bucket_path_mapper.js
Labels: sandbox, orange, 0 reviews

#6385 Fix: 4xx and 5xx responses from API Gateway cause Invicti findings (DataBiosphere/azul-private#154)
  .github/pull_request_template.md.template.py
  scripts/convert_environment.py
  src/azul/bigquery.py
  src/azul/chalice.py
  src/azul/plugins/repository/tdr_hca/__init__.py
  src/azul/service/manifest_service.py
  src/azul/strings.py
  src/azul/terraform.py
  terraform/browser/browser.tf.json.template.py
  terraform/gitlab/gitlab.tf.json.template.py
  test/integration_test.py
  test/service/test_app_logging.py
  test/service/test_manifest.py
  test/test_app_logging.py
  test/test_log_forwarding.py
Labels: sandbox, orange, 4+ reviews

#6605 Promotion 2024-10-01 anvilprod (#6602)
  .github/CODEOWNERS
  OPERATOR.rst
  UPGRADING.rst
  attic/scripts/update_subgraph_counts.py
  bin/wheels/runtime/idna-3.10-py3-none-any.whl
  bin/wheels/runtime/idna-3.8-py3-none-any.whl
  bin/wheels/runtime/protobuf-4.25.4-cp37-abi3-manylinux2014_x86_64.whl
  bin/wheels/runtime/protobuf-4.25.5-cp37-abi3-manylinux2014_x86_64.whl
  bin/wheels/runtime/pyasn1-0.6.0-py2.py3-none-any.whl
  bin/wheels/runtime/pyasn1-0.6.1-py3-none-any.whl
  bin/wheels/runtime/pyasn1_modules-0.4.0-py3-none-any.whl
  bin/wheels/runtime/pyasn1_modules-0.4.1-py3-none-any.whl
  bin/wheels/runtime/pytz-2024.1-py2.py3-none-any.whl
  bin/wheels/runtime/pytz-2024.2-py2.py3-none-any.whl
  deployments/anvilbox/environment.py
  deployments/anvildev/environment.py
  deployments/anvilprod/environment.py
  deployments/dev/environment.py
  deployments/hammerbox/environment.py
  deployments/prod.browser/environment.py
  deployments/prod/environment.py
  deployments/sandbox/environment.py
  deployments/tempdev/environment.py
  docker_images.json
  environment
  environment.boot
  environment.py
  requirements.all.txt
  requirements.dev.trans.txt
  requirements.trans.txt
  scripts/can_bundle.py
  scripts/export_inspector_findings.py
  scripts/post_deploy_tdr.py
  src/azul/azulclient.py
  src/azul/indexer/__init__.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/anvil/bundle.py
  src/azul/plugins/metadata/anvil/indexer/aggregate.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/indexer/aggregate.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  src/azul/plugins/metadata/hca/service/aggregation.py
  src/azul/plugins/metadata/hca/service/contributor_matrices.py
  src/azul/plugins/metadata/hca/service/response.py
  src/azul/plugins/repository/canned/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/plugins/repository/tdr_hca/__init__.py
  src/azul/terra.py
  terraform/browser/bucket_path_mapper.js
  test/docker_container_test_case.py
  test/integration_test.py
Labels: sandbox, orange, reqs, upgrade, reindex:anvilprod, deploy:gitlab, deploy:shared, deploy:runner, backup:gitlab

#6584 Fix: No replicas for donors in HCA (#6582)
  README.md
  src/azul/indexer/index_service.py
  src/azul/indexer/transform.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  src/humancellatlas/data/metadata/api.py
  terraform/shared/shared.tf.json.template.py
  test/hca_metadata_api/test.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.results.json
  test/indexer/test_anvil.py
  test/indexer/test_indexer.py
  test/service/data/verbatim/hca/pfb_entities.json
  test/service/data/verbatim/hca/pfb_schema.json
  test/service/test_manifest.py
Labels: sandbox, orange, base, 0 reviews, reindex:dev, reindex:anvildev, reindex:anvilprod, reindex:prod

#6617 Backport: 42fcfe32 (#6610, PR #6604)
  deployments/prod/environment.py
Labels: orange, no sandbox

#6613 Refactor handing of AnVIL links (#6612)
  src/azul/collections.py
  src/azul/plugins/metadata/anvil/bundle.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
Labels: sandbox, orange, 0 reviews

#6611 Index lm8 in LungMAP (#6606)
  deployments/prod/environment.py
Labels: orange, 0 reviews, no sandbox, reindex:prod, reindex:partial

#6625 Index dcp43 in prod (#6622)
  deployments/prod/environment.py
Labels: orange, 0 reviews, no sandbox, reindex:prod, reindex:partial

#6566 Fix: Invalid columns in compact manifest for AnVIL (#6110)
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/anvil/service/response.py
  test/integration_test.py
  test/service/test_manifest.py
Labels: sandbox, orange, 1 review

#6632 Index anvil8 in anvilprod (#6631)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
Labels: orange, 0 reviews, no sandbox, reindex:anvilprod, reindex:partial

#6635 Fix: Alarm api_unauthorized for HeadBucket from AWS Config (#6134)
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, orange, 0 reviews, deploy:shared

#6633 Promotion 2024-10-15 anvilprod (#6630)
  .github/CODEOWNERS
  .github/pull_request_template.md.template.py
  README.md
  deployments/prod/environment.py
  scripts/convert_environment.py
  src/azul/bigquery.py
  src/azul/chalice.py
  src/azul/collections.py
  src/azul/indexer/index_service.py
  src/azul/indexer/transform.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/anvil/bundle.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/plugins/repository/tdr_hca/__init__.py
  src/azul/service/manifest_service.py
  src/azul/strings.py
  src/azul/terraform.py
  src/humancellatlas/data/metadata/api.py
  terraform/browser/browser.tf.json.template.py
  terraform/gitlab/gitlab.tf.json.template.py
  terraform/shared/shared.tf.json.template.py
  test/hca_metadata_api/test.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.results.json
  test/indexer/test_anvil.py
  test/indexer/test_indexer.py
  test/integration_test.py
  test/service/data/verbatim/hca/pfb_entities.json
  test/service/data/verbatim/hca/pfb_schema.json
  test/service/test_app_logging.py
  test/service/test_manifest.py
  test/test_app_logging.py
  test/test_log_forwarding.py
Labels: sandbox, orange, reindex:anvilprod

#6634 Promotion 2024-10-15 prod (#6630)
  .github/CODEOWNERS
  .github/pull_request_template.md.template.py
  README.md
  deployments/prod/environment.py
  scripts/convert_environment.py
  src/azul/bigquery.py
  src/azul/chalice.py
  src/azul/collections.py
  src/azul/indexer/index_service.py
  src/azul/indexer/transform.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/anvil/bundle.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/plugins/repository/tdr_hca/__init__.py
  src/azul/service/manifest_service.py
  src/azul/strings.py
  src/azul/terraform.py
  src/humancellatlas/data/metadata/api.py
  terraform/browser/browser.tf.json.template.py
  terraform/gitlab/gitlab.tf.json.template.py
  terraform/shared/shared.tf.json.template.py
  test/hca_metadata_api/test.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.results.json
  test/indexer/test_anvil.py
  test/indexer/test_indexer.py
  test/integration_test.py
  test/service/data/verbatim/hca/pfb_entities.json
  test/service/data/verbatim/hca/pfb_schema.json
  test/service/test_app_logging.py
  test/service/test_manifest.py
  test/test_app_logging.py
  test/test_log_forwarding.py
Labels: orange, no sandbox, reindex:prod

#6640 Track table names in AnVIL bundles (#6639)
  src/azul/azulclient.py
  src/azul/indexer/document.py
  src/azul/plugins/metadata/anvil/bundle.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  test/indexer/data/2370f948-2783-aeb6-afea-e022897f4dcf.tdr.anvil.json
  test/indexer/data/6b0f6c0f-5d80-a242-accb-840921351cd5.tdr.anvil.json
  test/indexer/data/6c87f0e1-509d-46a4-b845-7584df39263b.tables.tdr.json
  test/indexer/data/826dea02-e274-affe-aabc-eb3db63ad068.results.json
  test/indexer/data/826dea02-e274-affe-aabc-eb3db63ad068.tdr.anvil.json
  test/indexer/test_anvil.py
  test/integration_test.py
  test/service/test_manifest.py
  test/service/test_response_anvil.py
Labels: sandbox, orange, base, 0 reviews, reindex:anvildev, reindex:anvilprod

#6643 Delete unused resources (#5871, #6534)
  deployments/prod/environment.py
  terraform/browser/add_response_security_headers.js
  terraform/browser/add_trailing_slash.js
  terraform/browser/browser.tf.json.template.py
  terraform/browser/explorer_domain_router.js
  terraform/browser/ptm_add_response_headers.js
  terraform/browser/ptm_next_path_mapper.js
Labels: sandbox, orange, reindex:prod, reindex:partial

#6650 Hotfix prod: Optimistic lock contention on HCA replicas (#6648)
  deployments/prod/environment.py
Labels: orange, partial, no sandbox, hotfix, reindex:prod, reindex:partial

#6651 Hotfix prod: Error indexing lm8 catalog (#6644)
  deployments/prod/environment.py
Labels: orange, partial, no sandbox, hotfix, reindex:prod, reindex:partial

#6654 Hotfix prod: Optimistic lock contention on HCA replicas (#6648)
  scripts/generate_openapi_document.py
Labels: orange, partial, 0 reviews, no sandbox, hotfix, reindex:prod, reindex:partial

#6659 Hotfix prod: Make dcp43 default and delete project snapshot cdabcf0b (#6658, #6664)
  deployments/prod/environment.py
Labels: orange, no sandbox, hotfix, reindex:prod, reindex:partial

#6652 Fix: Optimistic lock contention on HCA replicas (#6648)
  src/azul/indexer/document.py
  src/azul/indexer/index_service.py
Labels: sandbox, orange, partial, reindex:dev, reindex:prod
