Repository DataBiosphere/azul, pull requests merged in 2024-07, with the labels that each got.

#6369 Fix: ResourceNotFoundException when creating CW dashboard (#6271)
  terraform/cloudwatch_dashboard.template.json.py
Labels: sandbox, orange, 0 reviews

#6375 Make dcp39 the default catalog on prod (#6365)
  deployments/prod/environment.py
Labels: orange, 0 reviews, no sandbox, reindex:prod, reindex:partial

#6367 Reindex lm7 (#6364)
  deployments/prod/environment.py
Labels: orange, 0 reviews, no sandbox, reindex:lmprod, reindex:partial

#6368 Increase threshold for "unauthorized" metric alarm (#6220)
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, orange, 0 reviews, deploy:shared

#6313 Fix: Cannot filter by tissue atlas (#5519)
  lambdas/service/app.py
  lambdas/service/openapi.json
  src/azul/indexer/aggregate.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/indexer/aggregate.py
  src/azul/service/avro_pfb.py
  src/azul/service/elasticsearch_service.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.results.json
  test/service/data/pfb_manifest.results.json
  test/service/data/pfb_manifest.schema.json
  test/service/test_response.py
Labels: sandbox, orange, API, 0 reviews, reindex:dev, reindex:prod

#6386 Fix: BigQuery slot purchase fails in tempdev (#6263)
  src/azul/bigquery_reservation.py
Labels: sandbox, orange, 0 reviews

#6372 Fix: Operators have SSH access to anvilprod (#6371)
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, 2 reviews, no sandbox, deploy:gitlab

#6401 Make lm7 the default catalog for LungMAP prod (#6391)
  deployments/prod/environment.py
Labels: 0 reviews, no sandbox, reindex:partial

#6416 Index dcp40 in prod (#6411)
  deployments/prod/environment.py
Labels: orange, 0 reviews, no sandbox, reindex:prod, reindex:partial

#6418 Index anvil7 in anvilprod (#6398)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
Labels: orange, 0 reviews, no sandbox, reindex:anvilprod, reindex:partial

#6402 Fix: Transient IT failue for [catalog_complete] sub-test in GitLab prod (#6335)
  deployments/prod/environment.py
Labels: orange, 0 reviews, no sandbox, reindex:partial

#6357 Fix: Non-abusive request rates trigger WAF rate blocked alarms (#6321)
  scripts/request_flooder.py
  src/azul/__init__.py
  terraform/api_gateway.tf.json.template.py
  terraform/cloudwatch.tf.json.template.py
Labels: sandbox, orange, 2 reviews

#6422 Promotion 2024-07-16 prod (#6413)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
  deployments/prod/environment.py
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, no sandbox, reindex:prod, deploy:gitlab, reindex:partial

#6415 Fix: Quotes or backslashes in fields break API Gateway logs JSON (#4348)
  terraform/api_gateway.tf.json.template.py
Labels: sandbox, orange, 0 reviews

#6423 Promotion 2024-07-16 anvilprod (#6413)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
  deployments/prod/environment.py
  terraform/gitlab/gitlab.tf.json.template.py
Labels: sandbox, orange, reindex:anvilprod, deploy:gitlab, reindex:partial

#6434 Hotfix prod: Snapshot 2ef3655a in dcp40 catalog failed to index due to dangling inputs (#6431)
  deployments/prod/environment.py
Labels: orange, 0 reviews, hotfix, reindex:partial

#6436 Hotfix anvilprod: Snapshot ANVIL_MAS_ISO_seq failed to index in the_ anvil7 catalog (#6433)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
Labels: sandbox, orange, hotfix

#6425 Backport: 7802ee6d (#6335, PR #6422), 61683542 (#6431, PR #6434), 3e1f5971 (#6424, PR #6423) and 6bda7f09 (#6433, PR 6436)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
  deployments/prod/environment.py
Labels: orange, 0 reviews, no sandbox

#6414 Fix: Dependabot is paused (#6406)
  .github/PULL_REQUEST_TEMPLATE/upgrade.md
  .github/pull_request_template.md.template.py
Labels: orange, 0 reviews, no sandbox

#6427 Upgrade dependencies 2024-07-08 (#6389)
  UPGRADING.rst
  environment.boot
  environment.py
  image_manifests.json
  requirements.all.txt
  requirements.dev.trans.txt
  requirements.dev.txt
  requirements.pip.txt
  terraform/_schema.json.gz
  terraform/gitlab/gitlab.tf.json.template.py
Labels: sandbox, orange, reqs, upgrade, deploy:gitlab, deploy:shared, deploy:runner, backup:gitlab

#6384 Content Security Policy (CSP) Not Implemented (DataBiosphere/azul-private#6)
  lambdas/service/app.py
  src/azul/chalice.py
  swagger/oauth2-redirect.html.template.mustache
  swagger/swagger-ui.html.template.mustache
  test/service/test_app_logging.py
  test/test_app_logging.py
Labels: sandbox, orange, 2 reviews
