Repository DataBiosphere/azul, pull requests merged in 2024-09, with the labels that each got.

#6535 Explicitly configure source type in environment files (#6355)
  UPGRADING.rst
  deployments/anvilbox/environment.py
  deployments/anvildev/environment.py
  deployments/anvilprod/environment.py
  deployments/dev/environment.py
  deployments/hammerbox/environment.py
  deployments/prod/environment.py
  deployments/sandbox/environment.py
  deployments/tempdev/environment.py
Labels: sandbox, orange, no demo, partial, 0 reviews, upgrade

#6540 Backport: 347b2fb (#6521, PR #6525)
  deployments/prod/environment.py
Labels: sandbox, orange, 1 review

#6545 Promotion 2024-09-03 anvilprod (#6539)
  .github/PULL_REQUEST_TEMPLATE/anvilprod-promotion.md
  .github/PULL_REQUEST_TEMPLATE/prod-promotion.md
  .github/PULL_REQUEST_TEMPLATE/upgrade.md
  .github/pull_request_template.md
  .github/pull_request_template.md.template.py
  .github/workflows/ci.yml
  .github/workflows/schedule.py
  Makefile
  UPGRADING.rst
  bin/wheels/runtime/cachetools-5.4.0-py3-none-any.whl
  bin/wheels/runtime/cachetools-5.5.0-py3-none-any.whl
  bin/wheels/runtime/googleapis_common_protos-1.63.2-py2.py3-none-any.whl
  bin/wheels/runtime/googleapis_common_protos-1.64.0-py2.py3-none-any.whl
  bin/wheels/runtime/idna-3.7-py3-none-any.whl
  bin/wheels/runtime/idna-3.8-py3-none-any.whl
  common.mk
  docker_images.json
  environment
  environment.boot
  environment.py
  image_manifests.json
  requirements.all.txt
  requirements.dev.trans.txt
  requirements.trans.txt
  scripts/generate_environment_boot.py
  scripts/manage_images.py
  scripts/rename_resources.py
  src/azul/__init__.py
  src/azul/docker.py
  src/azul/service/async_manifest_service.py
  src/azul/service/manifest_controller.py
  terraform/api_gateway.tf.json.template.py
  terraform/gitlab/gitlab.tf.json.template.py
  terraform/gitlab/runner/Dockerfile
  terraform/gitlab/runner/Makefile
  terraform/shared/shared.tf.json.template.py
  test/service/test_manifest_async.py
Labels: sandbox, orange, 0 reviews, upgrade, deploy:gitlab, deploy:shared, deploy:runner, backup:gitlab

#6544 Promotion 2024-09-03 prod (#6539)
  .github/PULL_REQUEST_TEMPLATE/anvilprod-promotion.md
  .github/PULL_REQUEST_TEMPLATE/prod-promotion.md
  .github/PULL_REQUEST_TEMPLATE/upgrade.md
  .github/pull_request_template.md
  .github/pull_request_template.md.template.py
  .github/workflows/ci.yml
  .github/workflows/schedule.py
  Makefile
  UPGRADING.rst
  bin/wheels/runtime/cachetools-5.4.0-py3-none-any.whl
  bin/wheels/runtime/cachetools-5.5.0-py3-none-any.whl
  bin/wheels/runtime/googleapis_common_protos-1.63.2-py2.py3-none-any.whl
  bin/wheels/runtime/googleapis_common_protos-1.64.0-py2.py3-none-any.whl
  bin/wheels/runtime/idna-3.7-py3-none-any.whl
  bin/wheels/runtime/idna-3.8-py3-none-any.whl
  common.mk
  docker_images.json
  environment
  environment.boot
  environment.py
  image_manifests.json
  requirements.all.txt
  requirements.dev.trans.txt
  requirements.trans.txt
  scripts/generate_environment_boot.py
  scripts/manage_images.py
  scripts/rename_resources.py
  src/azul/__init__.py
  src/azul/docker.py
  src/azul/service/async_manifest_service.py
  src/azul/service/manifest_controller.py
  terraform/api_gateway.tf.json.template.py
  terraform/gitlab/gitlab.tf.json.template.py
  terraform/gitlab/runner/Dockerfile
  terraform/gitlab/runner/Makefile
  terraform/shared/shared.tf.json.template.py
  test/service/test_manifest_async.py
Labels: orange, 0 reviews, no sandbox, upgrade, deploy:gitlab, deploy:shared, deploy:runner, backup:gitlab

#6548 Upgrade dependencies 2024-09-02 (#6537)
  bin/wheels/runtime/certifi-2024.7.4-py3-none-any.whl
  bin/wheels/runtime/certifi-2024.8.30-py3-none-any.whl
  bin/wheels/runtime/cffi-1.17.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  bin/wheels/runtime/cffi-1.17.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  bin/wheels/runtime/cryptography-43.0.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  bin/wheels/runtime/cryptography-43.0.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  bin/wheels/runtime/google_crc32c-1.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  bin/wheels/runtime/google_crc32c-1.6.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  bin/wheels/runtime/googleapis_common_protos-1.64.0-py2.py3-none-any.whl
  bin/wheels/runtime/googleapis_common_protos-1.65.0-py2.py3-none-any.whl
  docker_images.json
  environment.boot
  environment.py
  requirements.all.txt
  requirements.dev.trans.txt
  requirements.trans.txt
  terraform/_schema.json.gz
Labels: sandbox, orange, reqs, deploy:gitlab, deploy:shared, deploy:runner, backup:gitlab

#6567 Hotfix prod: Index dcp42 in prod and make dcp41 default (#6556, #6558)
  deployments/prod/environment.py
Labels: orange, 1 review, no sandbox, hotfix, reindex:prod, reindex:partial

#6553 Fix: AWS Security Hub: CIS AWS Foundations Benchmark Critical and High Finding (DataBiosphere/azul-private#173)
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, 0 reviews, no sandbox, deploy:gitlab

#6568 Deploy browser site for LungMAP dev as TF component of Azul (#6346)
  deployments/dev.browser/environment.py
  terraform/browser/browser.tf.json.template.py
Labels: sandbox, orange

#6569 Backport: 5a23ace8 (#6558, PR #6567) & 6f07fadf (#6556, PR #6567)
  deployments/prod/environment.py
Labels: orange, no sandbox

#6207 Support for HCA data_use_restriction (#6131)
  lambdas/service/app.py
  lambdas/service/openapi.json
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  src/azul/plugins/metadata/hca/service/response.py
  src/humancellatlas/data/metadata/api.py
  test/indexer/data/80baee6e-00a5-4fdc-bfe3-d339ff8a7178.dss.hca.json
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.results.json
  test/service/data/pfb_manifest.results.json
  test/service/data/pfb_manifest.schema.json
  test/service/test_index_projects.py
  test/service/test_response.py
Labels: sandbox, orange, API, 4+ reviews, reindex:dev, reindex:prod

#6573 Promotion 2024-10-16 prod (#6571)
  OPERATOR.rst
  bin/wheels/runtime/certifi-2024.7.4-py3-none-any.whl
  bin/wheels/runtime/certifi-2024.8.30-py3-none-any.whl
  bin/wheels/runtime/cffi-1.17.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  bin/wheels/runtime/cffi-1.17.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  bin/wheels/runtime/cryptography-43.0.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  bin/wheels/runtime/cryptography-43.0.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  bin/wheels/runtime/google_crc32c-1.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  bin/wheels/runtime/google_crc32c-1.6.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  bin/wheels/runtime/googleapis_common_protos-1.64.0-py2.py3-none-any.whl
  bin/wheels/runtime/googleapis_common_protos-1.65.0-py2.py3-none-any.whl
  deployments/anvildev.browser/environment.py
  deployments/anvilprod.browser/environment.py
  deployments/dev.browser/environment.py
  deployments/tempdev.browser/environment.py
  deployments/tempdev/environment.py
  docker_images.json
  environment
  environment.boot
  environment.py
  requirements.all.txt
  requirements.dev.trans.txt
  requirements.trans.txt
  scripts/rename_resources.py
  src/azul/__init__.py
  src/azul/terraform.py
  terraform/_schema.json.gz
  terraform/browser/browser.tf.json.template.py
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, no sandbox, deploy:gitlab, deploy:shared, deploy:runner, backup:gitlab

#5635 Eliminate azul.terra.TDRClient.TDRSource (#5524)
  scripts/post_deploy_tdr.py
  scripts/update_subgraph_counts.py
  src/azul/plugins/repository/tdr.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/plugins/repository/tdr_hca/__init__.py
  src/azul/terra.py
  test/integration_test.py
  test/service/test_response.py
Labels: sandbox, orange, 0 reviews

#6572 Promotion 2024-10-16 anvilprod (#6571)
  OPERATOR.rst
  bin/wheels/runtime/certifi-2024.7.4-py3-none-any.whl
  bin/wheels/runtime/certifi-2024.8.30-py3-none-any.whl
  bin/wheels/runtime/cffi-1.17.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  bin/wheels/runtime/cffi-1.17.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  bin/wheels/runtime/cryptography-43.0.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  bin/wheels/runtime/cryptography-43.0.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  bin/wheels/runtime/google_crc32c-1.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  bin/wheels/runtime/google_crc32c-1.6.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  bin/wheels/runtime/googleapis_common_protos-1.64.0-py2.py3-none-any.whl
  bin/wheels/runtime/googleapis_common_protos-1.65.0-py2.py3-none-any.whl
  deployments/anvildev.browser/environment.py
  deployments/anvilprod.browser/environment.py
  deployments/dev.browser/environment.py
  deployments/prod/environment.py
  deployments/tempdev.browser/environment.py
  deployments/tempdev/environment.py
  docker_images.json
  environment
  environment.boot
  environment.py
  requirements.all.txt
  requirements.dev.trans.txt
  requirements.trans.txt
  scripts/rename_resources.py
  src/azul/__init__.py
  src/azul/terraform.py
  terraform/_schema.json.gz
  terraform/browser/browser.tf.json.template.py
  terraform/gitlab/gitlab.tf.json.template.py
Labels: sandbox, orange, deploy:gitlab, deploy:shared, deploy:runner, backup:gitlab

#6585 Hotfix prod: Deploy browser site for HCA prod as TF component of Azul (#6344)
  deployments/prod.browser/environment.py
  environment
Labels: orange, no sandbox, hotfix

#6578 Upgrade dependencies 2024-09-16 (#6570)
  UPGRADING.rst
  bin/wheels/runtime/idna-3.10-py3-none-any.whl
  bin/wheels/runtime/idna-3.8-py3-none-any.whl
  bin/wheels/runtime/protobuf-4.25.4-cp37-abi3-manylinux2014_x86_64.whl
  bin/wheels/runtime/protobuf-4.25.5-cp37-abi3-manylinux2014_x86_64.whl
  bin/wheels/runtime/pyasn1-0.6.0-py2.py3-none-any.whl
  bin/wheels/runtime/pyasn1-0.6.1-py3-none-any.whl
  bin/wheels/runtime/pyasn1_modules-0.4.0-py3-none-any.whl
  bin/wheels/runtime/pyasn1_modules-0.4.1-py3-none-any.whl
  bin/wheels/runtime/pytz-2024.1-py2.py3-none-any.whl
  bin/wheels/runtime/pytz-2024.2-py2.py3-none-any.whl
  docker_images.json
  environment.boot
  environment.py
  requirements.all.txt
  requirements.dev.trans.txt
  requirements.trans.txt
Labels: sandbox, orange, 1 review, reqs, upgrade, deploy:gitlab, deploy:shared, deploy:runner, backup:gitlab

#6589 Hotfix prod: Deploy browser site for LungMAP prod as a TF component of Azul (#6347)
  deployments/prod.browser/environment.py
Labels: orange, no sandbox, hotfix

#6588 Backport: 96cd562 (#6344, PR #6585) cb830191 (#6347, PR #6589)
  deployments/prod.browser/environment.py
  environment
Labels: orange, no sandbox

#6593 Hotfix prod: Make dcp42 the default catalog (#6586)
  deployments/prod/environment.py
Labels: orange, no sandbox, hotfix, reindex:prod, reindex:partial

#6595 Backports: f535d2e (#6586, PR #6593)
  deployments/prod/environment.py
Labels: orange, no sandbox

#6583 Update PyCharm base image to bookworm (#6575)
  docker_images.json
  environment.py
Labels: sandbox, orange, 0 reviews, deploy:shared

#6579 Promotion 2024-09-17 anvilprod (#6576)
  lambdas/service/app.py
  lambdas/service/openapi.json
  scripts/post_deploy_tdr.py
  scripts/update_subgraph_counts.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  src/azul/plugins/metadata/hca/service/response.py
  src/azul/plugins/repository/tdr.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/plugins/repository/tdr_hca/__init__.py
  src/azul/terra.py
  src/humancellatlas/data/metadata/api.py
  test/indexer/data/80baee6e-00a5-4fdc-bfe3-d339ff8a7178.dss.hca.json
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.results.json
  test/integration_test.py
  test/service/data/pfb_manifest.results.json
  test/service/data/pfb_manifest.schema.json
  test/service/test_index_projects.py
  test/service/test_response.py
Labels: sandbox, orange

#6580 Promotion 2024-09-17 prod (#6576)
  lambdas/service/app.py
  lambdas/service/openapi.json
  scripts/post_deploy_tdr.py
  scripts/update_subgraph_counts.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  src/azul/plugins/metadata/hca/service/response.py
  src/azul/plugins/repository/tdr.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/plugins/repository/tdr_hca/__init__.py
  src/azul/terra.py
  src/humancellatlas/data/metadata/api.py
  test/indexer/data/80baee6e-00a5-4fdc-bfe3-d339ff8a7178.dss.hca.json
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.results.json
  test/integration_test.py
  test/service/data/pfb_manifest.results.json
  test/service/data/pfb_manifest.schema.json
  test/service/test_index_projects.py
  test/service/test_response.py
Labels: orange, no sandbox, reindex:prod

#6554 Eliminate RepositoryPlugin.list_partitions (#6531)
  OPERATOR.rst
  UPGRADING.rst
  attic/scripts/update_subgraph_counts.py
  deployments/anvilbox/environment.py
  deployments/anvildev/environment.py
  deployments/anvilprod/environment.py
  deployments/dev/environment.py
  deployments/hammerbox/environment.py
  deployments/prod/environment.py
  deployments/sandbox/environment.py
  deployments/tempdev/environment.py
  scripts/can_bundle.py
  scripts/post_deploy_tdr.py
  src/azul/azulclient.py
  src/azul/indexer/__init__.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/anvil/bundle.py
  src/azul/plugins/metadata/anvil/indexer/aggregate.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/indexer/aggregate.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  src/azul/plugins/metadata/hca/service/aggregation.py
  src/azul/plugins/metadata/hca/service/contributor_matrices.py
  src/azul/plugins/metadata/hca/service/response.py
  src/azul/plugins/repository/canned/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/plugins/repository/tdr_hca/__init__.py
  src/azul/terra.py
  test/integration_test.py
Labels: sandbox, orange, 0 reviews, reindex:dev, upgrade, do not promote, reindex:anvildev, reindex:anvilprod, reindex:prod

#6601 Fix: Integration test does not cover file downloads for AnVIL (#6581)
  test/integration_test.py
Labels: sandbox, orange
