Repository DataBiosphere/azul, pull requests merged in 2024-01, with the labels that each got.

#5828 Upgrade dependencies 2023-12-25 (#5823)
  environment.py
  src/azul/__init__.py
  terraform/gitlab/gitlab.tf.json.template.py
Labels: sandbox, orange, upgrade

#5829 Enable replicas for anvilprod and hammerbox (#5819)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
Labels: sandbox, orange, 0 reviews, reindex

#5841 Make dcp34 the default catalog on prod (#5840)
  deployments/prod/environment.py
Labels: orange, 0 reviews, no sandbox

#5771 Fix: post_deploy script should use a TDR client per thread (#5767)
  scripts/post_deploy_tdr.py
Labels: sandbox, orange, 2 reviews

#5818 Fix: User access tokens are rejected with wrong response status (DataBiosphere/azul-private#126)
  src/azul/oauth2.py
Labels: sandbox, orange, 0 reviews

#5648 Refactor document operations (#5360)
  src/azul/indexer/document.py
  src/azul/indexer/index_service.py
  test/indexer/test_indexer.py
Labels: sandbox, orange, no demo, partial, base, 0 reviews, reindex

#5867 Make lm4 the default catalog for LungMAP prod (#5861)
  deployments/prod/environment.py
Labels: orange, 0 reviews, reindex, no sandbox

#5780 Update Terraform to 1.6.x (#5687, #5656)
  UPGRADING.rst
  environment.boot
  requirements.all.txt
  requirements.dev.trans.txt
  terraform/_schema.json.gz
Labels: orange, 2 reviews, reqs, upgrade

#5881 Fix: Curl manifest can be impacted by rate based WAF rules (DataBiosphere/azul-private#125)
  src/azul/service/manifest_service.py
  terraform/api_gateway.tf.json.template.py
  test/service/test_manifest.py
Labels: orange

#5862 Fix: Subgraph stitching query crashes BQ emulator (#5847)
  UPGRADING.rst
  src/azul/__init__.py
  test/indexer/test_tdr.py
Labels: sandbox, orange, upgrade

#5880 Rename some TF resources in browser component (#5878)
  scripts/rename_resources.py
  terraform/browser/browser.tf.json.template.py
Labels: sandbox, orange

#5853 Fix: Dummy S3 lifecycle rule has auto-generated name (#5848)
  UPGRADING.rst
  src/azul/terraform.py
Labels: sandbox, orange, 1 review, upgrade

#5864 Fix: Curl manifest from dev fails to download (#5811)
  src/azul/service/manifest_service.py
Labels: sandbox, orange, 0 reviews

#5852 Fix: Contribute retry & aggregate throttle thresholds exceeded during prod reindex (#5837)
  lambdas/indexer/app.py
Labels: orange, 0 reviews, no sandbox

#5892 Remove portal site (#5874)
  deployments/anvildev.browser/environment.py
  deployments/anvilprod.browser/environment.py
  terraform/browser/add_google_search_api_key.js
  terraform/browser/browser.tf.json.template.py
Labels: orange, no sandbox

#5758 Suppress Inspector findings for images not used within boundary (#5738)
  UPGRADING.rst
  scripts/kibana_proxy.py
  src/azul/__init__.py
  src/azul/docker.py
  terraform/gitlab/gitlab.tf.json.template.py
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, orange, 2 reviews, upgrade

#5901 Fix: anvil4 breaks IT due to long filters parameter (#5894)
  lambdas/service/app.py
  lambdas/service/openapi.json
  test/integration_test.py
Labels: sandbox, orange, API

#5903 Fix: anvil4 breaks IT due to long filters parameter (#5894)
  lambdas/service/app.py
  lambdas/service/openapi.json
  terraform/api_gateway.tf.json.template.py
  test/integration_test.py
Labels: orange, API

#5868 Index anvil4 in anvilprod (#5759)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
Labels: sandbox, orange, 1 review, reindex

#5885 Fix: Concurrently running GitLab test jobs occasionally time out (#5809)
  .gitlab-ci.yml
  UPGRADING.rst
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, 0 reviews, no sandbox, upgrade

#5689 Fix: GitHub API rate limit exceeded in test_canned_staging_area (#4757, #4438)
  src/azul/plugins/repository/canned/__init__.py
  src/humancellatlas/data/metadata/helpers/staging_area.py
  test/hca_metadata_api/test.py
  test/test_doctests.py
Labels: sandbox, orange, 4+ reviews

#5889 Fix: AWS event GetMacieSession results in AccessDenied error (#5779)
  UPGRADING.rst
  terraform/shared/shared.tf.json.template.py
Labels: orange, 1 review, no sandbox, upgrade
