Repository DataBiosphere/azul, pull requests merged in 2024-02, with the labels that each got.

#5911 Move anvilprod to anvilproject.org domain (#5284)
  README.md
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
  docs/compliance/change_management.rst
  scripts/rename_resources.py
  test/health_check_test_case.py
  test/indexer/test_health_check.py
  test/service/test_health_check.py
Labels: sandbox, orange

#5879 Fix: tdr_anvil's fetch_bundle lacks test coverage (#5046, #5898)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  test/indexer/data/826dea02-e274-affe-aabc-eb3db63ad068.results.json
  test/indexer/data/826dea02-e274-affe-aabc-eb3db63ad068.tables.tdr.json
  test/indexer/data/826dea02-e274-affe-aabc-eb3db63ad068.tdr.anvil.json
  test/indexer/test_anvil.py
  test/indexer/test_tdr.py
Labels: sandbox, orange, 0 reviews, reindex

#5915 Fix: Lambda `servicecachehealth` times out (#5467, #5622)
  UPGRADING.rst
  terraform/gitlab/gitlab.tf.json.template.py
Labels: orange, 1 review, no sandbox, upgrade

#5948 Refer to Docker images by repository digest (#4593, #5188, #5832)
  .github/PULL_REQUEST_TEMPLATE/upgrade.md
  .github/pull_request_template.md
  .github/pull_request_template.md.template.py
  Makefile
  README.md
  UPGRADING.rst
  environment.py
  image_manifests.json
  requirements.all.txt
  requirements.dev.trans.txt
  requirements.dev.txt
  scripts/kibana_proxy.py
  scripts/manage_images.py
  src/azul/__init__.py
  src/azul/__main__.py
  src/azul/docker.py
  terraform/shared/shared.tf.json.template.py
  test/docker_container_test_case.py
  test/test_doctests.py
Labels: sandbox, orange, reqs, upgrade

#5936 Make anvil4 the default catalog and remove anvil3 (#5907)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
Labels: sandbox, orange, 0 reviews, reindex

#5955 Index dcp35 in prod (#5949)
  deployments/prod/environment.py
Labels: orange, 0 reviews, no sandbox, reindex:prod, reindex:partial

#5888 Support for HCA bionetworks and atlases (#5519)
  lambdas/service/app.py
  lambdas/service/openapi.json
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/indexer/aggregate.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  src/azul/plugins/metadata/hca/service/response.py
  src/humancellatlas/data/metadata/api.py
  test/indexer/data/2c7d06b8-658e-4c51-9de4-a768322f84c5.dss.hca.json
  test/indexer/data/587d74b4-1075-4bbf-b96a-4d1ede0481b2.dss.hca.json
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.results.json
  test/indexer/data/ffac201f-4b1c-4455-bd58-19c1a9e863b4.dss.hca.json
  test/service/data/pfb_manifest.results.json
  test/service/data/pfb_manifest.schema.json
  test/service/test_index_projects.py
  test/service/test_response.py
Labels: sandbox, orange, API, 0 reviews, reindex:dev, reindex:prod

#5962 Promotion 2024-02-15 (#5961)
  .github/PULL_REQUEST_TEMPLATE/upgrade.md
  .github/pull_request_template.md
  .github/pull_request_template.md.template.py
  Makefile
  README.md
  UPGRADING.rst
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
  deployments/prod/environment.py
  environment.py
  image_manifests.json
  requirements.all.txt
  requirements.dev.trans.txt
  requirements.dev.txt
  scripts/kibana_proxy.py
  scripts/manage_images.py
  src/azul/__init__.py
  src/azul/__main__.py
  src/azul/docker.py
  terraform/shared/shared.tf.json.template.py
  test/docker_container_test_case.py
  test/test_doctests.py
Labels: orange, no sandbox, upgrade, reindex:prod

#5963 Fix logging of systemd units running `docker exec` (#5728)
  UPGRADING.rst
  terraform/gitlab/gitlab.tf.json.template.py
Labels: sandbox, orange, 0 reviews, upgrade

#5947 Fix: Wrong content type in 302 response from non-fetch manifest endpoint (#5932)
  src/azul/service/manifest_controller.py
  test/service/test_manifest.py
Labels: sandbox, orange, API, 0 reviews

#5945 Add unit test coverage for supplementary bundles (#5934)
  src/azul/plugins/repository/tdr_anvil/__init__.py
  test/indexer/data/6b0f6c0f-5d80-a242-accb-840921351cd5.tables.tdr.json
  test/indexer/data/6b0f6c0f-5d80-a242-accb-840921351cd5.tdr.anvil.json
  test/indexer/test_anvil.py
  test/service/test_response_anvil.py
Labels: sandbox, orange, 1 review, base

#5930 Fix: Curl manifest can be impacted by rate based WAF rules (DataBiosphere/azul-private#125)
  src/azul/__init__.py
  src/azul/service/manifest_service.py
  terraform/api_gateway.tf.json.template.py
  test/service/test_manifest.py
Labels: sandbox, orange, 3 reviews

#5950 Propagate 429 responses from DRS and TDR (#5921)
  src/azul/drs.py
  src/azul/http.py
  src/azul/service/repository_controller.py
  src/azul/service/source_controller.py
  src/azul/terra.py
Labels: sandbox, orange, 0 reviews

#5490 Track Replica hub IDs (#5360)
  src/azul/indexer/document.py
  src/azul/indexer/index_controller.py
  src/azul/indexer/index_service.py
  src/azul/indexer/transform.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  test/indexer/data/826dea02-e274-affe-aabc-eb3db63ad068.results.json
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.results.json
  test/indexer/test_indexer.py
Labels: sandbox, orange, 2 reviews, reindex:dev, reindex:anvildev, reindex:anvilprod, reindex:prod

#5973 Promotion 2024-02-21 (#5972)
  UPGRADING.rst
  lambdas/service/app.py
  lambdas/service/openapi.json
  src/azul/docker.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/indexer/aggregate.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  src/azul/plugins/metadata/hca/service/response.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/service/manifest_controller.py
  src/humancellatlas/data/metadata/api.py
  terraform/gitlab/gitlab.tf.json.template.py
  test/indexer/data/2c7d06b8-658e-4c51-9de4-a768322f84c5.dss.hca.json
  test/indexer/data/587d74b4-1075-4bbf-b96a-4d1ede0481b2.dss.hca.json
  test/indexer/data/6b0f6c0f-5d80-a242-accb-840921351cd5.tables.tdr.json
  test/indexer/data/6b0f6c0f-5d80-a242-accb-840921351cd5.tdr.anvil.json
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.results.json
  test/indexer/data/ffac201f-4b1c-4455-bd58-19c1a9e863b4.dss.hca.json
  test/indexer/test_anvil.py
  test/service/data/pfb_manifest.results.json
  test/service/data/pfb_manifest.schema.json
  test/service/test_index_projects.py
  test/service/test_manifest.py
  test/service/test_response.py
  test/service/test_response_anvil.py
Labels: orange, API, 0 reviews, no sandbox, upgrade, reindex:prod, deploy:gitlab

#5974 Fix: Project `2ef3655a` in dcp35 failed to index (#5971)
  deployments/prod/environment.py
Labels: orange, no sandbox, reindex:prod, reindex:partial

#5994 Upgrade ES domain for Hammerbox (#5975)
  UPGRADING.rst
  deployments/hammerbox/environment.py
Labels: sandbox, orange, partial, 0 reviews, upgrade

#5954 Fix: Transient IT failure for managed_access_repository_files with empty iterable (#5924)
  test/integration_test.py
Labels: sandbox, orange, 1 review

#5998 Promotion 2024-02-28 (#5997)
  src/azul/__init__.py
  src/azul/service/manifest_service.py
  terraform/api_gateway.tf.json.template.py
  test/service/test_manifest.py
Labels: orange, no sandbox

#5983 Simplify and streamline operator items in PR checklist (#5978)
  .github/ISSUE_TEMPLATE/blank.md
  .github/PULL_REQUEST_TEMPLATE/backport.md
  .github/PULL_REQUEST_TEMPLATE/hotfix.md
  .github/PULL_REQUEST_TEMPLATE/promotion.md
  .github/PULL_REQUEST_TEMPLATE/upgrade.md
  .github/pull_request_template.md
  .github/pull_request_template.md.template.py
  .github/replies/README.md
  .github/replies/security_design_review.md
  src/azul/__init__.py
  src/azul/template.py
Labels: sandbox, orange
