Repository DataBiosphere/azul, pull requests merged in 2025-04, with the labels that each got.

#7000 Backport: 2a9ee23 (#6997, PR #6999)
  deployments/prod/environment.py
Labels: sandbox, orange, 1 review

#7001 Make anvil9 default catalog and remove anvil8 (#6991)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
Labels: orange, 1 review, no sandbox, reindex:anvilprod, reindex:partial

#7004 Index dcp47 in prod (#6952)
  deployments/prod/environment.py
Labels: orange, no sandbox, reindex:prod, reindex:partial

#6919 Fix: Transient IT test_snapshot_listing fails in anvilbox (#5096)
  test/integration_test.py
Labels: sandbox, orange, 1 review

#6995 Fix: Verbatim PFB handover fails when using a common prefix (#6843)
  src/azul/indexer/__init__.py
  src/azul/indexer/document.py
  src/azul/indexer/index_service.py
  src/azul/indexer/transform.py
  src/azul/service/avro_pfb.py
  src/azul/service/manifest_service.py
  test/indexer/data/826dea02-e274-affe-aabc-eb3db63ad068.results.json
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.results.json
  test/indexer/test_indexer.py
  test/service/test_manifest.py
Labels: sandbox, orange, 1 review, reindex:dev, reindex:anvildev, reindex:anvilprod, reindex:prod

#6973 Replicate replica indices (#6965)
  src/azul/indexer/index_service.py
Labels: sandbox, orange, 0 reviews, reindex:dev, reindex:anvildev, reindex:anvilprod, reindex:prod

#7033 Hotfix prod: Unexpected schema domains in `dcp47` snapshot (#6955)
  deployments/prod/environment.py
Labels: sandbox, orange, 0 reviews, hotfix

#7003 Upgrade dependencies 2025-03-31 (#7002)
  bin/wheels/runtime/boto3-1.37.15-py3-none-any.whl
  bin/wheels/runtime/boto3-1.37.24-py3-none-any.whl
  bin/wheels/runtime/pyasn1_modules-0.4.1-py3-none-any.whl
  bin/wheels/runtime/pyasn1_modules-0.4.2-py3-none-any.whl
  bin/wheels/runtime/setuptools-76.1.0-py3-none-any.whl
  bin/wheels/runtime/setuptools-78.1.0-py3-none-any.whl
  bin/wheels/runtime/typing_extensions-4.13.0-py3-none-any.whl
  bin/wheels/runtime/typing_extensions-4.13.2-py3-none-any.whl
  docker_images.json
  environment.py
  requirements.all.txt
  requirements.dev.trans.txt
  requirements.dev.txt
  requirements.pip.txt
  requirements.trans.txt
  requirements.txt
  scripts/update_swagger.py
  swagger/swagger-ui-bundle.js
  test/service/test_manifest_async.py
Labels: sandbox, orange, reqs, deploy:gitlab, deploy:shared, backup:gitlab

#7013 Fix: File downloads using curl manifest.do not retry on 429 (#6970)
  src/azul/service/manifest_service.py
  test/service/test_manifest.py
Labels: sandbox, orange, 0 reviews

#7036 Backport: 99e60a0a (#6955, #PR 7033)
  deployments/prod/environment.py
Labels: orange, no sandbox

#7029 Fix CVE-2024-24790 in BQ emulator image, add arm64 version (DataBiosphere/azul-private#229, #6090)
  docker_images.json
  environment.py
  test/indexer/test_tdr.py
Labels: sandbox, orange, deploy:shared

#7017 Fix: Mirroring script is broken (#7009)
  scripts/mirror.py
Labels: sandbox, orange, 0 reviews

#7016 Fix: AzulClient.remote_mirror spends a lot of time partitioning sources (#7011, #3133)
  .github/workflows/ci.yml
  .github/workflows/schedule.yaml
  lambdas/layer/.chalice/config.json.template.py
  lambdas/service/app.py
  scripts/generate_environment_boot.py
  scripts/import_api_gateway_stage.py
  scripts/import_cloudwatch_log_groups.py
  scripts/import_default_vpc.py
  scripts/sell_unused_slots.py
  src/azul/__init__.py
  src/azul/auth.py
  src/azul/azulclient.py
  src/azul/health.py
  src/azul/indexer/action_controller.py
  src/azul/indexer/document.py
  src/azul/indexer/field.py
  src/azul/indexer/index_controller.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/anvil/service/response.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr_hca/__init__.py
  src/azul/service/catalog_controller.py
  src/azul/uuids.py
  terraform/browser/browser.tf.json.template.py
  test/hca_metadata_api/test.py
  test/service/__init__.py
  test/service/test_manifest_async.py
  test/test_deployment.py
Labels: sandbox, orange, 1 review

#7035 Add column for affected component to inspector findings sheet (#6986)
  scripts/export_inspector_findings.py
Labels: orange, 0 reviews, no sandbox

#7042 Fix: test_can_bundle_configured_catalogs fails with specific seed (#6928)
  src/azul/plugins/repository/tdr_anvil/__init__.py
  test/integration_test.py
Labels: sandbox, orange, 0 reviews

#7053 Backport: dbcfe1ca (#7037, #PR 7052)
  deployments/prod/environment.py
Labels: orange, no sandbox

#7038 Thin out GitLab data volume backups (#7030)
  .github/ISSUE_TEMPLATE/prune_gitlab_backups.md
Labels: orange, 0 reviews, no sandbox

#7058 Fix: Cannot resume curl manifest file downloads (#6969)
  src/azul/service/repository_controller.py
Labels: orange, 0 reviews

#7025 Block requests from abusive Google Apps Scripts (#6980)
  src/azul/__init__.py
  terraform/api_gateway.tf.json.template.py
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, orange, 3 reviews, deploy:shared

#7061 Index lm9 in LungMAP (#7057)
  deployments/prod/environment.py
Labels: orange, 0 reviews, no sandbox, reindex:prod, reindex:partial

#7048 Fix: Mirror script does not fail early when fail queue is nonempty (#6860, #7046)
  .mypy.ini
  scripts/mirror.py
  scripts/mirror_file.py
  src/azul/azulclient.py
  src/azul/indexer/action_controller.py
  src/azul/indexer/index_controller.py
  src/azul/indexer/mirror_controller.py
  src/azul/queues.py
Labels: sandbox, orange, 1 review

#7077 Encapsulate repository files as an attrs class (#6861)
  .mypy.ini
  lambdas/service/app.py
  scripts/mirror_file.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/repository/canned/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr.py
  src/azul/plugins/repository/tdr_hca/__init__.py
  src/azul/service/__init__.py
  src/azul/service/app_controller.py
  src/azul/service/catalog_controller.py
  src/azul/service/drs_controller.py
  src/azul/service/repository_controller.py
  src/azul/service/repository_service.py
  src/azul/service/source_controller.py
  test/indexer/data/1b6d8348-d6e9-406a-aa6a-7ee886e52bf9.tdr.hca.json
  test/indexer/data/4426adc5-b3c5-5aab-ab86-51d8ce44dfbe.tdr.hca.json
  test/service/test_repository_files.py
  test/test_doctests.py
Labels: sandbox, orange, no demo, partial, base, 0 reviews

#7080 Hotfix prod: Index lm9 in LungMAP (#7057)
  deployments/prod/environment.py
Labels: orange, no sandbox, hotfix, reindex:prod, reindex:partial

#7086 Backport: 547a3602 (#7057, PR #7080), 1eba4207, 9ac4fa4c, 716eebf6, abafeb1f, 3dbab113 (#7081), 94dedc48
  deployments/prod/environment.py
Labels: orange, no sandbox
