Repository DataBiosphere/azul, pull requests merged in 2025-05, with the labels that each got.

#7075 Some fixes to mirror documentation (#6938)
  docs/mirror.rst
Labels: orange, partial, no sandbox

#6946 Implement mirror_partition (#6861)
  scripts/post_deploy_tdr.py
  src/azul/azulclient.py
  src/azul/indexer/mirror_controller.py
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/canned/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/plugins/repository/tdr_hca/__init__.py
  test/indexer/test_mirror_controller.py
  test/integration_test.py
Labels: sandbox, orange, base, 0 reviews

#7085 Block requests from abusive Google Apps Scripts (#6980)
  terraform/shared/shared.tf.json.template.py
Labels: orange, 0 reviews, deploy:shared

#7072 Index dcp48 in prod (#7064)
  deployments/prod/environment.py
Labels: orange, 0 reviews, no sandbox, reindex:prod, reindex:partial

#7088 Promotion 2025-04-29 anvilprod (#7082)
  .mypy.ini
  deployments/prod/environment.py
  lambdas/service/app.py
  scripts/mirror.py
  scripts/mirror_file.py
  src/azul/__init__.py
  src/azul/azulclient.py
  src/azul/indexer/action_controller.py
  src/azul/indexer/index_controller.py
  src/azul/indexer/mirror_controller.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/repository/canned/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr.py
  src/azul/plugins/repository/tdr_hca/__init__.py
  src/azul/queues.py
  src/azul/service/__init__.py
  src/azul/service/app_controller.py
  src/azul/service/catalog_controller.py
  src/azul/service/drs_controller.py
  src/azul/service/repository_controller.py
  src/azul/service/repository_service.py
  src/azul/service/source_controller.py
  terraform/api_gateway.tf.json.template.py
  terraform/shared/shared.tf.json.template.py
  test/indexer/data/1b6d8348-d6e9-406a-aa6a-7ee886e52bf9.tdr.hca.json
  test/indexer/data/4426adc5-b3c5-5aab-ab86-51d8ce44dfbe.tdr.hca.json
  test/service/test_repository_files.py
  test/test_doctests.py
Labels: sandbox, orange, deploy:shared

#7087 Promotion 2025-04-29 prod (#7082)
  .mypy.ini
  lambdas/service/app.py
  scripts/mirror.py
  scripts/mirror_file.py
  src/azul/__init__.py
  src/azul/azulclient.py
  src/azul/indexer/action_controller.py
  src/azul/indexer/index_controller.py
  src/azul/indexer/mirror_controller.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/repository/canned/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr.py
  src/azul/plugins/repository/tdr_hca/__init__.py
  src/azul/queues.py
  src/azul/service/__init__.py
  src/azul/service/app_controller.py
  src/azul/service/catalog_controller.py
  src/azul/service/drs_controller.py
  src/azul/service/repository_controller.py
  src/azul/service/repository_service.py
  src/azul/service/source_controller.py
  terraform/api_gateway.tf.json.template.py
  terraform/shared/shared.tf.json.template.py
  test/indexer/data/1b6d8348-d6e9-406a-aa6a-7ee886e52bf9.tdr.hca.json
  test/indexer/data/4426adc5-b3c5-5aab-ab86-51d8ce44dfbe.tdr.hca.json
  test/service/test_repository_files.py
  test/test_doctests.py
Labels: orange, no sandbox, deploy:shared

#7043 Implement mirror_file, mirror_part & finalize_file (#6862)
  .mypy.ini
  lambdas/indexer/.chalice/config.json.template.py
  scripts/mirror.py
  scripts/mirror_file.py
  src/azul/azulclient.py
  src/azul/indexer/lambda_iam_policy.py
  src/azul/indexer/mirror_controller.py
  src/azul/indexer/mirror_service.py
  src/azul/service/storage_service.py
  test/indexer/test_mirror_controller.py
Labels: sandbox, orange, 1 review, base

#7093 Fix: Azul uses deprecated SQS endpoints (#4560)
  environment.py
  src/azul/__init__.py
Labels: sandbox, orange, 0 reviews

#7090 Verify digest of file objects in mirror (#7069, #7089)
  .mypy.ini
  bin/wheels/runtime/resumablesha256-1.0-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  requirements.all.txt
  requirements.dev.trans.txt
  requirements.txt
  scripts/mirror.py
  scripts/mirror_file.py
  scripts/reindex.py
  scripts/validate_snapshots.py
  src/azul/args.py
  src/azul/azulclient.py
  src/azul/digests.py
  src/azul/indexer/lambda_iam_policy.py
  src/azul/indexer/mirror_controller.py
  src/azul/indexer/mirror_service.py
  src/azul/service/storage_service.py
  test/indexer/test_mirror_controller.py
Labels: sandbox, orange, 0 reviews, reqs, python

#7097 Populate schema property in info objects (#7076)
  .mypy.ini
  UPGRADING.rst
  docs/mirror.rst
  lambdas/indexer/app.py
  lambdas/indexer/openapi.json
  lambdas/indexer/vendor/resources/static/schemas
  lambdas/service/app.py
  requirements.all.txt
  requirements.dev.trans.txt
  requirements.dev.txt
  schemas/mirror/info/v1.json
  scripts/mirror_file.py
  src/azul/azulclient.py
  src/azul/chalice.py
  src/azul/health.py
  src/azul/indexer/mirror_controller.py
  src/azul/indexer/mirror_service.py
  src/azul/types.py
  test/azul_test_case.py
  test/indexer/test_mirror_controller.py
Labels: sandbox, orange, API, 1 review, base, reqs, upgrade

#7098 Add CL item for sprint assignment to promotion issue template (#6930)
  .github/ISSUE_TEMPLATE/promotion.md
  .github/PULL_REQUEST_TEMPLATE/anvilprod-promotion.md
  .github/PULL_REQUEST_TEMPLATE/prod-promotion.md
  .github/pull_request_template.md.template.py
Labels: sandbox, orange, 0 reviews

#7120 Promotion 2025-05-13 prod (#7112)
  .github/ISSUE_TEMPLATE/promotion.md
  .github/PULL_REQUEST_TEMPLATE/anvilprod-promotion.md
  .github/PULL_REQUEST_TEMPLATE/prod-promotion.md
  .github/pull_request_template.md.template.py
  .mypy.ini
  UPGRADING.rst
  bin/wheels/runtime/resumablesha256-1.0-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  deployments/prod/environment.py
  docs/mirror.rst
  environment.py
  lambdas/indexer/.chalice/config.json.template.py
  lambdas/indexer/app.py
  lambdas/indexer/openapi.json
  lambdas/indexer/vendor/resources/static/schemas
  lambdas/service/app.py
  requirements.all.txt
  requirements.dev.trans.txt
  requirements.dev.txt
  requirements.txt
  schemas/mirror/info/v1.json
  scripts/mirror.py
  scripts/mirror_file.py
  scripts/reindex.py
  scripts/validate_snapshots.py
  src/azul/__init__.py
  src/azul/args.py
  src/azul/azulclient.py
  src/azul/chalice.py
  src/azul/digests.py
  src/azul/health.py
  src/azul/indexer/lambda_iam_policy.py
  src/azul/indexer/mirror_controller.py
  src/azul/indexer/mirror_service.py
  src/azul/service/storage_service.py
  src/azul/types.py
  terraform/gitlab/gitlab.tf.json.template.py
  test/azul_test_case.py
  test/indexer/test_mirror_controller.py
Labels: orange, API, base, no sandbox, reqs, upgrade, hotfix, deploy:gitlab

#6903 Fix: Alarm api_unauthorized for HeadBucket from AWS Config (#6134)
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, hold warm, orange, 0 reviews, deploy:shared

#7116 Improve logging in mirror controller and service (partial #7109)
  src/azul/indexer/mirror_controller.py
  src/azul/indexer/mirror_service.py
Labels: orange, no demo, partial, 0 reviews, no sandbox, hotfix

#7124 Prefer mirrored copy of files for direct downloads (#7122, #7123)
  deployments/prod/environment.py
  src/azul/indexer/mirror_controller.py
  src/azul/indexer/mirror_service.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/repository/tdr_hca/__init__.py
  src/azul/service/lambda_iam_policy.py
  src/azul/service/repository_controller.py
  test/indexer/test_mirror_controller.py
  test/service/test_repository_files.py
Labels: orange, 0 reviews, no sandbox, hotfix

#7158 Fix: Various mirror issues (#7148, #7153)
  lambdas/indexer/.chalice/config.json.template.py
  src/azul/service/repository_controller.py
  test/indexer/test_mirror_controller.py
  test/service/__init__.py
  test/service/test_repository_files.py
Labels: sandbox, orange, 2 reviews

#7155 Index dcp49 in prod (#7115, #7143)
  deployments/prod/environment.py
Labels: orange, 0 reviews, no sandbox, reindex:prod, reindex:partial

#7161 Promotion 2025-05-20 anvilprod (#7144)
  .github/ISSUE_TEMPLATE/promotion.md
  .github/PULL_REQUEST_TEMPLATE/anvilprod-promotion.md
  .github/PULL_REQUEST_TEMPLATE/prod-promotion.md
  .github/pull_request_template.md.template.py
  .mypy.ini
  UPGRADING.rst
  bin/wheels/runtime/resumablesha256-1.0-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  deployments/prod/environment.py
  docs/mirror.rst
  environment.py
  lambdas/indexer/.chalice/config.json.template.py
  lambdas/indexer/app.py
  lambdas/indexer/openapi.json
  lambdas/indexer/vendor/resources/static/schemas
  lambdas/service/app.py
  requirements.all.txt
  requirements.dev.trans.txt
  requirements.dev.txt
  requirements.txt
  schemas/mirror/info/v1.json
  scripts/mirror.py
  scripts/mirror_file.py
  scripts/reindex.py
  scripts/validate_snapshots.py
  src/azul/__init__.py
  src/azul/args.py
  src/azul/azulclient.py
  src/azul/chalice.py
  src/azul/deployment.py
  src/azul/digests.py
  src/azul/health.py
  src/azul/indexer/lambda_iam_policy.py
  src/azul/indexer/mirror_controller.py
  src/azul/indexer/mirror_service.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/repository/tdr_hca/__init__.py
  src/azul/service/lambda_iam_policy.py
  src/azul/service/repository_controller.py
  src/azul/service/storage_service.py
  src/azul/terraform.py
  src/azul/types.py
  terraform/gitlab/gitlab.tf.json.template.py
  terraform/shared/shared.tf.json.template.py
  test/azul_test_case.py
  test/indexer/test_mirror_controller.py
  test/service/__init__.py
  test/service/test_repository_files.py
Labels: sandbox, orange, API, reqs, deploy:gitlab, deploy:shared

#7160 Promotion 2025-05-20 prod (#7144)
  deployments/prod/environment.py
  lambdas/indexer/.chalice/config.json.template.py
  src/azul/service/repository_controller.py
  terraform/shared/shared.tf.json.template.py
  test/indexer/test_mirror_controller.py
  test/service/__init__.py
  test/service/test_repository_files.py
Labels: orange, no sandbox, reindex:prod, deploy:shared, reindex:partial

#7138 Fix: Alarm api_unauthorized for HeadBucket/Object from SSM agent (#6141)
  terraform/gitlab/gitlab.tf.json.template.py
Labels: sandbox, orange, 0 reviews, deploy:gitlab

#7140 Fix: Missing TF dependency between queue and lambda resources (#7050)
  src/azul/terraform.py
Labels: sandbox, orange, 0 reviews

#7167 Hotfix prod: Unexpected schema domains in dcp49 snapshot (#6955)
  deployments/prod/environment.py
Labels: orange, no sandbox, hotfix

#7141 Make mirror_file fail if file object already exists (#7134)
  src/azul/indexer/mirror_controller.py
  src/azul/indexer/mirror_service.py
  src/azul/service/repository_controller.py
  src/azul/service/storage_service.py
  test/indexer/test_mirror_controller.py
  test/service/test_repository_files.py
Labels: sandbox, orange, 1 review

#7162 Ensure mirror.py does nothing when invoked without arguments (#7146)
  scripts/mirror.py
Labels: sandbox, orange, 0 reviews

#7121 Schedule issue for monthly web application vulnerability scan (#7100)
  .github/ISSUE_TEMPLATE/web_app_vulnerability_scan.md
Labels: sandbox, orange, 0 reviews

#7175 Backport: b019eb29 (#6955, PR #7167)
  deployments/prod/environment.py
Labels: sandbox, orange

#7181 Fix: ListObject shortcut in mirror_partition does not work (#7173)
  src/azul/indexer/mirror_controller.py
  src/azul/indexer/mirror_service.py
Labels: sandbox, orange, no demo, partial, 0 reviews
