Repository DataBiosphere/azul, pull requests merged in 2025-08, with the labels that each got.

#7330 Fix: WAF blocked alarm too sensitive (#7327)
  terraform/api_gateway.tf.json.template.py
Labels: sandbox, orange, 0 reviews

#7332 Fix: Inconsistent mirror message group IDs (#7125)
  src/azul/indexer/mirror_controller.py
Labels: sandbox, orange, 1 review

#7336 Index anvil11 & remove anvil10 (#7337, #7329)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
Labels: orange, 0 reviews, no sandbox, reindex:anvilprod, reindex:partial

#7276 Fix: CSP: Failure to Define Directive with No Fallback (DataBiosphere/data-browser#4450)
  terraform/browser/browser.tf.json.template.py
Labels: sandbox, orange, 0 reviews

#7225 Fix: Cannot generate unfiltered JSONL manifest in AnVIL (#7190)
  src/azul/service/manifest_service.py
  src/azul/service/storage_service.py
  test/azul_test_case.py
  test/docker_container_test_case.py
  test/service/test_manifest.py
Labels: sandbox, orange, 1 review

#7348 Reintroduce anvil10_sources (#7347)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
Labels: orange, 1 review, no sandbox, reindex:anvilprod, reindex:partial

#7349 Promotion 2025-08-12 prod (#7344)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
  deployments/prod/environment.py
  src/azul/service/manifest_service.py
  src/azul/service/storage_service.py
  terraform/browser/browser.tf.json.template.py
  test/azul_test_case.py
  test/docker_container_test_case.py
  test/service/test_manifest.py
Labels: orange, 0 reviews, no sandbox, reindex:prod, reindex:partial, mirror

#7350 Promotion 2025-08-12 anvilprod (#7344)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
  deployments/prod/environment.py
  src/azul/service/manifest_service.py
  src/azul/service/storage_service.py
  terraform/browser/browser.tf.json.template.py
  test/azul_test_case.py
  test/docker_container_test_case.py
  test/service/test_manifest.py
Labels: sandbox, orange, 0 reviews, reindex:anvilprod, reindex:partial

#7354 Fix: envhook.py falsely warns about variable override (#6320)
  scripts/envhook.py
  scripts/export_environment.py
Labels: sandbox, orange

#7322 Add issue type to existing issues in all repos (#6889)
  .github/ISSUE_TEMPLATE/audited_events_rule_set_review.md
  .github/ISSUE_TEMPLATE/fedramp_inventory_review.md
  .github/ISSUE_TEMPLATE/opensearch_updates.md
  .github/ISSUE_TEMPLATE/promotion.md
  .github/ISSUE_TEMPLATE/prune_gitlab_backups.md
  .github/ISSUE_TEMPLATE/public_access_content_review.md
  .github/ISSUE_TEMPLATE/upgrade.md
  .github/ISSUE_TEMPLATE/vpn_certificate_renewals.md
  .github/ISSUE_TEMPLATE/web_app_vulnerability_scan.md
  .github/workflows/schedule.py
  .github/workflows/schedule.yaml
Labels: sandbox, orange, 0 reviews

#7323 Reorganize source spec parsing (partial #7305)
  .mypy.ini
  attic/scripts/mirror_file.py
  environment.py
  scripts/can_bundle.py
  scripts/find_in_snapshots.py
  scripts/mirror.py
  scripts/post_deploy_tdr.py
  scripts/reindex.py
  src/azul/__init__.py
  src/azul/args.py
  src/azul/azulclient.py
  src/azul/indexer/__init__.py
  src/azul/indexer/index_queue_service.py
  src/azul/indexer/index_repository_service.py
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/canned/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr.py
  src/azul/plugins/repository/tdr_hca/__init__.py
  test/azul_test_case.py
  test/indexer/test_anvil.py
  test/indexer/test_tdr.py
  test/integration_test.py
  test/service/test_response.py
Labels: sandbox, orange, partial, 0 reviews, demo

#7333 Upgrade dependencies 2025-08-04 (#7282, #7328)
  bin/wheels/runtime/boto3-1.39.13-py3-none-any.whl
  bin/wheels/runtime/boto3-1.40.3-py3-none-any.whl
  bin/wheels/runtime/fastavro-1.11.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  bin/wheels/runtime/fastavro-1.12.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl
  bin/wheels/runtime/http_message_signatures-0.7.0-py3-none-any.whl
  bin/wheels/runtime/http_message_signatures-1.0.0-py3-none-any.whl
  docker_images.json
  environment.boot
  environment.py
  requirements.all.txt
  requirements.dev.trans.txt
  requirements.dev.txt
  requirements.pip.txt
  requirements.trans.txt
  requirements.txt
  scripts/update_swagger.py
Labels: sandbox, orange, 0 reviews, reqs, deploy:gitlab, deploy:shared, deploy:runner, backup:gitlab

#7374 Implement resumable MD5 digests; et al (#7288, #7242, #7370)
  .mypy.ini
  bin/wheels/runtime/resumablehash-1.2-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl
  bin/wheels/runtime/resumablesha256-1.0-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  bin/wheels/runtime/typing_extensions-4.14.1-py3-none-any.whl
  bin/wheels/runtime/typing_extensions-4.15.0-py3-none-any.whl
  common.mk
  requirements.all.txt
  requirements.dev.trans.txt
  requirements.dev.txt
  requirements.trans.txt
  requirements.txt
  src/azul/digests.py
  src/azul/indexer/aggregate.py
  src/azul/logging.py
  src/azul/queues.py
  src/azul/service/storage_service.py
Labels: sandbox, orange, reqs

#7358 Make metric alarms more sensitive (DataBiosphere/azul-private#280, DataBiosphere/azul-private#281, DataBiosphere/azul-private#282)
  src/azul/chalice.py
  terraform/api_gateway.tf.json.template.py
  terraform/cloudwatch.tf.json.template.py
  terraform/gitlab/gitlab.tf.json.template.py
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, orange, 3 reviews

#7366 Fix: Repository plugin needlessly duplicates replicas (#7346)
  scripts/can_bundle.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  test/indexer/data/6c87f0e1-509d-46a4-b845-7584df39263b.tables.tdr.json
  test/indexer/data/826dea02-e274-affe-aabc-eb3db63ad068.results.json
  test/indexer/data/826dea02-e274-affe-aabc-eb3db63ad068.tdr.anvil.json
  test/service/data/manifest/verbatim/jsonl/anvil/linked.json
  test/service/data/manifest/verbatim/pfb/anvil/pfb_entities.json
  test/service/test_manifest.py
  test/service/test_response_anvil.py
Labels: sandbox, orange, 1 review, reindex:anvildev, reindex:anvilprod
