Repository DataBiosphere/azul, pull requests merged in 2025-01, with the labels that each got.

#6784 Fix: IT fails with no_index in azul_it_flags (#6765)
  src/azul/indexer/__init__.py
  test/integration_test.py
Labels: sandbox, orange, 0 reviews

#6775 Fix: No progress information while copying images to ECR (#6681)
  scripts/manage_images.py
Labels: sandbox, orange, 0 reviews

#6776 Exclude swagger-ui-*.js from GitHub code scanning (#6547)
  .github/codeql/codeql-config.yml
Labels: sandbox, orange, 0 reviews

#6802 Remove portal registration API (#6782)
  attic/rfc/portal-registration-api.yaml
  attic/scripts/manage_portals.py
  attic/scripts/reset_portal_db.py
  attic/src/azul/portal_service.py
  attic/src/azul/version_service.py
  attic/test/service/test_portal_service.py
  attic/test/service/test_version_service.py
  attic/test/version_table_test_case.py
  lambdas/service/app.py
  lambdas/service/openapi.json
  src/azul/__init__.py
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/canned/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr.py
  terraform/dynamo.tf.json.template.py
  test/integration_test.py
  test/service/test_request_validation.py
  test/service/test_response.py
Labels: sandbox, orange, API, 0 reviews

#6761 Exclude tracebacks from error responses (#6420)
  common.mk
  requirements.all.txt
  requirements.dev.trans.txt
  requirements.dev.txt
  scripts/reindex.py
  src/azul/chalice.py
  test/test_app_logging.py
  test/test_log_forwarding.py
Labels: sandbox, orange, 0 reviews, reqs

#6763 Fix: Rebooting GitLab may trigger ClamAV alarm (#6114)
  terraform/gitlab/gitlab.tf.json.template.py
Labels: sandbox, orange, 2 reviews, deploy:gitlab

#6811 Fix: Untagged route in Swagger UI (#6791)
  lambdas/indexer/openapi.json
  lambdas/service/app.py
  lambdas/service/openapi.json
  src/azul/chalice.py
Labels: sandbox, orange, API, 0 reviews

#6817 Move `Annual review of the rule set for audited events` to January (#6813)
  .github/ISSUE_TEMPLATE/audited_events_rule_set_review.md
Labels: sandbox, orange, 0 reviews

#6807 Optimize joiner rejection and re-enable it for AnVIL (#5256)
  src/azul/indexer/__init__.py
  src/azul/indexer/index_service.py
  src/azul/plugins/metadata/anvil/bundle.py
  src/azul/plugins/metadata/hca/bundle.py
Labels: sandbox, orange, 0 reviews, reindex:anvildev, reindex:anvilprod

#6803 Fix: Optimistic lock contention on HCA replicas (#6648)
  deployments/prod/environment.py
  src/azul/collections.py
  src/azul/indexer/aggregate.py
  src/azul/indexer/transform.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/indexer/aggregate.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  src/azul/service/manifest_service.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.results.json
  test/service/test_filters.py
  test/service/test_request_builder.py
Labels: sandbox, orange, 0 reviews, reindex:dev, reindex:prod

#6825 Hotfix prod: Make dcp45 the default catalog on prod (#6806)
  deployments/prod/environment.py
Labels: orange, no sandbox, hotfix

#6830 Backport: fc64aa2b (#6806, PR #6825)
  deployments/prod/environment.py
Labels: orange, no sandbox

#6819 Fix: Facebook crawler excessively hits download endpoint (#6809)
  deployments/anvilbox/environment.py
  deployments/anvildev/environment.py
  deployments/anvilprod/environment.py
  deployments/dev/environment.py
  deployments/hammerbox/environment.py
  deployments/prod/environment.py
  deployments/tempdev/environment.py
  environment.py
  lambdas/indexer/app.py
  lambdas/indexer/openapi.json
  lambdas/service/app.py
  lambdas/service/openapi.json
  src/azul/__init__.py
  src/azul/chalice.py
  swagger/swagger-initializer.js.template.mustache
  terraform/api_gateway.tf.json.template.py
  test/integration_test.py
Labels: sandbox, orange, API, partial

#6822 Adopt mypy (#6821, #4558)
  .github/workflows/ci.yml
  .gitignore
  .gitlab-ci.yml
  .mypy.ini
  bin/wheels/runtime/pyOpenSSL-24.3.0-py3-none-any.whl
  bin/wheels/runtime/pyOpenSSL-25.0.0-py3-none-any.whl
  bin/wheels/runtime/wrapt-1.17.0-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  bin/wheels/runtime/wrapt-1.17.2-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  environment.py
  lambdas/indexer/app.py
  lambdas/layer/app.py
  lambdas/service/app.py
  requirements.all.txt
  requirements.dev.trans.txt
  requirements.dev.txt
  requirements.trans.txt
  requirements.txt
  src/azul/__init__.py
  src/azul/attrs.py
  src/azul/auth.py
  src/azul/azulclient.py
  src/azul/chalice.py
  src/azul/collections.py
  src/azul/health.py
  src/azul/indexer/document.py
  src/azul/indexer/index_controller.py
  src/azul/openapi/params.py
  src/azul/openapi/responses.py
  src/azul/openapi/schema.py
  src/azul/service/catalog_controller.py
  src/azul/types.py
  test/test_app_logging.py
  test/test_openapi.py
Labels: sandbox, orange, partial, reqs

#6668 Support for AnVIL duos_id (#6620)
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/anvil/service/response.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/terra.py
  test/indexer/data/2370f948-2783-aeb6-afea-e022897f4dcf.tdr.anvil.json
  test/indexer/test_anvil.py
  test/service/data/manifest/verbatim/pfb/anvil/pfb_entities.json
  test/service/data/manifest/verbatim/pfb/anvil/pfb_schema.json
  test/service/test_manifest.py
  test/service/test_response_anvil.py
Labels: sandbox, orange, 2 reviews, reindex:anvildev, reindex:anvilprod

#6838 Hotfix anvilprod: Indexing snapshot ANVIL_CMG_Yale_GRU fails due to joiner (#6837)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
Labels: sandbox, orange, 0 reviews, hotfix, reindex:anvilprod

#6720 Add contact information to Swagger UI (#6205)
  lambdas/indexer/openapi.json
  lambdas/service/openapi.json
  scripts/generate_openapi_document.py
  src/azul/__init__.py
  src/azul/chalice.py
  test/test_openapi.py
Labels: sandbox, orange, 3 reviews

#6814 Upgrade dependencies 2025-01-06 (#6805)
  bin/wheels/runtime/boto3-1.35.84-py3-none-any.whl
  bin/wheels/runtime/boto3-1.36.3-py3-none-any.whl
  bin/wheels/runtime/cachetools-5.5.0-py3-none-any.whl
  bin/wheels/runtime/cachetools-5.5.1-py3-none-any.whl
  bin/wheels/runtime/fastavro-1.10.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  bin/wheels/runtime/fastavro-1.9.7-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  bin/wheels/runtime/more_itertools-10.5.0-py3-none-any.whl
  bin/wheels/runtime/more_itertools-10.6.0-py3-none-any.whl
  bin/wheels/runtime/s3transfer-0.10.4-py3-none-any.whl
  bin/wheels/runtime/s3transfer-0.11.1-py3-none-any.whl
  docker_images.json
  environment.boot
  environment.py
  requirements.all.txt
  requirements.dev.trans.txt
  requirements.dev.txt
  requirements.trans.txt
  requirements.txt
  terraform/_schema.json.gz
  terraform/gitlab/gitlab.tf.json.template.py
Labels: sandbox, orange, 0 reviews, reqs, deploy:gitlab, deploy:shared, deploy:runner, backup:gitlab

#6846 Promotion 2025-01-21 anvilprod (#6835)
  .github/workflows/ci.yml
  deployments/prod/environment.py
  src/azul/collections.py
  src/azul/indexer/aggregate.py
  src/azul/indexer/transform.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/indexer/aggregate.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  src/azul/service/manifest_service.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.results.json
  test/service/test_filters.py
  test/service/test_request_builder.py
Labels: sandbox, orange

#6845 Promotion 2025-01-21 prod (#6835)
  .github/workflows/ci.yml
  deployments/prod/environment.py
  src/azul/collections.py
  src/azul/indexer/aggregate.py
  src/azul/indexer/transform.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/indexer/aggregate.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  src/azul/service/manifest_service.py
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.results.json
  test/service/test_filters.py
  test/service/test_request_builder.py
Labels: orange, no sandbox, reindex:prod

#6842 Fix: Alarm api_unauthorized for HeadBucket from AWS Config (#6134)
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, orange, 0 reviews, deploy:shared

#6855 Fix: Redundant manifest generations due to race condition (#6850)
  test/integration_test.py
Labels: sandbox, orange, partial, 1 review

#6826 Implement executive order M-21-31 (#6070)
  src/azul/__init__.py
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, orange, 0 reviews, deploy:shared

#6847 Improve handling of DUOS replicas (#6139)
  src/azul/indexer/transform.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/service/avro_pfb.py
  src/azul/service/manifest_service.py
  test/indexer/data/2370f948-2783-aeb6-afea-e022897f4dcf.tdr.anvil.json
  test/indexer/test_anvil.py
  test/service/data/manifest/verbatim/jsonl/anvil/linked.json
  test/service/data/manifest/verbatim/jsonl/anvil/orphans.json
  test/service/data/manifest/verbatim/jsonl/hca/manifest.json
  test/service/data/manifest/verbatim/pfb/anvil/pfb_entities.json
  test/service/data/manifest/verbatim/pfb/anvil/pfb_schema.json
  test/service/test_manifest.py
Labels: sandbox, orange, base, 0 reviews, reindex:anvildev, reindex:anvilprod

#6831 Log test durations (#5896)
  Makefile
  requirements.all.txt
  requirements.dev.trans.txt
Labels: sandbox, orange, 1 review, reqs

#6863 Include outer entity in accumulator overflow log message (#6793)
  src/azul/indexer/aggregate.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/hca/indexer/transform.py
Labels: sandbox, orange, partial, 0 reviews
