Repository DataBiosphere/azul, pull requests merged in 2025-02, with the labels that each got.

#6867 Remove workaround for utility available in TF AWS provider v5.x (#5257)
  terraform/browser/browser.tf.json.template.py
Labels: sandbox, orange, 0 reviews

#6873 Adopt mypy (#6821)
  .mypy.ini
  src/azul/__init__.py
  src/azul/chalice.py
  src/azul/deployment.py
  src/azul/drs.py
  src/azul/es.py
  src/azul/exceptions.py
  src/azul/files.py
  src/azul/health.py
  src/azul/hmac.py
  src/azul/http.py
  src/azul/iterators.py
  src/azul/json.py
  src/azul/lambdas.py
  src/azul/modules.py
  src/azul/oauth2.py
  src/azul/objects.py
  src/azul/queues.py
  src/azul/template.py
  src/azul/terra.py
  src/azul/terraform.py
  src/azul/threads.py
  src/azul/time.py
  src/azul/types.py
  test/indexer/test_tdr.py
  test/test_doctests.py
Labels: sandbox, orange, partial

#6877 Prototype mirroring of a single HCA file (#6857)
  scripts/mirror_file.py
  src/azul/service/storage_service.py
Labels: sandbox, orange, 0 reviews

#6872 Fix: Verbatim PFB manifest to failure due to missing DUOS registration (#6871)
  src/azul/plugins/repository/tdr_anvil/__init__.py
Labels: sandbox, orange, 0 reviews, reindex:anvildev, reindex:anvilprod

#6870 Remove `tenacity` warning suppression for tests (#2070)
  test/azul_test_case.py
Labels: sandbox, orange, 0 reviews

#6890 Fix: AssertionError indexing snapshot not registered in DUOS (#6883)
  src/azul/terra.py
  test/azul_test_case.py
  test/indexer/test_anvil.py
Labels: sandbox, orange, reindex:anvildev

#6818 Fix: GitHub CI workflow selects dev when building prod branch (#5428, #6823)
  .dockerignore
  .github/workflows/ci.yml
  Dockerfile
  requirements.all.txt
  requirements.dev.trans.txt
  scripts/check_branch.py
  test/test_check_branch.py
Labels: sandbox, orange, 2 reviews, reqs

#6880 Fix: UnicodeDecodeError raised by log forwarder (#5582)
  src/azul/indexer/log_forwarding_service.py
Labels: sandbox, orange, 0 reviews

#6881 Promotion 2025-02-04 anvilprod (#6878)
  Makefile
  requirements.all.txt
  requirements.dev.trans.txt
  src/azul/__init__.py
  src/azul/indexer/aggregate.py
  src/azul/indexer/transform.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/service/avro_pfb.py
  src/azul/service/manifest_service.py
  terraform/shared/shared.tf.json.template.py
  test/indexer/data/2370f948-2783-aeb6-afea-e022897f4dcf.tdr.anvil.json
  test/indexer/test_anvil.py
  test/service/data/manifest/verbatim/jsonl/anvil/linked.json
  test/service/data/manifest/verbatim/jsonl/anvil/orphans.json
  test/service/data/manifest/verbatim/jsonl/hca/manifest.json
  test/service/data/manifest/verbatim/pfb/anvil/pfb_entities.json
  test/service/data/manifest/verbatim/pfb/anvil/pfb_schema.json
  test/service/test_manifest.py
Labels: sandbox, orange, reqs, reindex:anvilprod, deploy:shared

#6815 Add relations to PFB-based verbatim manifest for AnVIL (#6066)
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/service/avro_pfb.py
  src/azul/service/manifest_service.py
  test/integration_test.py
  test/service/data/manifest/verbatim/pfb/anvil/pfb_entities.json
  test/service/test_manifest.py
Labels: sandbox, orange, 0 reviews

#6882 Promotion 2025-02-04 prod (#6878)
  Makefile
  requirements.all.txt
  requirements.dev.trans.txt
  src/azul/__init__.py
  src/azul/indexer/aggregate.py
  src/azul/indexer/transform.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/anvil/__init__.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/service/avro_pfb.py
  src/azul/service/manifest_service.py
  terraform/shared/shared.tf.json.template.py
  test/indexer/data/2370f948-2783-aeb6-afea-e022897f4dcf.tdr.anvil.json
  test/indexer/test_anvil.py
  test/service/data/manifest/verbatim/jsonl/anvil/linked.json
  test/service/data/manifest/verbatim/jsonl/anvil/orphans.json
  test/service/data/manifest/verbatim/jsonl/hca/manifest.json
  test/service/data/manifest/verbatim/pfb/anvil/pfb_entities.json
  test/service/data/manifest/verbatim/pfb/anvil/pfb_schema.json
  test/service/test_manifest.py
Labels: orange, no sandbox, reqs, deploy:shared

#6747 Assert metadata schema location (#6516)
  UPGRADING.rst
  deployments/dev/environment.py
  deployments/sandbox/environment.py
  src/azul/plugins/repository/tdr_hca/__init__.py
  src/humancellatlas/data/metadata/api.py
  test/azul_test_case.py
  test/hca_metadata_api/test.py
  test/indexer/data/1b6d8348-d6e9-406a-aa6a-7ee886e52bf9.tdr.hca.json
  test/indexer/data/d8c20944-739f-4e7d-9161-b720953432ce.tables.tdr.json
Labels: sandbox, orange, 4+ reviews, reindex:dev, upgrade, reindex:prod, reindex:partial

#6879 Implement executive order M-21-31 (#6070)
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, orange, 3 reviews, deploy:shared

#6896 Add issue type to existing issues in all repos (#6889)
  .github/ISSUE_TEMPLATE/audited_events_rule_set_review.md
  .github/ISSUE_TEMPLATE/blank.md
  .github/ISSUE_TEMPLATE/fedramp_inventory_review.md
  .github/ISSUE_TEMPLATE/opensearch_updates.md
  .github/ISSUE_TEMPLATE/promotion.md
  .github/ISSUE_TEMPLATE/public_access_content_review.md
  .github/ISSUE_TEMPLATE/upgrade.md
Labels: orange, partial, 0 reviews, no sandbox

#6904 Hotfix prod: Index dcp46 in prod (#6902)
  deployments/prod/environment.py
Labels: orange, no sandbox, hotfix, reindex:prod, reindex:partial

#6891 Adopt mypy (#6821)
  .mypy.ini
  lambdas/service/app.py
  src/azul/__init__.py
  src/azul/indexer/__init__.py
  src/azul/indexer/document.py
  src/azul/indexer/document_service.py
  src/azul/indexer/field.py
  src/azul/indexer/index_service.py
  src/azul/indexer/transform.py
  src/azul/openapi/schema.py
  src/azul/plugins/__init__.py
  src/azul/plugins/metadata/anvil/bundle.py
  src/azul/plugins/metadata/anvil/indexer/transform.py
  src/azul/plugins/metadata/hca/bundle.py
  src/azul/plugins/metadata/hca/indexer/aggregate.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  src/azul/plugins/repository/canned/__init__.py
  src/azul/plugins/repository/dss/__init__.py
  src/azul/plugins/repository/tdr.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/plugins/repository/tdr_hca/__init__.py
  src/azul/service/avro_pfb.py
  src/azul/service/elasticsearch_service.py
  src/azul/service/manifest_service.py
  src/azul/service/repository_controller.py
  src/azul/terra.py
  src/azul/types.py
  src/azul/uuids.py
  test/indexer/__init__.py
  test/indexer/test_indexer.py
  test/service/test_request_builder.py
  test/service/test_response.py
Labels: sandbox, orange, partial

#6899 Fix: Filters other than dataset_id break verbatim handover to Terra (#6898)
  src/azul/service/manifest_service.py
  test/integration_test.py
  test/service/test_manifest.py
Labels: sandbox, orange, 0 reviews

#6907 Backport: 660a05b5 (#6902, PR #6904)
  deployments/prod/environment.py
Labels: orange, no sandbox, operator

#6901 Fix: Images not deployed after manual deletion from ECR (#5747)
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, orange, 0 reviews, deploy:shared

#6914 Automatic JSON serialization of attrs-decorated classes (#6821)
  scripts/can_bundle.py
  src/azul/attrs.py
  src/azul/azulclient.py
  src/azul/indexer/__init__.py
  src/azul/indexer/document.py
  src/azul/indexer/index_controller.py
  src/azul/indexer/index_service.py
  src/azul/json.py
  src/azul/plugins/__init__.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/types.py
  test/indexer/test_indexer.py
  test/indexer/test_indexer_controller.py
  test/integration_test.py
Labels: sandbox, orange, partial

#6893 Create mirror queues and bucket (#6859)
  deployments/dev/environment.py
  deployments/sandbox/environment.py
  environment.py
  lambdas/indexer/app.py
  scripts/mirror_file.py
  src/azul/__init__.py
  src/azul/azulclient.py
  src/azul/deployment.py
  src/azul/health.py
  src/azul/indexer/index_controller.py
  src/azul/lambdas.py
  src/azul/queues.py
  src/azul/service/storage_service.py
  terraform/cloudwatch_dashboard.template.json.py
  terraform/s3.tf.json.template.py
  terraform/sqs.tf.json.template.py
  test/sqs_test_case.py
Labels: sandbox, orange, 0 reviews

#6931 Automatic (de)serialization for bundles (#6821)
  scripts/can_bundle.py
  src/azul/attrs.py
  src/azul/collections.py
  src/azul/indexer/__init__.py
  src/azul/indexer/document.py
  src/azul/json.py
  src/azul/plugins/metadata/anvil/bundle.py
  src/azul/plugins/metadata/hca/bundle.py
  src/azul/plugins/repository/tdr_anvil/__init__.py
  src/azul/plugins/repository/tdr_hca/__init__.py
  test/indexer/__init__.py
  test/indexer/test_anvil.py
  test/indexer/test_tdr.py
  test/integration_test.py
  test/service/test_manifest.py
  test/test_doctests.py
Labels: sandbox, orange, reindex:dev, reindex:anvildev

#6908 Fix: check_branch.py fails on chained PRs (#6906)
  .github/workflows/ci.yml
Labels: sandbox, orange, 1 review, base

#6894 Support for HCA duos_id (#6196)
  lambdas/service/app.py
  lambdas/service/openapi.json
  src/azul/plugins/metadata/hca/__init__.py
  src/azul/plugins/metadata/hca/indexer/transform.py
  src/azul/plugins/metadata/hca/service/response.py
  src/humancellatlas/data/metadata/api.py
  test/indexer/data/80baee6e-00a5-4fdc-bfe3-d339ff8a7178.dss.hca.json
  test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.results.json
  test/service/data/manifest/terra/pfb_entities.json
  test/service/data/manifest/terra/pfb_schema.json
  test/service/test_index_projects.py
  test/service/test_response.py
Labels: sandbox, orange, API, 1 review, reindex:dev, reindex:prod
