Repository DataBiosphere/azul, pull requests merged in 2025-07, with the labels that each got.

#7246 Backport: 031675ea (#7244)
  src/azul/plugins/metadata/hca/__init__.py
Labels: sandbox, orange

#7270 Fix: File size aggregation is broken for AnVIL (#6988)
  lambdas/service/app.py
  lambdas/service/openapi.json
  src/azul/plugins/metadata/anvil/indexer/aggregate.py
  src/azul/plugins/metadata/anvil/service/response.py
  test/indexer/data/826dea02-e274-affe-aabc-eb3db63ad068.results.json
  test/service/test_response_anvil.py
Labels: sandbox, orange, API, 0 reviews, reindex:anvildev, reindex:anvilprod

#7266 Fix: Indexing attempt numbers are logged as strings (#7083)
  src/azul/indexer/action_controller.py
Labels: sandbox, orange, 0 reviews

#7273 Fix: CSP: Failure to Define Directive with No Fallback (DataBiosphere/azul-private#234)
  src/azul/csp.py
Labels: sandbox, orange, 0 reviews

#7238 Plan for VPN server and client certificate expiration (#6331)
  .github/ISSUE_TEMPLATE/vpn_certificate_renewals.md
  README.md
  terraform/gitlab/vpn/Makefile
Labels: orange, 2 reviews, no sandbox

#7285 Remove ANVIL_GREGoR_R02_GRU from all catalogs (DataBiosphere/azul-private#271)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
Labels: sandbox, orange, 0 reviews, hotfix, reindex:anvilprod, reindex:partial

#7277 Update Docker to 28.0.4 (#6961)
  docker_images.json
  environment.boot
  environment.py
  requirements.all.txt
  requirements.dev.trans.txt
Labels: sandbox, orange, 0 reviews, reqs, deploy:gitlab, deploy:shared, deploy:runner

#7267 Log important SQS message attributes on receipt (#7170)
  src/azul/indexer/action_controller.py
  src/azul/indexer/index_controller.py
  src/azul/indexer/index_queue_service.py
  src/azul/queues.py
  test/indexer/test_index_controller.py
  test/sqs_test_case.py
Labels: sandbox, orange, 1 review

#7269 Fix: Mirrored file objects store content type in S3 (#7265)
  requirements.all.txt
  requirements.dev.trans.txt
  src/azul/indexer/mirror_service.py
  src/azul/service/repository_controller.py
  src/azul/service/storage_service.py
Labels: sandbox, orange, partial, 0 reviews, reqs

#7184 Improvements to validate_snapshots.py (#7139)
  scripts/find_in_snapshots.py
Labels: sandbox, orange, 0 reviews

#7300 CIS Hardened Image Level 1 on Amazon Linux 2 Kernel 5.10 (#7261)
  OPERATOR.rst
  terraform/gitlab/gitlab.tf.json.template.py
Labels: sandbox, orange, 0 reviews

#7309 Upgrade dependencies 2025-07-21 (#7291)
  bin/wheels/runtime/boto3-1.39.13-py3-none-any.whl
  bin/wheels/runtime/boto3-1.39.7-py3-none-any.whl
  docker_images.json
  environment.boot
  environment.py
  requirements.all.txt
  requirements.dev.txt
  requirements.txt
  scripts/update_swagger.py
  terraform/gitlab/gitlab.tf.json.template.py
Labels: sandbox, orange, reqs, deploy:gitlab, deploy:shared, deploy:runner, backup:gitlab

#7298 Fix: Log request body (#6404)
  src/azul/chalice.py
  src/azul/deployment.py
  src/azul/es.py
  src/azul/http.py
  src/azul/json.py
  src/azul/logging.py
  test/service/test_app_logging.py
  test/test_app_logging.py
  test/test_http.py
Labels: orange, 0 reviews
