Repository DataBiosphere/azul, pull requests merged in 2025-03, with the labels that each got.

#6935 Backport: f3d3a77 (#6925, PR #6913)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
Labels: orange, no sandbox

#6934 Fix: Facebook crawler excessively hits download endpoint (#6809)
  deployments/anvildev/environment.py
  deployments/dev/environment.py
Labels: orange, 0 reviews, no sandbox

#6933 Temporarily disable exporting relations (#6929)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
  deployments/prod/environment.py
  environment.py
  src/azul/__init__.py
  src/azul/service/manifest_service.py
Labels: sandbox, orange, 1 review

#6951 Fix: test_verbatim_pfb_manifest fails when relations are disabled (#6949)
  test/service/test_manifest.py
Labels: sandbox, orange

#6957 Hotfix prod: Make dcp46 & lm8 default catalogs on prod (#6922, #6954, #6955, #6956)
  deployments/prod/environment.py
Labels: orange, partial, no sandbox, hotfix, reindex:prod, reindex:lmprod

#6968 Backport: 9741b17c (#6922, #6954, #6955, #6956, PR #6957)
  deployments/prod/environment.py
Labels: orange, no sandbox

#6972 Promotion 2025-03-11 prod (#6959)
  .github/CODEOWNERS
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
Labels: orange, no sandbox

#6971 Promotion 2025-03-11 anvilprod (#6959)
  .github/CODEOWNERS
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
  deployments/prod/environment.py
Labels: sandbox, orange, reindex:anvilprod

#6977 Hotfix anvilprod: Indexing anvil9 snapshot `ANVIL_CMG_Yale_GRU` fails due to joiner (#6976)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
Labels: sandbox, orange, hotfix

#6900 Implement executive order M-21-31 (#6070)
  scripts/import_cloudwatch_log_groups.py
  src/azul/terraform.py
  terraform/Makefile
  terraform/api_gateway.tf.json.template.py
  terraform/shared/Makefile
  terraform/shared/shared.tf.json.template.py
Labels: sandbox, hold warm, orange, 3 reviews, deploy:shared

#6905 Implement mirror_source (#6860)
  deployments/dev/environment.py
  deployments/sandbox/environment.py
  environment.py
  lambdas/indexer/.chalice/config.json.template.py
  lambdas/indexer/app.py
  scripts/mirror.py
  src/azul/__init__.py
  src/azul/azulclient.py
  src/azul/deployment.py
  src/azul/indexer/action_controller.py
  src/azul/indexer/index_controller.py
  src/azul/indexer/lambda_iam_policy.py
  src/azul/indexer/mirror_controller.py
  src/azul/queues.py
  terraform/sqs.tf.json.template.py
  test/indexer/test_index_controller.py
  test/indexer/test_mirror_controller.py
  test/integration_test.py
  test/sqs_test_case.py
Labels: sandbox, orange, 1 review, base

#6999 Hotfix prod: Reindex lm8 (#6997)
  deployments/prod/environment.py
Labels: orange, no sandbox, hotfix, reindex:prod, reindex:partial

#6974 Backport: 918fbf5 (PR #6971), dd3b28e (#6976, PR #6977)
  deployments/anvilprod/environment.py
  deployments/hammerbox/environment.py
Labels: orange, 1 review, no sandbox
